// Every in-app notification kind the collaboration system can raise. Kept as a
// const tuple so both the service and the client DTOs share one source of
// truth. Reminder-driven notifications reuse the legacy 'reminder' type.
export const NOTIFICATION_TYPES = [
  'reminder',
  'task_overdue',
  'task_invite',
  'invite_accepted',
  'invite_declined',
  'member_joined',
  'member_removed',
  'member_role_changed',
  'ownership_transferred',
  'task_updated',
  'task_completed',
  'due_date_changed',
  'priority_changed',
  'reminder_updated',
  'subtask_completed',
  'attachment_added',
  'comment_added',
  'mention',
  'ai_plan_applied',
  'ai_recommendation_ready',
  'weather_travel',
  'task_assistant',
  'task_created',
  'task_reopened',
  'task_assigned',
  'task_status_changed',
  'calendar_event_created',
  'calendar_event_updated',
  'calendar_event_cancelled',
  'calendar_conflict',
  'schedule_changed',
  'deadline_changed',
  'focus_session_scheduled',
  'focus_session_completed',
  'focus_session_cancelled',
  'focus_reminder',
  'focus_session_missed',
  'deadline_risk',
  'workload_warning',
  'planner_suggestion',
  'time_capsule_ready',
] as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[number];
