CREATE TABLE IF NOT EXISTS "supervision_relationships" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "guardian_user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE cascade, "supervised_user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE cascade, "status" varchar(16) DEFAULT 'pending' NOT NULL, "permissions" jsonb DEFAULT '{"level":"plan_only"}'::jsonb NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "accepted_at" timestamp, "revoked_at" timestamp, "updated_at" timestamp DEFAULT now() NOT NULL, CONSTRAINT "supervision_relationships_no_self" CHECK ("guardian_user_id" <> "supervised_user_id"));
CREATE INDEX IF NOT EXISTS "idx_supervision_guardian" ON "supervision_relationships" ("guardian_user_id", "status");
CREATE INDEX IF NOT EXISTS "idx_supervision_supervised" ON "supervision_relationships" ("supervised_user_id", "status");

CREATE TABLE IF NOT EXISTS "supervision_rules" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "relationship_id" uuid NOT NULL REFERENCES "supervision_relationships"("id") ON DELETE cascade, "created_by" uuid NOT NULL REFERENCES "users"("id") ON DELETE cascade, "name" varchar(255) NOT NULL, "starts_at" timestamp NOT NULL, "ends_at" timestamp NOT NULL, "repeat" jsonb DEFAULT '{"type":"once"}'::jsonb NOT NULL, "mode" varchar(24) NOT NULL, "status" varchar(16) DEFAULT 'scheduled' NOT NULL, "task_id" uuid REFERENCES "tasks"("id") ON DELETE set null, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS "idx_supervision_rules_relationship" ON "supervision_rules" ("relationship_id", "status");
CREATE INDEX IF NOT EXISTS "idx_supervision_rules_schedule" ON "supervision_rules" ("status", "starts_at", "ends_at");

CREATE TABLE IF NOT EXISTS "supervision_overrides" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "rule_id" uuid NOT NULL REFERENCES "supervision_rules"("id") ON DELETE cascade, "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE cascade, "reason" varchar(40) NOT NULL, "requested_at" timestamp DEFAULT now() NOT NULL, "effective_at" timestamp DEFAULT now() NOT NULL);

CREATE TABLE IF NOT EXISTS "supervision_audit_logs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "relationship_id" uuid NOT NULL REFERENCES "supervision_relationships"("id") ON DELETE cascade, "actor_user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE cascade, "event" varchar(48) NOT NULL, "rule_id" uuid REFERENCES "supervision_rules"("id") ON DELETE set null, "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS "idx_supervision_audit_relationship" ON "supervision_audit_logs" ("relationship_id", "created_at");
