import { useEffect, useState } from 'react'
import { AppLayout, PrimaryButton, SecondaryButton, SectionCard, type SidebarNavHandlers } from '../../components/layout'
import { useLanguage } from '../../i18n/LanguageContext'
import { AppIcon } from './AppIcon'
import { supervisionApi, SupervisionApiError, type GuardianTask, type Relationship, type SafeIdentity } from './api'

type Translate=(key:string,params?:Record<string,string|number>)=>string
const label=(v?:string)=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
const auditKeys:Record<string,string>={app_management_consent_updated:'supervision.audit.appManagementConsentUpdated',app_management_consent_revoked:'supervision.audit.appManagementConsentRevoked',permissions_updated:'supervision.audit.permissionsUpdated',accepted:'supervision.audit.accepted',rejected:'supervision.audit.rejected',requested:'supervision.audit.requested',revoked:'supervision.audit.revoked',rule_created:'supervision.audit.ruleCreated',rule_updated:'supervision.audit.ruleUpdated',override_used:'supervision.audit.overrideUsed',rule_pause:'supervision.audit.rulePaused',rule_resume:'supervision.audit.ruleResumed',rule_end:'supervision.audit.ruleEnded',rule_started:'supervision.audit.ruleStarted',rule_task_completed:'supervision.audit.ruleTaskCompleted',rule_time_expired:'supervision.audit.ruleTimeExpired'}
const modeKeys:Record<string,string>={time:'supervision.options.untilTime',task:'supervision.options.untilTaskCompleted',task_or_time:'supervision.options.taskOrTime'}
const levelKeys:Record<string,string>={plan_only:'supervision.levels.planOnly',accountability:'supervision.levels.accountability',progress_only:'supervision.levels.progressOnly',device_restrictions:'supervision.levels.deviceRestrictions'}
const localized=(t:Translate,key?:string,fallback?:string)=>key?t(key):label(fallback)
export const identityLabel=(p?:SafeIdentity,fallback='BeePlan user')=>p?.displayName?.trim()||(p?.username?`@${p.username}`:fallback)
export const initials=(p?:SafeIdentity)=>identityLabel(p).replace(/^@/,'').split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'BP'
export const remainingMinutes=(estimated=0,focused=0)=>Math.max(estimated-focused,0)
export const canCreateRestriction=(mode:string,taskId:string,apps:string[])=>apps.length>0&&(mode==='time'||Boolean(taskId))
function Avatar({person}:{person?:SafeIdentity}){const[bad,setBad]=useState(false);return person?.avatarUrl&&!bad?<img src={person.avatarUrl} alt="" onError={()=>setBad(true)} className="h-12 w-12 rounded-full object-cover"/>:<span className="grid h-12 w-12 place-items-center rounded-full bg-[var(--bp-accent-soft)] font-black text-[var(--bp-accent-ink)]">{initials(person)}</span>}
function AppRow({app,selected,onClick,t}:{app:any;selected?:boolean;onClick?:()=>void;t:Translate}){return <button type="button" aria-pressed={selected} onClick={onClick} className={`flex min-h-20 w-full items-center gap-3 rounded-xl border p-3 text-start transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--bp-accent)] ${selected?'border-[var(--bp-accent)] bg-[var(--bp-accent-soft)]':'border-[var(--bp-border)] bg-[var(--bp-bg)] hover:bg-[var(--bp-surface)]'}`}><AppIcon app={app}/><span className="min-w-0 flex-1"><b className="block truncate text-sm">{app.displayName}</b><small className="text-[var(--bp-muted)]">{app.enforceable?t('supervision.app.strictModeIntervention'):t('supervision.app.accountabilityOnly')}</small></span><span className="text-lg" aria-hidden>{selected?'✓':'○'}</span></button>}
export function SupervisionScreen({accessToken,...nav}:SidebarNavHandlers&{accessToken:string}){const{t}=useLanguage();const[rels,setRels]=useState<Relationship[]>([]),[selected,setSelected]=useState<Relationship|null>(null),[apps,setApps]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[tasks,setTasks]=useState<GuardianTask[]>([]),[audit,setAudit]=useState<any[]>([]),[coreState,setCoreState]=useState<'loading'|'ready'|'error'>('loading'),[detailError,setDetailError]=useState(''),[creating,setCreating]=useState(false);const[form,setForm]=useState({name:t('supervision.defaults.restrictionName'),restrictionMode:'task_or_time',taskId:'',duration:'120',managedAppIds:[] as string[]})
 const loadCore=()=>{setCoreState('loading');if(import.meta.env.DEV)console.info('[Supervision:Web] relationships request start');void supervisionApi.relationships(accessToken).then(r=>{if(import.meta.env.DEV)console.info(`[Supervision:Web] relationships request success count=${r.length}`);setRels(r);setSelected(s=>s?r.find(x=>x.id===s.id)??null:s);setCoreState('ready')}).catch(error=>{if(import.meta.env.DEV){const safe=error instanceof SupervisionApiError?`status=${error.status} category=${error.category}`:'category=network_or_unknown';console.info(`[Supervision:Web] relationships request failed ${safe}`)}setCoreState('error')})};useEffect(loadCore,[accessToken]);useEffect(()=>{if(!selected)return;setDetailError('');void Promise.all([supervisionApi.approvedApps(accessToken,selected.id),supervisionApi.rules(accessToken,selected.id),supervisionApi.tasks(accessToken,selected.id,'active'),supervisionApi.audit(accessToken,selected.id)]).then(([a,r,tasksResult,auditResult])=>{setApps(a);setRules(r);setTasks(tasksResult);setAudit(auditResult)}).catch(()=>setDetailError(t('supervision.errors.detailLoadFailed')))},[selected,accessToken,t])
 const create=async()=>{if(!selected||!canCreateRestriction(form.restrictionMode,form.taskId,form.managedAppIds))return;setCreating(true);try{const now=new Date(),end=new Date(now.getTime()+Number(form.duration)*60000);await supervisionApi.createRule(accessToken,selected.id,{...form,startsAt:now.toISOString(),endsAt:form.restrictionMode==='task'?undefined:end.toISOString()});setRules(await supervisionApi.rules(accessToken,selected.id))}catch{setDetailError(t('supervision.errors.createFailed'))}finally{setCreating(false)}}
 if(coreState!=='ready')return <AppLayout active="supervision" {...nav}><main className="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:px-6"><header><p className="text-sm font-black text-[var(--bp-accent-ink)]">{t('supervision.title')}</p><h1 className="mt-1 text-3xl font-black">{t('supervision.heading')}</h1></header><SectionCard>{coreState==='loading'?<p>{t('supervision.loading')}</p>:<><p role="alert" className="text-rose-600">{t('supervision.errors.loadFailed')}</p><PrimaryButton className="mt-3" onClick={loadCore}>{t('supervision.actions.retry')}</PrimaryButton></>}</SectionCard></main></AppLayout>
 return <AppLayout active="supervision" {...nav}><main className="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:px-6"><header><p className="text-sm font-black text-[var(--bp-accent-ink)]">{t('supervision.title')}</p><h1 className="mt-1 text-3xl font-black">{t('supervision.heading')}</h1><p className="mt-2 text-sm text-[var(--bp-muted)]">{t('supervision.description')}</p></header>{detailError&&<p role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-600">{detailError}</p>}
 {!selected?<section className="grid gap-3 sm:grid-cols-2">{rels.filter(r=>r.status==='active'&&r.currentRole==='guardian').map(r=><button key={r.id} onClick={()=>setSelected(r)} className="flex items-center gap-3 rounded-2xl border border-[var(--bp-border)] bg-[var(--bp-surface)] p-4 text-start hover:border-[var(--bp-accent)]"><Avatar person={r.supervisedUser}/><span><b>{identityLabel(r.supervisedUser,t('supervision.userFallback'))}</b><small className="mt-1 block text-[var(--bp-muted)]">{localized(t,levelKeys[r.permissions.level],r.permissions.level)} · {t('supervision.actions.openDashboard')}</small></span></button>)}{!rels.length&&<SectionCard><p className="font-bold">{t('supervision.empty.title')}</p><p className="text-sm text-[var(--bp-muted)]">{t('supervision.empty.description')}</p></SectionCard>}</section>:<><SecondaryButton onClick={()=>setSelected(null)}>← {t('supervision.actions.people')}</SecondaryButton><SectionCard><div className="flex items-center gap-3"><Avatar person={selected.supervisedUser}/><div className="min-w-0"><h2 className="text-xl font-black">{identityLabel(selected.supervisedUser,t('supervision.userFallback'))}</h2><p className="text-sm text-[var(--bp-muted)]">{selected.supervisedUser.username?`@${selected.supervisedUser.username} · `:''}{localized(t,levelKeys[selected.permissions.level],selected.permissions.level)} · {t('supervision.status.active')}</p></div></div></SectionCard>
 <section><div className="mb-3 flex items-center justify-between"><div><h2 className="text-xl font-black">{t('supervision.restrictions.title')}</h2><p className="text-sm text-[var(--bp-muted)]">{t('supervision.restrictions.description')}</p></div></div>{rules.length?<div className="grid gap-3 md:grid-cols-2">{rules.map(r=>{const picked=apps.filter(a=>(r.appSelection?.managedAppIds??[]).includes(a.id));return <SectionCard key={r.id}><div className="flex items-start justify-between gap-3"><h3 className="font-black">{r.name}</h3><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-black text-emerald-600">{t(`supervision.status.${r.status}`)}</span></div><p className="mt-4 text-xs font-black uppercase tracking-wide text-[var(--bp-muted)]">{t('supervision.restrictions.restrictedApps')}</p><div className="mt-2 space-y-2">{picked.length?picked.map(a=><div key={a.id} className="flex items-center gap-2"><AppIcon app={a} size="sm"/><span className="text-sm font-bold">{a.displayName}</span></div>):<p className="text-sm text-[var(--bp-muted)]">{t('supervision.restrictions.approvedAppsUnavailable')}</p>}</div><dl className="mt-4 space-y-2 text-sm"><div><dt className="text-[var(--bp-muted)]">{t('supervision.restrictions.endsWhen')}</dt><dd className="font-semibold">{localized(t,modeKeys[r.restrictionMode],r.restrictionMode)}{r.endsAt?' · '+new Date(r.endsAt).toLocaleString():''}</dd></div><div><dt className="text-[var(--bp-muted)]">{t('supervision.restrictions.enforcement')}</dt><dd className="font-semibold">{t('supervision.app.accountabilityOnly')}</dd></div></dl></SectionCard>})}</div>:<SectionCard><p className="font-bold">{t('supervision.restrictions.noneActive')}</p></SectionCard>}</section>
 {selected.permissions.level==='device_restrictions'&&<div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]"><SectionCard><h2 className="text-xl font-black">{t('supervision.create.title')}</h2><p className="mt-1 text-sm text-[var(--bp-muted)]">{t('supervision.create.description')}</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['supervision.create.fields.restriction','name'],['supervision.create.fields.releaseCondition','restrictionMode'],['supervision.create.fields.task','taskId'],['supervision.create.fields.maximumDuration','duration']].map(([title,key])=><label key={key} className={`${key==='taskId'&&form.restrictionMode==='time'?'hidden':''} block text-xs font-black`}>{t(title)}{key==='name'?<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-[var(--bp-border)] bg-[var(--bp-input)] px-3 py-2 text-sm"/>:<select value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-[var(--bp-border)] bg-[var(--bp-input)] px-3 py-2 text-sm">{key==='restrictionMode'?<><option value="time">{t('supervision.options.untilTime')}</option><option value="task">{t('supervision.options.untilTaskCompleted')}</option><option value="task_or_time">{t('supervision.options.taskOrTime')}</option></>:key==='taskId'?<><option value="">{t('supervision.create.selectTask')}</option>{tasks.map(task=><option key={task.id} value={task.id}>{task.title} ({task.progress}%)</option>)}</>:['15','30','60','120'].map(v=><option key={v} value={v}>{t('supervision.durationMinutes',{count:v})}</option>)}</select>}</label>)}</div><p className="mt-5 text-sm font-black">{t('supervision.restrictions.approvedApps')}</p><div className="mt-2 grid gap-3 sm:grid-cols-2">{apps.map(a=><AppRow key={a.id} app={a} t={t} selected={form.managedAppIds.includes(a.id)} onClick={()=>setForm(f=>({...f,managedAppIds:f.managedAppIds.includes(a.id)?f.managedAppIds.filter(id=>id!==a.id):[...f.managedAppIds,a.id]}))}/>)}</div><PrimaryButton className="mt-5" loading={creating} disabled={creating||!canCreateRestriction(form.restrictionMode,form.taskId,form.managedAppIds)} onClick={create}>{creating?t('supervision.actions.creatingRestriction'):t('supervision.actions.createRestriction')}</PrimaryButton></SectionCard><SectionCard><h2 className="text-lg font-black">{t('supervision.activity.title')}</h2><div className="mt-4 space-y-4">{audit.length?audit.slice(0,6).map(a=><div key={a.id} className="border-s border-[var(--bp-border)] ps-3"><p className="text-sm font-bold">{localized(t,auditKeys[a.event],a.event)}</p><p className="mt-1 text-xs text-[var(--bp-muted)]">{new Date(a.createdAt).toLocaleString()}</p></div>):<p className="text-sm text-[var(--bp-muted)]">{t('supervision.activity.empty')}</p>}</div></SectionCard></div>}</>}</main></AppLayout>}
