import { useEffect, useState } from 'react'
import { AppLayout, PrimaryButton, SecondaryButton, SectionCard, type SidebarNavHandlers } from '../../components/layout'
import { AppIcon } from './AppIcon'
import { supervisionApi, type GuardianTask, type Relationship, type SafeIdentity } from './api'

const label=(v?:string)=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
const auditLabel:Record<string,string>={app_management_consent_updated:'App management consent updated',permissions_updated:'Sharing permissions updated',accepted:'Supervision accepted',requested:'Supervision requested'}
export const identityLabel=(p?:SafeIdentity)=>p?.displayName?.trim()||(p?.username?`@${p.username}`:'BeePlan user')
export const initials=(p?:SafeIdentity)=>identityLabel(p).replace(/^@/,'').split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'BP'
export const remainingMinutes=(estimated=0,focused=0)=>Math.max(estimated-focused,0)
export const canCreateRestriction=(mode:string,taskId:string,apps:string[])=>apps.length>0&&(mode==='time'||Boolean(taskId))
function Avatar({person}:{person?:SafeIdentity}){const[bad,setBad]=useState(false);return person?.avatarUrl&&!bad?<img src={person.avatarUrl} alt="" onError={()=>setBad(true)} className="h-12 w-12 rounded-full object-cover"/>:<span className="grid h-12 w-12 place-items-center rounded-full bg-[var(--bp-accent-soft)] font-black text-[var(--bp-accent-ink)]">{initials(person)}</span>}
function AppRow({app,selected,onClick}:{app:any;selected?:boolean;onClick?:()=>void}){return <button type="button" aria-pressed={selected} onClick={onClick} className={`flex min-h-20 w-full items-center gap-3 rounded-xl border p-3 text-start transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--bp-accent)] ${selected?'border-[var(--bp-accent)] bg-[var(--bp-accent-soft)]':'border-[var(--bp-border)] bg-[var(--bp-bg)] hover:bg-[var(--bp-surface)]'}`}><AppIcon app={app}/><span className="min-w-0 flex-1"><b className="block truncate text-sm">{app.displayName}</b><small className="text-[var(--bp-muted)]">{app.enforceable?'Strict Mode intervention':'Accountability only'}</small></span><span className="text-lg" aria-hidden>{selected?'✓':'○'}</span></button>}
export function SupervisionScreen({accessToken,...nav}:SidebarNavHandlers&{accessToken:string}){const[rels,setRels]=useState<Relationship[]>([]),[selected,setSelected]=useState<Relationship|null>(null),[apps,setApps]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[tasks,setTasks]=useState<GuardianTask[]>([]),[audit,setAudit]=useState<any[]>([]),[error,setError]=useState(''),[creating,setCreating]=useState(false);const[form,setForm]=useState({name:'Study Mode',restrictionMode:'task_or_time',taskId:'',duration:'120',managedAppIds:[] as string[]})
 const load=()=>supervisionApi.relationships(accessToken).then(r=>{setRels(r);setSelected(s=>s?r.find(x=>x.id===s.id)??null:s)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[accessToken]);useEffect(()=>{if(!selected)return;void Promise.all([supervisionApi.approvedApps(accessToken,selected.id),supervisionApi.rules(accessToken,selected.id),supervisionApi.tasks(accessToken,selected.id,'active'),supervisionApi.audit(accessToken,selected.id)]).then(([a,r,t,l])=>{setApps(a);setRules(r);setTasks(t);setAudit(l)}).catch(e=>setError(e.message))},[selected,accessToken])
 const create=async()=>{if(!selected||!canCreateRestriction(form.restrictionMode,form.taskId,form.managedAppIds))return;setCreating(true);try{const now=new Date(),end=new Date(now.getTime()+Number(form.duration)*60000);await supervisionApi.createRule(accessToken,selected.id,{...form,startsAt:now.toISOString(),endsAt:form.restrictionMode==='task'?undefined:end.toISOString()});setRules(await supervisionApi.rules(accessToken,selected.id))}catch(e){setError(e instanceof Error?e.message:'Could not create restriction.')}finally{setCreating(false)}}
 return <AppLayout active="supervision" {...nav}><main className="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:px-6"><header><p className="text-sm font-black text-[var(--bp-accent-ink)]">Supervision</p><h1 className="mt-1 text-3xl font-black">Manage progress and restrictions</h1><p className="mt-2 text-sm text-[var(--bp-muted)]">Study progress and approved device restrictions stay private and consent-based.</p></header>{error&&<p role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-600">{error}</p>}
 {!selected?<section className="grid gap-3 sm:grid-cols-2">{rels.filter(r=>r.status==='active'&&r.currentRole==='guardian').map(r=><button key={r.id} onClick={()=>setSelected(r)} className="flex items-center gap-3 rounded-2xl border border-[var(--bp-border)] bg-[var(--bp-surface)] p-4 text-start hover:border-[var(--bp-accent)]"><Avatar person={r.supervisedUser}/><span><b>{identityLabel(r.supervisedUser)}</b><small className="mt-1 block text-[var(--bp-muted)]">{label(r.permissions.level)} · Open dashboard</small></span></button>)}{!rels.length&&<SectionCard><p className="font-bold">No supervised people yet</p><p className="text-sm text-[var(--bp-muted)]">Accepted supervision relationships will appear here.</p></SectionCard>}</section>:<><SecondaryButton onClick={()=>setSelected(null)}>← People</SecondaryButton><SectionCard><div className="flex items-center gap-3"><Avatar person={selected.supervisedUser}/><div className="min-w-0"><h2 className="text-xl font-black">{identityLabel(selected.supervisedUser)}</h2><p className="text-sm text-[var(--bp-muted)]">{selected.supervisedUser.username?`@${selected.supervisedUser.username} · `:''}{label(selected.permissions.level)} · Active</p></div></div></SectionCard>
 <section><div className="mb-3 flex items-center justify-between"><div><h2 className="text-xl font-black">Active Restrictions</h2><p className="text-sm text-[var(--bp-muted)]">Current Guardian-created study rules.</p></div></div>{rules.length?<div className="grid gap-3 md:grid-cols-2">{rules.map(r=>{const picked=apps.filter(a=>(r.appSelection?.managedAppIds??[]).includes(a.id));return <SectionCard key={r.id}><div className="flex items-start justify-between gap-3"><h3 className="font-black">{r.name}</h3><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-black text-emerald-600">{label(r.status)}</span></div><p className="mt-4 text-xs font-black uppercase tracking-wide text-[var(--bp-muted)]">Restricted apps</p><div className="mt-2 space-y-2">{picked.map(a=><div key={a.id} className="flex items-center gap-2"><AppIcon app={a} size="sm"/><span className="text-sm font-bold">{a.displayName}</span></div>)||<p className="text-sm text-[var(--bp-muted)]">Approved apps are unavailable.</p>}</div><dl className="mt-4 space-y-2 text-sm"><div><dt className="text-[var(--bp-muted)]">Ends when</dt><dd className="font-semibold">{label(r.restrictionMode)}{r.endsAt?' · '+new Date(r.endsAt).toLocaleString():''}</dd></div><div><dt className="text-[var(--bp-muted)]">Enforcement</dt><dd className="font-semibold">Accountability only</dd></div></dl></SectionCard>})}</div>:<SectionCard><p className="font-bold">No restrictions are currently active.</p></SectionCard>}</section>
 {selected.permissions.level==='device_restrictions'&&<div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]"><SectionCard><h2 className="text-xl font-black">Create Restriction</h2><p className="mt-1 text-sm text-[var(--bp-muted)]">Choose approved apps and when the restriction should end.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['Restriction','name'],['Release condition','restrictionMode'],['Task','taskId'],['Maximum duration','duration']].map(([title,key])=><label key={key} className={`${key==='taskId'&&form.restrictionMode==='time'?'hidden':''} block text-xs font-black`}>{title}{key==='name'?<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-[var(--bp-border)] bg-[var(--bp-input)] px-3 py-2 text-sm"/>:<select value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-[var(--bp-border)] bg-[var(--bp-input)] px-3 py-2 text-sm">{key==='restrictionMode'?<><option value="time">Until time</option><option value="task">Until task completed</option><option value="task_or_time">Task or time</option></>:key==='taskId'?<><option value="">Select supervised task</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title} ({t.progress}%)</option>)}</>:['15','30','60','120'].map(v=><option key={v} value={v}>{v} minutes</option>)}</select>}</label>)}</div><p className="mt-5 text-sm font-black">Approved apps</p><div className="mt-2 grid gap-3 sm:grid-cols-2">{apps.map(a=><AppRow key={a.id} app={a} selected={form.managedAppIds.includes(a.id)} onClick={()=>setForm(f=>({...f,managedAppIds:f.managedAppIds.includes(a.id)?f.managedAppIds.filter(id=>id!==a.id):[...f.managedAppIds,a.id]}))}/>)}</div><PrimaryButton className="mt-5" loading={creating} disabled={creating||!canCreateRestriction(form.restrictionMode,form.taskId,form.managedAppIds)} onClick={create}>{creating?'Creating restriction…':'Create Restriction'}</PrimaryButton></SectionCard><SectionCard><h2 className="text-lg font-black">Activity</h2><div className="mt-4 space-y-4">{audit.slice(0,6).map(a=><div key={a.id} className="border-s border-[var(--bp-border)] ps-3"><p className="text-sm font-bold">{auditLabel[a.event]??label(a.event)}</p><p className="mt-1 text-xs text-[var(--bp-muted)]">{new Date(a.createdAt).toLocaleString()}</p></div>)||<p className="text-sm text-[var(--bp-muted)]">No activity yet.</p>}</div></SectionCard></div>}</>}</main></AppLayout>}
