import { useEffect, useState, type InputHTMLAttributes } from 'react'
import { ConfirmDestructiveModal } from '../../components/ConfirmDestructiveModal'
import { DangerButton, PrimaryButton, SecondaryButton, SectionCard } from '../../components/layout'
import type { AuthUser } from '../../lib/api'
import { getPlannerPreferences, updatePlannerPreferences, type PlannerPreferences } from '../../lib/plannerApi'
import { changePassword, deleteAccount, updateProfile } from './settings.api'
import { validatePassword } from './settingsValidation'

const fieldClass = 'w-full rounded-lg border border-[var(--bp-border)] bg-[var(--bp-surface)] px-3 py-2 text-sm text-[var(--bp-text)] outline-none focus:border-[var(--bp-accent)]'
function Field({ label, ...props }: { label: string } & InputHTMLAttributes<HTMLInputElement>) { return <label className="space-y-1"><span className="text-xs font-bold text-[var(--bp-muted)]">{label}</span><input className={fieldClass} {...props} /></label> }
function Status({ value }: { value: { ok: boolean; text: string } | null }) { return value ? <p role="status" className={`mt-3 text-xs font-bold ${value.ok ? 'text-emerald-400' : 'text-red-400'}`}>{value.text}</p> : null }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between border-b border-[var(--bp-border)]/60 py-3 last:border-0"><span className="text-sm font-bold text-[var(--bp-text)]">{label}</span><button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} className={`relative h-6 w-11 rounded-full ${checked ? 'bg-[var(--bp-accent)]' : 'bg-[var(--bp-border)]'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-all ${checked ? 'left-6' : 'left-1'}`} /></button></div> }

export function AccountSettings({ user, token, onUpdated }: { user: AuthUser | null; token?: string; onUpdated: (user: AuthUser) => void }) {
  const [profile, setProfile] = useState({ fullName: user?.fullName ?? '', email: user?.email ?? '', avatarUrl: user?.avatarUrl ?? '' })
  const [password, setPassword] = useState({ current: '', next: '', confirm: '' })
  const [profileStatus, setProfileStatus] = useState<{ ok: boolean; text: string } | null>(null); const [passwordStatus, setPasswordStatus] = useState<{ ok: boolean; text: string } | null>(null)
  const [saving, setSaving] = useState(false); const [changing, setChanging] = useState(false)
  useEffect(() => setProfile({ fullName: user?.fullName ?? '', email: user?.email ?? '', avatarUrl: user?.avatarUrl ?? '' }), [user])
  async function saveProfile() {
    if (!token || !profile.fullName.trim() || !/^\S+@\S+\.\S+$/.test(profile.email)) return setProfileStatus({ ok: false, text: 'Enter a full name and valid email.' })
    setSaving(true); try { const updated = await updateProfile(token, { ...profile, avatarUrl: profile.avatarUrl || null, timezone: user?.timezone ?? 'UTC' }); onUpdated(updated); setProfileStatus({ ok: true, text: 'Profile changes saved.' }) } catch (error) { setProfileStatus({ ok: false, text: error instanceof Error ? error.message : 'Unable to save profile.' }) } finally { setSaving(false) }
  }
  async function savePassword() {
    const error = validatePassword(password.next)
    if (!password.current || error || password.next !== password.confirm) return setPasswordStatus({ ok: false, text: !password.current ? 'Current password is required.' : error || 'New passwords do not match.' })
    if (!token) return
    setChanging(true); try { await changePassword(token, password.current, password.next); setPassword({ current: '', next: '', confirm: '' }); setPasswordStatus({ ok: true, text: 'Password changed successfully.' }) } catch (cause) { setPasswordStatus({ ok: false, text: cause instanceof Error ? cause.message : 'Unable to change password.' }) } finally { setChanging(false) }
  }
  const social = user?.authProvider !== 'password'
  return <SectionCard><h3 className="text-sm font-black text-[var(--bp-text)]">Account</h3><p className="mb-4 text-xs text-[var(--bp-muted)]">Manage your profile and sign-in security.</p>
    <div className="mb-4 flex items-center gap-4">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="Profile" className="h-16 w-16 rounded-full object-cover" /> : <div className="flex h-16 w-16 items-center justify-center rounded-full bg-[var(--bp-accent)]/20 text-xl font-black text-[var(--bp-accent)]">{(profile.fullName[0] ?? '?').toUpperCase()}</div>}<div className="flex-1"><Field label="Profile photo URL" type="url" value={profile.avatarUrl} onChange={(e) => setProfile({ ...profile, avatarUrl: e.target.value })} /></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Full Name" value={profile.fullName} onChange={(e) => setProfile({ ...profile, fullName: e.target.value })} /><Field label="Email Address" type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} /><Field label="Username" value="Not currently supported" disabled /></div><PrimaryButton className="mt-4" loading={saving} onClick={saveProfile}>Save Changes</PrimaryButton><Status value={profileStatus} />
    <div className="my-6 border-t border-[var(--bp-border)]" /><h4 className="text-sm font-black text-[var(--bp-text)]">Security</h4><p className="mb-3 text-xs text-[var(--bp-muted)]">{social ? 'Password is managed by your social sign-in provider.' : 'Use at least 8 characters with uppercase, lowercase, number, and symbol.'}</p><div className="grid gap-3 sm:grid-cols-3"><Field label="Current Password" type="password" autoComplete="current-password" disabled={social} value={password.current} onChange={(e) => setPassword({ ...password, current: e.target.value })} /><Field label="New Password" type="password" autoComplete="new-password" disabled={social} value={password.next} onChange={(e) => setPassword({ ...password, next: e.target.value })} /><Field label="Confirm New Password" type="password" autoComplete="new-password" disabled={social} value={password.confirm} onChange={(e) => setPassword({ ...password, confirm: e.target.value })} /></div><PrimaryButton className="mt-4" disabled={social} loading={changing} onClick={savePassword}>Change Password</PrimaryButton><Status value={passwordStatus} /></SectionCard>
}

export function AiSettings({ token, onOpen }: { token?: string; onOpen?: () => void }) {
  const [prefs, setPrefs] = useState<PlannerPreferences | null>(null); const [status, setStatus] = useState<{ ok: boolean; text: string } | null>(null); const [saving, setSaving] = useState(false)
  useEffect(() => { if (token) getPlannerPreferences(token).then(setPrefs).catch(() => setStatus({ ok: false, text: 'Unable to load planner preferences.' })) }, [token])
  const number = (key: 'workBlockMinutes' | 'breakMinutes' | 'bufferMinutes', value: string) => setPrefs((current) => current ? { ...current, [key]: Number(value) } : current)
  async function save() { if (!token || !prefs) return; setSaving(true); try { setPrefs(await updatePlannerPreferences(token, prefs)); setStatus({ ok: true, text: 'AI preferences saved.' }) } catch (error) { setStatus({ ok: false, text: error instanceof Error ? error.message : 'Unable to save preferences.' }) } finally { setSaving(false) } }
  return <SectionCard><div className="flex justify-between gap-3"><div><h3 className="text-sm font-black text-[var(--bp-text)]">AI Preferences</h3><p className="text-xs text-[var(--bp-muted)]">Tune how BeePlan builds your day.</p></div><SecondaryButton size="sm" onClick={onOpen}>Open AI Planner</SecondaryButton></div>{prefs ? <><div className="mt-4 grid gap-3 sm:grid-cols-3"><Field label="Focus session (min)" type="number" min="15" max="240" value={prefs.workBlockMinutes} onChange={(e) => number('workBlockMinutes', e.target.value)} /><Field label="Short break (min)" type="number" min="0" max="60" value={prefs.breakMinutes} onChange={(e) => number('breakMinutes', e.target.value)} /><Field label="Session buffer (min)" type="number" min="0" max="60" value={prefs.bufferMinutes} onChange={(e) => number('bufferMinutes', e.target.value)} /></div><div className="mt-3 grid gap-3 sm:grid-cols-3">{(['morning','afternoon','evening'] as const).map((period) => <label key={period} className="space-y-1"><span className="text-xs font-bold capitalize text-[var(--bp-muted)]">{period} productivity</span><select className={fieldClass} value={prefs.energy[period]} onChange={(e) => setPrefs({ ...prefs, energy: { ...prefs.energy, [period]: e.target.value as 'high'|'medium'|'low' } })}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label>)}</div><label className="mt-3 block space-y-1"><span className="text-xs font-bold text-[var(--bp-muted)]">Planning style</span><select className={fieldClass} value={prefs.groupSimilarTasks ? 'batch' : 'balanced'} onChange={(e) => setPrefs({ ...prefs, groupSimilarTasks: e.target.value === 'batch' })}><option value="balanced">Balanced</option><option value="batch">Batch similar tasks</option></select></label><p className="mt-3 text-xs text-[var(--bp-muted)]">Long-break support is reserved for a future planner API update.</p><PrimaryButton className="mt-4" loading={saving} onClick={save}>Save AI Preferences</PrimaryButton></> : <p className="mt-4 text-xs text-[var(--bp-muted)]">Loading preferences…</p>}<Status value={status} /></SectionCard>
}

type LocalPrefs = Record<'taskReminders'|'collaboration'|'focus'|'location'|'push'|'email', boolean> & { timeFormat: string; dateFormat: string }
const defaults: LocalPrefs = { taskReminders: true, collaboration: true, focus: true, location: true, push: true, email: false, timeFormat: '12', dateFormat: 'MM/DD/YYYY' }
function loadLocalPrefs(): LocalPrefs {
  try {
    const stored = JSON.parse(localStorage.getItem('beeplan_settings_preferences') ?? '{}') as Partial<LocalPrefs>
    return Object.fromEntries(Object.keys(defaults).map((key) => [key, stored[key as keyof LocalPrefs] ?? defaults[key as keyof LocalPrefs]])) as LocalPrefs
  } catch {
    return defaults
  }
}
export function GeneralSettings({ mode, language, timezone, token, onTheme, onLanguage, onNotifications, onDeleted }: { mode: string; language: string; timezone: string; token?: string; onTheme: () => void; onLanguage: () => void; onNotifications?: () => void; onDeleted: () => void }) {
  const [prefs, setPrefs] = useState<LocalPrefs>(loadLocalPrefs); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false)
  function patch(key: keyof LocalPrefs, value: string | boolean) { const next = { ...prefs, [key]: value }; setPrefs(next); localStorage.setItem('beeplan_settings_preferences', JSON.stringify(next)) }
  async function remove() { if (!token) return; setDeleting(true); try { await deleteAccount(token); onDeleted() } finally { setDeleting(false) } }
  return <><SectionCard><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-black text-[var(--bp-text)]">Notifications</h3><SecondaryButton size="sm" onClick={onNotifications}>Open notification center</SecondaryButton></div>{([['taskReminders','Task reminders'],['collaboration','Collaboration notifications'],['focus','Focus notifications'],['location','Location reminders'],['push','Push notifications'],['email','Email notifications']] as const).map(([key,label]) => <Toggle key={key} label={label} checked={prefs[key]} onChange={(value) => patch(key,value)} />)}</SectionCard>
    <SectionCard><h3 className="mb-4 text-sm font-black text-[var(--bp-text)]">Appearance</h3><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1"><span className="text-xs font-bold text-[var(--bp-muted)]">Theme</span><select className={fieldClass} value={mode} onChange={onTheme}><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="space-y-1"><span className="text-xs font-bold text-[var(--bp-muted)]">Language</span><select className={fieldClass} value={language} onChange={onLanguage}><option value="en">English</option><option value="ar">العربية</option></select></label><label className="space-y-1"><span className="text-xs font-bold text-[var(--bp-muted)]">Time format</span><select className={fieldClass} value={prefs.timeFormat} onChange={(e) => patch('timeFormat',e.target.value)}><option value="12">12-hour</option><option value="24">24-hour</option></select></label><label className="space-y-1"><span className="text-xs font-bold text-[var(--bp-muted)]">Date format</span><select className={fieldClass} value={prefs.dateFormat} onChange={(e) => patch('dateFormat',e.target.value)}><option>MM/DD/YYYY</option><option>DD/MM/YYYY</option><option>YYYY-MM-DD</option></select></label><Field label="Timezone" value={timezone} disabled /></div></SectionCard>
    <SectionCard><h3 className="text-sm font-black text-[var(--bp-text)]">Privacy</h3><Toggle label="Location Services" checked={prefs.location} onChange={(value) => patch('location',value)} /><div className="mt-1 flex flex-wrap gap-3 border-t border-[var(--bp-border)] pt-4"><SecondaryButton disabled title="Data export API is not available">Export data (coming soon)</SecondaryButton><DangerButton onClick={() => setConfirm(true)}>Delete account</DangerButton></div></SectionCard><ConfirmDestructiveModal open={confirm} title="Delete account?" message="This permanently deletes your account and all associated data. This cannot be undone." confirmLabel="Delete account" isConfirming={deleting} onCancel={() => setConfirm(false)} onConfirm={remove} /></>
}
