import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowBigUp, Lightbulb, Plus } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppLayout, type SidebarNavHandlers } from '../../components/layout'
import { Modal } from '../../components/layout/Modal'
import { feedbackApi, type FeedbackItem } from './feedback.api'
import { useLanguage } from '../../i18n/LanguageContext'

export function FeedbackScreen({ accessToken, ...nav }: SidebarNavHandlers & { accessToken: string }) {
  const navigate = useNavigate(); const { t } = useLanguage(); const [sort, setSort] = useState('most_voted'); const [open, setOpen] = useState(false); const client = useQueryClient()
  const query = useQuery({ queryKey: ['feedback', sort], queryFn: () => feedbackApi.list(accessToken, new URLSearchParams({ sort })) })
  const vote = useMutation({ mutationFn: (item: FeedbackItem) => feedbackApi.vote(accessToken, item.id, item.voted), onSuccess: () => void client.invalidateQueries({ queryKey: ['feedback'] }) })
  return <AppLayout active="feedback" {...nav}><main className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">{t('feedback.title')}</h1><p className="mt-1 text-sm text-[var(--bp-muted)]">{t('feedback.subtitle')}</p></div><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-[var(--bp-accent)] px-4 py-2.5 text-sm font-bold text-[var(--bp-accent-text)]"><Plus className="h-4 w-4" />{t('feedback.share')}</button></div><div className="mt-6 flex justify-end"><select aria-label={t('feedback.sortLabel')} value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-[var(--bp-border)] bg-[var(--bp-surface)] px-3 py-2 text-sm"><option value="most_voted">{t('feedback.sort.most_voted')}</option><option value="newest">{t('feedback.sort.newest')}</option><option value="recently_updated">{t('feedback.sort.recently_updated')}</option></select></div><section className="mt-4 space-y-3">{query.isLoading ? <p className="text-sm text-[var(--bp-muted)]">Loading feedback…</p> : query.data?.items.length ? query.data.items.map((item) => <article key={item.id} className="flex gap-4 rounded-xl border border-[var(--bp-border)] bg-[var(--bp-surface)] p-4"><button disabled={vote.isPending} onClick={() => vote.mutate(item)} aria-label={`${item.voted ? 'Remove vote from' : 'Vote for'} ${item.title}`} className={`flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-lg text-sm font-bold ${item.voted ? 'bg-[var(--bp-accent)] text-[var(--bp-accent-text)]' : 'bg-[var(--bp-accent-soft)] text-[var(--bp-accent-ink)]'}`}><ArrowBigUp className="h-5 w-5" />{item.voteCount}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><button onClick={() => navigate(`/feedback/${item.id}`)} className="text-left font-semibold hover:underline">{item.title}</button><span className="rounded-full bg-[var(--bp-bg)] px-2 py-0.5 text-xs text-[var(--bp-muted)]">{t(`feedback.status.${item.status}`)}</span></div><p className="mt-2 line-clamp-2 text-sm text-[var(--bp-muted)]">{item.description}</p><p className="mt-2 text-xs text-[var(--bp-muted)]">{item.category} · {item.author.displayName} · {new Date(item.updatedAt).toLocaleDateString()}</p></div></article>) : <div className="rounded-xl border border-dashed border-[var(--bp-border)] p-8 text-center"><Lightbulb className="mx-auto h-7 w-7 text-[var(--bp-accent-ink)]" /><p className="mt-3 font-semibold">{t('feedback.emptyTitle')}</p><p className="mt-1 text-sm text-[var(--bp-muted)]">{t('feedback.emptyDescription')}</p></div>}</section><ShareModal open={open} onClose={() => setOpen(false)} onSubmit={(body) => feedbackApi.submit(accessToken, body).then(() => { setOpen(false); void client.invalidateQueries({ queryKey: ['feedback'] })} )} /></main></AppLayout>
}
function ShareModal({ open, onClose, onSubmit }: { open: boolean; onClose: () => void; onSubmit: (body: { category: string; title: string; description: string }) => Promise<unknown> }) { const { t } = useLanguage(); const [category, setCategory] = useState('idea'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const submit = async () => { setSaving(true); setError(''); try { await onSubmit({ category, title, description }); setTitle(''); setDescription('') } catch (reason) { setError(reason instanceof Error ? reason.message : t('feedback.error')) } finally { setSaving(false) } }; return <Modal open={open} title={t('feedback.share')} onClose={onClose} footer={<><button onClick={onClose} className="px-3 py-2 text-sm">{t('common.cancel')}</button><button disabled={saving || title.trim().length < 3 || description.trim().length < 10} onClick={() => void submit()} className="rounded-lg bg-[var(--bp-accent)] px-3 py-2 text-sm font-bold text-[var(--bp-accent-text)] disabled:opacity-50">{saving ? 'Submitting…' : 'Submit idea'}</button></>}><label className="mt-4 block text-sm font-semibold">{t('feedback.categoryLabel')}<select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 w-full rounded-lg border border-[var(--bp-border)] bg-[var(--bp-bg)] p-2"><option value="idea">{t('feedback.category.idea')}</option><option value="improvement">{t('feedback.category.improvement')}</option><option value="problem">{t('feedback.category.problem')}</option><option value="other">{t('feedback.category.other')}</option></select></label><label className="mt-4 block text-sm font-semibold">{t('feedback.titleField')}<input value={title} maxLength={160} onChange={(event) => setTitle(event.target.value)} className="mt-2 w-full rounded-lg border border-[var(--bp-border)] bg-[var(--bp-bg)] p-2" /></label><label className="mt-4 block text-sm font-semibold">{t('feedback.description')}<textarea value={description} maxLength={4000} onChange={(event) => setDescription(event.target.value)} className="mt-2 min-h-28 w-full rounded-lg border border-[var(--bp-border)] bg-[var(--bp-bg)] p-2" /></label>{error ? <p className="mt-3 text-sm text-red-600">{error}</p> : null}</Modal> }
