import { useCallback, useEffect, useState } from 'react'
import { getTaskAssistant, refreshTaskAssistant, updateTaskAssistantNotification, updateTaskAssistantSuggestion, type ApiTask, type TaskAssistantState } from '../lib/tasksApi'

const labelContext = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

export function TravelWeatherCard({ token, task }: { token: string; task: ApiTask }) {
  const [state, setState] = useState<TaskAssistantState | null>(null)
  const [loading, setLoading] = useState(false)
  const [expandedSuggestion, setExpandedSuggestion] = useState<string | null>(null)
  const [notificationsOpen, setNotificationsOpen] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { setState(await getTaskAssistant(token, task.id)) } finally { setLoading(false) } }, [task.id, token])
  useEffect(() => { void load() }, [load, task.updatedAt])
  const update = async (id: string, payload: { status?: string; quantity?: string }) => setState(await updateTaskAssistantSuggestion(token, task.id, id, payload))
  const weatherEvidence = state?.travelWeather?.recommendations?.weatherEvidence
  const recommendationTypes: string[] = state?.travelWeather?.recommendations?.recommendationTypes ?? []
  const weatherAdvice = recommendationTypes.filter((type) => ['hydration', 'uv_protection', 'umbrella', 'strong_wind'].includes(type)).map((type) => ({ hydration: 'Take water', uv_protection: 'Use sun protection', umbrella: 'Take an umbrella', strong_wind: 'Prepare for strong wind' } as Record<string, string>)[type]).filter(Boolean)

  return <section aria-label="Task Assistant" className="rounded-2xl border border-[var(--bp-border)] bg-[var(--bp-surface)] p-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-[var(--bp-text)]">Task Assistant</h3><p className="mt-1 text-xs text-[var(--bp-muted)]">{state ? labelContext(state.context.primaryContext) : 'Detecting task context…'}</p></div><button type="button" disabled={loading} onClick={() => void refreshTaskAssistant(token, task.id).then(setState)} className="text-sm font-bold text-[var(--bp-accent-ink)]">Refresh</button></div>
    {state ? <>
      {state.suggestions.length ? <section className="mt-4" aria-labelledby="task-assistant-prepare"><h4 id="task-assistant-prepare" className="mb-2 text-sm font-black text-[var(--bp-text)]">Prepare</h4><div className="divide-y divide-[var(--bp-border)]">{state.suggestions.map((item) => { const open = expandedSuggestion === item.id; return <div key={item.id} className="py-2"><div className="flex items-center gap-2"><input aria-label={`Complete ${item.title}`} type="checkbox" checked={item.status === 'completed'} onChange={(event) => void update(item.id, { status: event.target.checked ? 'completed' : 'pending' })} /><button type="button" onClick={() => setExpandedSuggestion(open ? null : item.id)} className="flex flex-1 items-center justify-between text-start"><span className="text-sm font-bold text-[var(--bp-text)]">{item.title}</span><span className="text-[var(--bp-muted)]">{open ? '⌃' : '›'}</span></button></div>{open ? <div className="ms-7 mt-2"><p className="text-xs text-[var(--bp-muted)]">{item.description}</p><p className="mt-1 text-xs text-[var(--bp-muted)]">Why: {item.reason}</p>{item.category ? <label className="mt-2 block text-xs font-bold text-[var(--bp-muted)]">Quantity or note<input aria-label={`Quantity for ${item.title}`} defaultValue={item.quantity ?? ''} onBlur={(event) => void update(item.id, { quantity: event.target.value })} className="ms-2 rounded-lg border border-[var(--bp-border)] bg-[var(--bp-input)] px-2 py-1 font-normal text-[var(--bp-text)]" /></label> : null}<button type="button" aria-label={`Dismiss ${item.title}`} onClick={() => void update(item.id, { status: 'dismissed' })} className="mt-2 text-xs font-bold text-[var(--bp-muted)]">Dismiss</button></div> : null}</div> })}</div></section> : null}
      {weatherEvidence ? <section className="mt-4" aria-labelledby="task-assistant-weather"><h4 id="task-assistant-weather" className="text-sm font-black text-[var(--bp-text)]">Weather</h4><p className="mt-1 text-sm font-bold text-[var(--bp-text)]">{Math.round(weatherEvidence.feelsLikeC ?? 0)}°C{weatherAdvice.length ? ` · ${weatherAdvice.join(' · ')}` : ''}</p></section> : null}
      {state.travelWeather?.eligibility?.eligible ? <section className="mt-4" aria-labelledby="task-assistant-travel"><h4 id="task-assistant-travel" className="text-sm font-black text-[var(--bp-text)]">Travel</h4>{state.travelWeather.route?.durationMinutes ? <p className="mt-1 text-sm font-bold text-[var(--bp-text)]">🚗 {state.travelWeather.route.durationMinutes} min{state.travelWeather.recommendedDepartureTime ? ` · leave by ${new Date(state.travelWeather.recommendedDepartureTime).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}` : ''}</p> : <><p className="mt-1 text-sm font-bold text-[var(--bp-text)]">Travel time unavailable</p>{state.travelWeather.routeUnavailableReason === 'origin_unavailable' ? <p className="mt-1 text-xs text-[var(--bp-muted)]">Set Home to calculate departure.</p> : null}</>}</section> : null}
      {state.timeline.length ? <section className="mt-4" aria-labelledby="task-assistant-timeline"><h4 id="task-assistant-timeline" className="text-sm font-black text-[var(--bp-text)]">Timeline</h4><ol className="mt-2 space-y-2">{state.timeline.map((stage) => <li key={stage.id} className="text-sm font-bold text-[var(--bp-text)]">{stage.scheduledAt ? new Date(stage.scheduledAt).toLocaleString([], { weekday: 'short', hour: 'numeric', minute: '2-digit' }) : 'Upcoming'} · {stage.title}</li>)}</ol></section> : null}
      {state.contextualNotifications.length ? <section className="mt-4" aria-labelledby="task-assistant-notifications"><button type="button" onClick={() => setNotificationsOpen((value) => !value)} className="flex w-full items-center justify-between text-start"><h4 id="task-assistant-notifications" className="text-sm font-black text-[var(--bp-text)]">Notifications</h4><span className="text-xs font-bold text-[var(--bp-muted)]">{state.contextualNotifications.length} scheduled {notificationsOpen ? '⌃' : '›'}</span></button>{notificationsOpen ? <ul className="mt-2 space-y-1 text-sm text-[var(--bp-muted)]">{state.contextualNotifications.map((notification) => <li key={notification.id} className="flex items-center justify-between gap-3"><span>{new Date(notification.scheduledAt).toLocaleString([], { weekday: 'short', hour: 'numeric', minute: '2-digit' })} · {notification.body}</span><button type="button" aria-label={`Disable ${notification.body}`} onClick={() => void updateTaskAssistantNotification(token, task.id, notification.id, { status: 'dismissed' }).then(setState)} className="text-xs font-bold">Disable</button></li>)}</ul> : null}</section> : null}
    </> : null}
  </section>
}
