import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Pressable, Text, TextInput, View } from 'react-native'
import { AppScreen, FilterTabs, PageHeader, PrimaryButton, SectionCard, SecondaryButton, StatsCard } from '../components/layout'
import { acceptDailyPlan, generateDailyPlan, getDailyPlanAcceptance, getPlannerPreferences, updatePlannerPreferences, type DailyPlan, type PlannerPreferences } from '../lib/plannerApi'
import { useTheme } from '../theme/useTheme'
import { BUFFER_MINUTES_RANGE, ENERGY_LEVELS, formatUnavailableHours, parseBufferMinutes, parseUnavailableHours, savePlannerPreferencesOptimistically, setEnergyPreference, validatePlannerPreferences, type EnergyPeriod } from './plannerPreferences'

type Tab = 'today' | 'progress' | 'timeline' | 'suggestions'
const tabs: { value: Tab; label: string }[] = [{ value: 'today', label: 'Today' }, { value: 'progress', label: 'Progress' }, { value: 'timeline', label: 'Timeline' }, { value: 'suggestions', label: 'Suggestions' }]

export default function AiDailyPlannerScreen({ accessToken, onBack }: { accessToken: string; onBack: () => void }) {
  const { theme } = useTheme(); const { colors } = theme; const queryClient = useQueryClient(); const [tab, setTab] = useState<Tab>('today'); const date = new Date().toISOString().slice(0, 10)
  const acceptance = useQuery({ queryKey: ['planner', 'acceptance', date], queryFn: () => getDailyPlanAcceptance(accessToken, date), enabled: Boolean(accessToken), staleTime: 30_000 })
  const preferences = useQuery({ queryKey: ['planner', 'preferences'], queryFn: () => getPlannerPreferences(accessToken), enabled: Boolean(accessToken), staleTime: 30_000 })
  const generate = useMutation({ mutationFn: () => generateDailyPlan(accessToken, date), onSuccess: (next) => queryClient.setQueryData(['planner', 'draft', date], next) })
  const accept = useMutation({ mutationFn: (next: DailyPlan) => acceptDailyPlan(accessToken, next), onSuccess: (saved) => queryClient.setQueryData(['planner', 'acceptance', date], saved) })
  const plan = acceptance.data?.plan; const draft = queryClient.getQueryData<DailyPlan>(['planner', 'draft', date]); const activePlan = plan ?? draft
  if (acceptance.isLoading || preferences.isLoading) return <AppScreen><PageHeader title="AI Daily Planner" onBack={onBack} /><Text style={{ color: colors.secondaryText }}>Loading your plan and preferences...</Text></AppScreen>
  if (acceptance.isError || preferences.isError) return <AppScreen><PageHeader title="AI Daily Planner" onBack={onBack} /><SectionCard><Text style={{ color: colors.error }}>Couldn't load your plan or preferences.</Text><SecondaryButton onPress={() => { void acceptance.refetch(); void preferences.refetch() }}>Retry</SecondaryButton></SectionCard></AppScreen>
  return <AppScreen><PageHeader title="AI Daily Planner" subtitle="Your smart plan for today" onBack={onBack} /><FilterTabs tabs={tabs} active={tab} onChange={setTab} />
    {preferences.data ? <Preferences preferences={preferences.data} onSave={async (next) => { const error = validatePlannerPreferences(next); if (error) throw new Error(error); const previous = preferences.data; await savePlannerPreferencesOptimistically(next, previous, (value) => updatePlannerPreferences(accessToken, value), { optimistic: (value) => queryClient.setQueryData(['planner', 'preferences'], value), persisted: (value) => queryClient.setQueryData(['planner', 'preferences'], value), rollback: (value) => queryClient.setQueryData(['planner', 'preferences'], value) }) }} /> : null}
    {!activePlan ? <SectionCard><Text className="mb-3" style={{ color: colors.secondaryText }}>No plan yet. Generate one from your tasks, reminders, and saved preferences.</Text>{generate.isError ? <Text style={{ color: colors.error }}>Couldn't generate a plan. Try again.</Text> : null}<PrimaryButton disabled={!preferences.data} loading={generate.isPending} onPress={() => void generate.mutate()}>Generate Smart Plan</PrimaryButton></SectionCard> : <><View className="mb-3 flex-row flex-wrap justify-between gap-y-2"><StatsCard icon="tasks" value={String(activePlan.capacity.scheduledTaskCount)} title="Scheduled" /><StatsCard icon="focus" value={`${activePlan.capacity.freeMinutes}m`} title="Free time" /></View>{tab === 'today' ? <Today plan={activePlan} /> : tab === 'progress' ? <Progress plan={activePlan} /> : tab === 'timeline' ? <Timeline plan={activePlan} /> : <Suggestions plan={activePlan} />}<View className="flex-row gap-2"><SecondaryButton className="flex-1" loading={generate.isPending} onPress={() => void generate.mutate()}>Regenerate</SecondaryButton><PrimaryButton className="flex-1" loading={accept.isPending} onPress={() => void accept.mutate(activePlan)}>{plan ? 'Accepted' : 'Accept Plan'}</PrimaryButton></View></>}</AppScreen>
}

function Today({ plan }: { plan: DailyPlan }) { const { theme } = useTheme(); return <SectionCard>{Object.entries(plan.sections).map(([section, items]) => <View key={section} className="mb-3"><Text className="text-xs font-black uppercase" style={{ color: theme.colors.accent }}>{section}</Text>{items.map((item) => <Text key={item.id} className="mt-1 text-sm" style={{ color: theme.colors.text }}>{item.startTime} - {item.title}</Text>)}</View>)}</SectionCard> }
function Progress({ plan }: { plan: DailyPlan }) { const { theme } = useTheme(); const value = Math.round(plan.capacity.scheduledMinutes / Math.max(1, plan.capacity.requestedMinutes) * 100); return <SectionCard><Text className="text-3xl font-black" style={{ color: theme.colors.text }}>{value}%</Text><Text style={{ color: theme.colors.secondaryText }}>{plan.capacity.scheduledMinutes} scheduled minutes</Text></SectionCard> }
function Timeline({ plan }: { plan: DailyPlan }) { const { theme } = useTheme(); return <SectionCard>{Object.values(plan.sections).flat().sort((a, b) => a.startTime.localeCompare(b.startTime)).map((item) => <Text key={item.id} className="mb-2" style={{ color: theme.colors.text }}>{item.startTime}-{item.endTime} - {item.title}</Text>)}</SectionCard> }
function Suggestions({ plan }: { plan: DailyPlan }) { const { theme } = useTheme(); return <SectionCard>{plan.unscheduled.map((item, i) => <View key={`${item.title}-${i}`} className="mb-2"><Text style={{ color: theme.colors.text }}>{item.title}</Text><Text style={{ color: theme.colors.secondaryText }}>{item.reason}</Text></View>)}</SectionCard> }

function Preferences({ preferences, onSave }: { preferences: PlannerPreferences; onSave: (next: PlannerPreferences) => Promise<void> }) {
  const { theme } = useTheme(); const { colors } = theme; const [draft, setDraft] = useState(preferences); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { setDraft(preferences) }, [preferences])
  const field = (label: string, value: string, change: (value: string) => void) => <View className="mb-2"><Text className="text-xs" style={{ color: colors.secondaryText }}>{label}</Text><TextInput value={value} onChangeText={change} className="rounded-lg border px-2 py-2" style={{ borderColor: colors.border, color: colors.text }} /></View>
  const numberField = (label: string, value: number, change: (value: string) => void) => <View className="mb-2"><Text className="text-xs" style={{ color: colors.secondaryText }}>{label}</Text><TextInput value={String(value)} onChangeText={change} keyboardType="number-pad" accessibilityLabel={label} className="rounded-lg border px-2 py-2" style={{ borderColor: colors.border, color: colors.text }} /></View>
  const save = async () => { setSaving(true); setMessage(''); try { await onSave(draft); setMessage('Preferences saved. The next generated plan uses them.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save preferences.') } finally { setSaving(false) } }
  const toggle = (key: 'scheduleHardTasksInFocus' | 'finishStartedFirst' | 'groupSimilarTasks' | 'bufferBeforeMeetings', label: string) => <Pressable key={key} onPress={() => setDraft({ ...draft, [key]: !draft[key] })} accessibilityRole="switch" accessibilityState={{ checked: draft[key] }} className="mb-1 flex-row justify-between rounded-lg p-2" style={{ backgroundColor: colors.background }}><Text style={{ color: colors.text }}>{label}</Text><Text style={{ color: colors.accent }}>{draft[key] ? 'On' : 'Off'}</Text></Pressable>
  const energy = (period: EnergyPeriod, label: string) => <View key={period} className="mb-2"><Text className="mb-1 text-xs" style={{ color: colors.secondaryText }}>{label}</Text><View className="flex-row gap-1">{ENERGY_LEVELS.map((level) => <Pressable key={level} onPress={() => setDraft(setEnergyPreference(draft, period, level))} accessibilityRole="button" accessibilityLabel={`${label} energy: ${level}`} accessibilityState={{ selected: draft.energy[period] === level }} className="rounded-lg px-2 py-1" style={{ backgroundColor: draft.energy[period] === level ? colors.accent : colors.background }}><Text className="text-xs" style={{ color: draft.energy[period] === level ? colors.background : colors.text }}>{level[0].toUpperCase() + level.slice(1)}</Text></Pressable>)}</View></View>
  return <SectionCard className="mb-3"><Text className="mb-2 font-black" style={{ color: colors.text }}>AI Planning Preferences</Text>{field('Focus hours (start)', draft.focusStartTime, (value) => setDraft({ ...draft, focusStartTime: value }))}{field('Focus hours (end)', draft.focusEndTime, (value) => setDraft({ ...draft, focusEndTime: value }))}{field('Work block / break minutes', `${draft.workBlockMinutes}/${draft.breakMinutes}`, (value) => { const [work, rest] = value.split('/').map(Number); setDraft({ ...draft, workBlockMinutes: work || 0, breakMinutes: rest || 0 }) })}<Text className="mb-1 mt-1 text-xs font-black" style={{ color: colors.text }}>Energy pattern</Text>{energy('morning', 'Morning')}{energy('afternoon', 'Afternoon')}{energy('evening', 'Evening')}{energy('night', 'Night')}{toggle('scheduleHardTasksInFocus', 'Schedule difficult tasks in focus hours')}{toggle('finishStartedFirst', 'Finish started tasks first')}{toggle('groupSimilarTasks', 'Group similar tasks')}{toggle('bufferBeforeMeetings', 'Buffer before reminders/meetings')}{draft.bufferBeforeMeetings ? numberField(`Buffer before meetings (${BUFFER_MINUTES_RANGE.min}-${BUFFER_MINUTES_RANGE.max} min)`, draft.bufferMinutes, (value) => setDraft({ ...draft, bufferMinutes: parseBufferMinutes(value) })) : null}{field('Capacity: max work / emergency buffer', `${draft.maxDailyWorkMinutes}/${draft.emergencyBufferMinutes}`, (value) => { const [max, emergency] = value.split('/').map(Number); setDraft({ ...draft, maxDailyWorkMinutes: max || 0, emergencyBufferMinutes: emergency || 0 }) })}{field('Sleep (start/end)', `${draft.sleep.start}/${draft.sleep.end}`, (value) => { const [start, end] = value.split('/'); setDraft({ ...draft, sleep: { start: start || '', end: end || '' } }) })}{field('Lunch (start/end)', `${draft.lunch.start}/${draft.lunch.end}`, (value) => { const [start, end] = value.split('/'); setDraft({ ...draft, lunch: { start: start || '', end: end || '' } }) })}{field('Unavailable windows', formatUnavailableHours(draft.unavailableHours), (value) => setDraft({ ...draft, unavailableHours: parseUnavailableHours(value) }))}<TextInput value={draft.note} onChangeText={(note) => setDraft({ ...draft, note })} multiline maxLength={1000} placeholder="Personal planning note" placeholderTextColor={colors.placeholder} className="mb-2 rounded-lg border px-2 py-2" style={{ borderColor: colors.border, color: colors.text }} />{message ? <Text className="mb-2" style={{ color: message.includes('saved') ? colors.success : colors.error }}>{message}</Text> : null}<PrimaryButton size="sm" loading={saving} onPress={() => void save()}>Save Preferences</PrimaryButton></SectionCard>
}
