import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { useAuth } from '../hooks/useAuth';
import { useTheme } from '../theme/useTheme';
import { useLanguage } from '../i18n/LanguageContext';
import { challengesApi, type Challenge } from '../features/challenges/challengesApi';

export const challengeUnit = (c: Challenge, t: (k: string) => string) => c.type === 'focus_minutes' ? t('challenges.minutes') : c.type === 'focus_sessions' ? t('challenges.sessions') : t('challenges.tasks');
export const challengePercent = (c: Challenge) => Math.min(100, Math.max(0, c.progressValue / c.targetValue * 100));

export default function ChallengesScreen({ navigation }: any) {
  const { accessToken } = useAuth(); const { theme } = useTheme(); const { t, isRTL } = useLanguage();
  const q = useQuery({ queryKey: ['challenges'], queryFn: () => challengesApi.list(accessToken!), enabled: !!accessToken });
  const filters = [{ key: 'active', label: t('challenges.active') }, { key: 'scheduled', label: t('challenges.upcoming') }, { key: 'completed', label: t('challenges.completed') }] as const;
  if (q.isLoading) return <View style={{ flex: 1, backgroundColor: theme.colors.background, alignItems: 'center', justifyContent: 'center' }}><ActivityIndicator color={theme.colors.primary} /><Text style={{ color: theme.colors.secondaryText, marginTop: 12 }}>{t('challenges.loading')}</Text></View>;
  if (q.isError) return <View style={{ flex: 1, backgroundColor: theme.colors.background, alignItems: 'center', justifyContent: 'center', padding: 24 }}><Text style={{ color: theme.colors.text, fontSize: 18, fontWeight: '800', textAlign: 'center' }}>{t('challenges.error')}</Text><Pressable onPress={() => void q.refetch()} style={{ marginTop: 16, backgroundColor: theme.colors.accent, borderRadius: 12, paddingHorizontal: 20, paddingVertical: 12 }}><Text style={{ color: '#111827', fontWeight: '800' }}>{t('challenges.retry')}</Text></Pressable></View>;
  return <ScrollView style={{ backgroundColor: theme.colors.background }} contentContainerStyle={{ padding: 20, paddingTop: 28, paddingBottom: 40 }}><View style={{ alignItems: isRTL ? 'flex-end' : 'flex-start' }}><Text style={{ color: theme.colors.text, fontSize: 30, fontWeight: '900' }}>{t('challenges.title')}</Text><Text style={{ color: theme.colors.secondaryText, fontSize: 14, marginTop: 6, textAlign: isRTL ? 'right' : 'left' }}>{t('challenges.subtitle')}</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingVertical: 20 }}>{filters.map(filter => <View key={filter.key} style={{ borderRadius: 999, backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border, padding: 2 }}><Text style={{ color: theme.colors.text, fontWeight: '800', paddingHorizontal: 16, paddingVertical: 9 }}>{filter.label}</Text></View>)}</ScrollView>{filters.map(filter => { const challenges = (q.data ?? []).filter(c => c.status === filter.key); return <View key={filter.key} style={{ marginBottom: 20 }}><Text style={{ color: theme.colors.text, fontSize: 18, fontWeight: '900', marginBottom: 10 }}>{filter.label}</Text>{challenges.length ? challenges.map(c => <ChallengeCard key={c.id} c={c} theme={theme} t={t} isRTL={isRTL} onPress={() => navigation.navigate('ChallengeDetail', { challengeId: c.id })} />) : <View style={{ backgroundColor: theme.colors.surface, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.border, padding: 18 }}><Text style={{ color: theme.colors.secondaryText, textAlign: isRTL ? 'right' : 'left' }}>{filter.key === 'active' ? t('challenges.noActive') : filter.key === 'scheduled' ? t('challenges.noUpcoming') : t('challenges.noCompleted')}</Text></View>}</View>; })}</ScrollView>;
}

export function ChallengeCard({ c, theme, t, isRTL = false, onPress }: { c: Challenge; theme: any; t: (k: string) => string; isRTL?: boolean; onPress: () => void }) { const value = Math.min(c.progressValue, c.targetValue); const pct = challengePercent(c); const complete = pct >= 100 || c.status === 'completed'; return <Pressable onPress={onPress} style={{ backgroundColor: theme.colors.surface, borderRadius: 18, borderWidth: 1, borderColor: complete ? theme.colors.success : theme.colors.border, padding: 16, marginBottom: 10 }}><View style={{ flexDirection: isRTL ? 'row-reverse' : 'row', justifyContent: 'space-between', alignItems: 'flex-start' }}><Text style={{ color: theme.colors.text, fontSize: 17, fontWeight: '900', flex: 1, textAlign: isRTL ? 'right' : 'left' }}>{c.title}</Text><Text style={{ color: complete ? theme.colors.success : theme.colors.primary, fontSize: 12, fontWeight: '800', marginStart: 10 }}>{complete ? t('challenges.completed') : c.status === 'scheduled' ? t('challenges.upcoming') : t('challenges.active')}</Text></View>{c.description ? <Text style={{ color: theme.colors.secondaryText, marginTop: 7, textAlign: isRTL ? 'right' : 'left' }}>{c.description}</Text> : null}<Text style={{ color: theme.colors.secondaryText, fontSize: 13, marginTop: 14, textAlign: isRTL ? 'right' : 'left' }}>{value} / {c.targetValue} {challengeUnit(c, t)}</Text><View style={{ height: 9, width: '100%', backgroundColor: theme.colors.border, borderRadius: 99, overflow: 'hidden', marginTop: 8 }}><View style={{ height: 9, width: `${pct}%`, backgroundColor: complete ? theme.colors.success : theme.colors.accent, borderRadius: 99 }} /></View><Text style={{ color: complete ? theme.colors.success : theme.colors.secondaryText, fontWeight: '800', marginTop: 10, textAlign: isRTL ? 'right' : 'left' }}>{c.status === 'scheduled' ? t('challenges.startsIn') : c.completed ? t('challenges.completedByYou') : c.status === 'completed' ? t('challenges.ended') : t('challenges.remaining')}</Text></Pressable>; }
