import { useEffect, useMemo, useRef, useState } from 'react'
import { AccessibilityInfo, Animated, Easing, Pressable, Text, TextInput, View, useWindowDimensions } from 'react-native'
import Svg, { Circle, Path } from 'react-native-svg'
import { ArrowLeft, Check, Dices, Search, Target } from 'lucide-react-native'
import { AppScreen, SectionCard } from '../components/layout'
import { useTheme } from '../theme/useTheme'
import { useLanguage } from '../i18n/LanguageContext'
import { getRandomStart, type RandomStartItem } from '../lib/tasksApi'
import { buildWheel, EMPTY_FILTERS, isRtlLabel, pickRandom, type WheelFilters, type WheelMode } from '../features/randomStart/randomStartLogic'

function point(c: number, r: number, d: number) { const a = d * Math.PI / 180; return { x: c + r * Math.sin(a), y: c - r * Math.cos(a) } }
function path(size: number, start: number, end: number) { const c = size / 2, r = c - 4, a = point(c,r,start), b = point(c,r,end); return `M ${c} ${c} L ${a.x} ${a.y} A ${r} ${r} 0 ${end-start>180?1:0} 1 ${b.x} ${b.y} Z` }
function Wheel({ items, rotation, size, colors }: { items: RandomStartItem[]; rotation: Animated.Value; size: number; colors: any }) { const c=size/2,r=c-4,slice=items.length?360/items.length:360; return <View accessibilityRole="image" accessibilityLabel={`Random task wheel with ${items.length} tasks`} style={{ width:size,height:size }}><Text className="absolute -top-5 left-0 right-0 z-10 text-center text-4xl" style={{ color:colors.text }}>▼</Text><Animated.View style={{ width:size,height:size,transform:[{rotate:rotation.interpolate({inputRange:[0,360],outputRange:['0deg','360deg']})}] }}><Svg width={size} height={size}>{items.map((x,i)=><Path key={x.candidateKey} d={items.length===1?`M ${c} ${c} m -${r},0 a ${r},${r} 0 1,0 ${r*2},0 a ${r},${r} 0 1,0 -${r*2},0`:path(size,i*slice,(i+1)*slice)} fill={[colors.accentSoft,colors.surface,colors.card,'#fffbed'][i%4]} stroke={colors.accent}/>) }<Circle cx={c} cy={c} r={r*.22} fill={colors.accent}/></Svg>{items.map((x,i)=>{const p=point(c,r*.61,i*slice+slice/2),w=Math.min(92,size*.28);return <View key={`${x.candidateKey}-label`} style={{position:'absolute',left:p.x-w/2,top:p.y-22,width:w,height:44,justifyContent:'center'}}><Text numberOfLines={2} style={{color:colors.text,fontSize:items.length>8?10:12,fontWeight:'700',textAlign:'center',writingDirection:isRtlLabel(x.title)?'rtl':'ltr'}}>{x.title}</Text></View>})}<View className="absolute items-center justify-center" style={{left:c-r*.2,top:c-r*.2,width:r*.4,height:r*.4}}><Text className="text-2xl">🐝</Text></View></Animated.View></View> }

function DependencyInfo({ task, ar, colors, result = false }: { task: RandomStartItem; ar: boolean; colors: any; result?: boolean }) {
  const count = task.incompleteDependencyCount ?? 0
  if (!count) return null
  const titles = task.dependencyTitles?.join('، ')
  const text = ar ? (titles ? `تعتمد على: ${titles}` : `${count} تبعية غير مكتملة`) : (titles ? `Depends on: ${titles}` : `${count} incomplete ${count === 1 ? 'dependency' : 'dependencies'}`)
  return <View className={result ? 'mt-3 rounded-xl p-3' : 'mt-1'} style={result ? { backgroundColor: colors.surface } : undefined}><Text className={result ? 'text-sm' : 'text-xs'} style={{ color: colors.secondaryText }}>⚠ {text}</Text>{result ? <Text className="mt-1 text-xs" style={{ color: colors.secondaryText }}>{ar ? 'ما زال بإمكانك اختيار ما تريد فعله.' : 'You can still choose what you want to do.'}</Text> : null}</View>
}

export default function RandomStartScreen({ accessToken, onBack, onViewTask, onStartFocus }: { accessToken:string; onBack:()=>void; onViewTask:(id:string)=>void; onStartFocus:(task:RandomStartItem)=>Promise<void> }) {
  const { colors }=useTheme().theme; const { language, formatNumber }=useLanguage(); const { width }=useWindowDimensions(); const size=Math.min(340,Math.max(240,width-48)); const ar=language==='ar'
  const [all,setAll]=useState<RandomStartItem[]>([]),[mode,setMode]=useState<WheelMode>('all'),[selected,setSelected]=useState(new Set<string>()),[excluded,setExcluded]=useState(new Set<string>()),[filters,setFilters]=useState<WheelFilters>(EMPTY_FILTERS),[weighted,setWeighted]=useState(false),[query,setQuery]=useState(''),[result,setResult]=useState<RandomStartItem|null>(null),[shown,setShown]=useState<RandomStartItem[]>([]),[spinning,setSpinning]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''); const rotation=useRef(new Animated.Value(0)).current,rotationRef=useRef(0)
  useEffect(()=>{let live=true;getRandomStart(accessToken).then(r=>{if(live){setAll(r.candidates);setSelected(new Set(r.candidates.map(x=>x.candidateKey)));setShown(r.candidates.slice(0,12))}}).catch(e=>live&&setError(e instanceof Error?e.message:'Unable to load tasks.')).finally(()=>live&&setLoading(false));return()=>{live=false}},[accessToken])
  const eligible=useMemo(()=>buildWheel(all,mode,selected,filters,excluded),[all,mode,selected,filters,excluded]); useEffect(()=>{if(!spinning&&eligible.length===1){setResult(eligible[0]);setShown(eligible)}},[eligible,spinning]); const visible=useMemo(()=>all.filter(x=>x.title.toLowerCase().includes(query.toLowerCase())),[all,query]); const toggleFilter=(g:keyof WheelFilters,v:string)=>setFilters(f=>({...f,[g]:f[g].includes(v)?f[g].filter(x=>x!==v):[...f[g],v]}))
  async function spin(remove?:RandomStartItem){if(spinning)return;const ex=remove?new Set([...excluded,remove.candidateKey]):excluded;if(remove)setExcluded(ex);const pool=buildWheel(all,mode,selected,filters,ex);const picked=pickRandom(pool,weighted);if(!picked){setResult(pool[0]??null);return}if(pool.length===1){setResult(pool[0]);setShown(pool);return}setSpinning(true);setResult(null);const wheel=pool.length<=12?pool:[...pool.slice(0,11).filter(x=>x.candidateKey!==picked.candidateKey),picked].slice(0,12);setShown(wheel);const i=wheel.findIndex(x=>x.candidateKey===picked.candidateKey),slice=360/wheel.length,target=360-(i*slice+slice/2),reduced=await AccessibilityInfo.isReduceMotionEnabled(),delta=((target-(rotationRef.current%360)+360)%360)+(reduced?0:1800),next=rotationRef.current+delta;rotationRef.current=next;if(reduced)rotation.setValue(next);else await new Promise<void>(resolve=>Animated.timing(rotation,{toValue:next,duration:2400,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start(()=>resolve()));setResult(picked);setSpinning(false)}
  async function focus(){if(result)await onStartFocus(result)}
  const modes:[WheelMode,string,string][]=[['all',ar?'كل المهام':'All Tasks',ar?'أدر كل المهام المتاحة.':'Spin all eligible tasks.'],['pick',ar?'اختر المهام':'Pick Tasks',ar?'اختر مهام محددة بنفسك.':'Choose specific tasks yourself.'],['filter',ar?'تصفية المهام':'Filter Tasks',ar?'استخدم خصائص المهام.':'Use task properties.']]
  return <AppScreen><View className="mb-4 flex-row items-start gap-3"><Pressable onPress={onBack} accessibilityLabel={ar?'رجوع':'Back'} className="mt-1 rounded-xl border p-2" style={{borderColor:colors.border}}><ArrowLeft size={20} color={colors.text}/></Pressable><View className="flex-1"><Text className="text-2xl font-black" style={{color:colors.text}}>{ar?'ابدأ عشوائيًا':'Random Start'}</Text><Text className="mt-1 text-sm" style={{color:colors.secondaryText}}>{ar?'مش عارف بأي مهمة تبدأ؟ جهّز العجلة ودع BeePlan يختار لك.':"Can't decide what to do next? Build your wheel and let BeePlan choose."}</Text></View></View>
    <View className="gap-2">{modes.map(([value,title,desc])=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:mode===value}} onPress={()=>{setMode(value);setResult(null)}} className="flex-row items-center gap-3 rounded-2xl border p-3" style={{borderColor:mode===value?colors.accent:colors.border,backgroundColor:mode===value?colors.accentSoft:colors.surface}}>{mode===value?<Check size={18} color={colors.accent}/>:<Dices size={18} color={colors.secondaryText}/>}<View><Text className="font-black" style={{color:colors.text}}>{title}</Text><Text className="text-xs" style={{color:colors.secondaryText}}>{desc}</Text></View></Pressable>)}</View>
    {mode==='pick'?<SectionCard className="mt-4"><View className="flex-row items-center gap-2 rounded-xl border px-3" style={{borderColor:colors.border}}><Search size={16} color={colors.secondaryText}/><TextInput value={query} onChangeText={setQuery} placeholder={ar?'ابحث في المهام':'Search tasks'} placeholderTextColor={colors.secondaryText} className="flex-1 py-3" style={{color:colors.text}}/></View><View className="mt-3 flex-row gap-4"><Pressable onPress={()=>setSelected(new Set(all.map(x=>x.candidateKey)))}><Text className="font-bold" style={{color:colors.accent}}>Select All</Text></Pressable><Pressable onPress={()=>setSelected(new Set())}><Text style={{color:colors.secondaryText}}>Clear</Text></Pressable></View><View className="mt-2">{visible.map(x=><Pressable key={x.candidateKey} onPress={()=>setSelected(s=>{const n=new Set(s);n.has(x.candidateKey)?n.delete(x.candidateKey):n.add(x.candidateKey);return n})} accessibilityRole="checkbox" accessibilityState={{checked:selected.has(x.candidateKey)}} className="mt-2 flex-row items-center gap-3 rounded-xl border p-3" style={{borderColor:colors.border}}><View className="h-5 w-5 items-center justify-center rounded border" style={{borderColor:colors.accent,backgroundColor:selected.has(x.candidateKey)?colors.accent:'transparent'}}>{selected.has(x.candidateKey)?<Check size={14} color={colors.accentText}/>:null}</View><View className="flex-1"><Text numberOfLines={1} style={{color:colors.text,writingDirection:isRtlLabel(x.title)?'rtl':'ltr'}}>{x.title}</Text><Text className="text-xs capitalize" style={{color:colors.secondaryText}}>{x.priority}{x.estimatedTimeMinutes?` · ${x.estimatedTimeMinutes} min`:''}</Text><DependencyInfo task={x} ar={ar} colors={colors}/></View></Pressable>)}</View></SectionCard>:null}
    {mode==='filter'?<SectionCard className="mt-4">{([['priorities','Priority',[['high','High'],['medium','Medium'],['low','Low']]],['due','Due',[['today','Today'],['week','This Week'],['none','No Deadline']]],['durations','Estimated time',[['under30','Under 30 min'],['30to60','30–60 min'],['over60','1h+']]]] as const).map(([g,label,values])=><View key={g} className="mb-4"><Text className="mb-2 font-black" style={{color:colors.text}}>{label}</Text><View className="flex-row flex-wrap gap-2">{values.map(([v,label])=><Pressable key={v} onPress={()=>toggleFilter(g,v)} accessibilityState={{selected:filters[g].includes(v)}} className="rounded-full border px-3 py-2" style={{borderColor:filters[g].includes(v)?colors.accent:colors.border,backgroundColor:filters[g].includes(v)?colors.accentSoft:colors.surface}}><Text className="text-xs font-bold" style={{color:colors.text}}>{label}</Text></Pressable>)}</View></View>)}</SectionCard>:null}
    <SectionCard className="mt-4"><Pressable onPress={()=>setWeighted(v=>!v)} accessibilityRole="switch" accessibilityState={{checked:weighted}} className="flex-row items-center justify-between"><View><Text className="font-black" style={{color:colors.text}}>{ar?'ترجيح حسب الأولوية':'Weighted by priority'}</Text><Text className="text-xs" style={{color:colors.secondaryText}}>High 3× · Medium 2× · Low 1×</Text></View><View className="h-7 w-12 rounded-full p-1" style={{backgroundColor:weighted?colors.accent:colors.border}}><View className="h-5 w-5 rounded-full" style={{backgroundColor:colors.surface,marginLeft:weighted?20:0}}/></View></Pressable></SectionCard>
    <View className="mt-7 items-center"><Wheel items={shown.length?shown:eligible.slice(0,12)} rotation={rotation} size={size} colors={colors}/><Text className="mt-4 text-sm" style={{color:colors.secondaryText}}>{eligible.length<2?(mode==='filter'?(ar?'لا توجد مهام تطابق هذه التصفيات.':'No tasks match these filters.'):(ar?'اختر مهمتين على الأقل لتجهيز العجلة.':'Choose at least two tasks to build your wheel.')):`${formatNumber(eligible.length)} ${ar?'مهمة في العجلة':'tasks in wheel'}`}</Text><Pressable disabled={loading||spinning||eligible.length<2} onPress={()=>void spin()} className="mt-3 min-w-56 flex-row items-center justify-center gap-2 rounded-xl px-6 py-4" style={{backgroundColor:colors.accent,opacity:loading||spinning||eligible.length<2?.45:1}}><Dices size={18} color={colors.accentText}/><Text className="font-black" style={{color:colors.accentText}}>{ar?'ابدأ الدوران':'Spin'} {formatNumber(eligible.length)} {ar?'مهمة':'tasks'}</Text></Pressable></View>
    {result&&!spinning?<SectionCard className="mt-5" style={{borderColor:colors.accent,backgroundColor:colors.accentSoft}}><Text className="text-xs font-black uppercase" style={{color:colors.accent}}>🐝 {ar?'مهمتك التالية':'Your next task'}</Text><Text className="mt-2 text-xl font-black" style={{color:colors.text,writingDirection:isRtlLabel(result.title)?'rtl':'ltr'}}>{result.title}</Text><Text className="mt-1 text-sm capitalize" style={{color:colors.secondaryText}}>{result.priority}{result.estimatedTimeMinutes?` · ${result.estimatedTimeMinutes} min`:''}</Text><DependencyInfo task={result} ar={ar} colors={colors} result/><Pressable onPress={()=>void focus()} className="mt-4 flex-row items-center justify-center gap-2 rounded-xl p-3" style={{backgroundColor:colors.accent}}><Target size={16} color={colors.accentText}/><Text className="font-black" style={{color:colors.accentText}}>{ar?'ابدأ التركيز':'Start Focus'}</Text></Pressable><View className="mt-3 flex-row flex-wrap justify-center gap-3"><Pressable onPress={()=>void spin()}><Text className="font-bold" style={{color:colors.accent}}>{ar?'أدر مرة أخرى':'Spin Again'}</Text></Pressable><Pressable onPress={()=>onViewTask(result.taskId??result.id)}><Text className="font-bold" style={{color:colors.text}}>{ar?'عرض المهمة':'View Task'}</Text></Pressable><Pressable onPress={()=>void spin(result)}><Text className="font-bold" style={{color:colors.secondaryText}}>{ar?'استبعدها وأدر مرة أخرى':'Remove & spin again'}</Text></Pressable></View></SectionCard>:null}{error?<Text className="mt-4" style={{color:colors.error}}>{error}</Text>:null}
  </AppScreen>
}
