import { Activity, CalendarDays, Clock3, Sparkles, Target, TriangleAlert } from 'lucide-react-native';
import { Pressable, Text, View } from 'react-native';
import { BottomNavBar, ScreenLayout, SectionCard } from '../components/layout';
import type { TodayDashboard, TodayDashboardRecommendation } from '../lib/tasksApi';
import { focusParentLabel, focusPrimaryTitle } from '../lib/focusDisplay';
import { useTheme } from '../theme/useTheme';

type Props = { dashboard: TodayDashboard | null; summaryLoading?: boolean; summaryError?: string; onRetrySummary?: () => void; onRefresh?: () => void; onSignOut: () => void; onViewTasks: () => void; onViewFocus?: () => void; onViewReminders: () => void; onViewNotes?: () => void; onViewAnalytics?: () => void; onViewCalendar?: () => void; onViewAiDailyPlanner?: () => void; onViewNotifications?: () => void; unreadCount?: number; onStartFocus: (item: TodayDashboardRecommendation) => Promise<void>; onContinueFocus: () => void };

export default function TasksDashboardScreen({ dashboard, summaryLoading = false, summaryError = '', onRetrySummary, onRefresh, onSignOut, onViewTasks, onViewFocus, onViewReminders, onViewNotifications, unreadCount, onStartFocus, onContinueFocus }: Props) {
  const { theme } = useTheme(); const { colors } = theme;
  return <ScreenLayout headerSubtitle={dashboard?.greeting ?? 'Today'} onSignOut={onSignOut} onOpenNotifications={onViewNotifications} unreadCount={unreadCount} refreshing={summaryLoading && Boolean(dashboard)} onRefresh={onRefresh} footer={<BottomNavBar active="dashboard" onNavigateTasks={onViewTasks} onNavigateFocus={onViewFocus} onNavigateReminders={onViewReminders} />}>
    {summaryError ? <SectionCard className="mb-3"><Text style={{ color: colors.error }}>{summaryError}</Text><Pressable onPress={onRetrySummary} accessibilityRole="button" accessibilityLabel="Retry dashboard" className="mt-2"><Text style={{ color: colors.accent }}>Retry dashboard</Text></Pressable></SectionCard> : null}
    {summaryLoading && !dashboard ? <Skeleton /> : dashboard ? <View className="gap-3"><Status dashboard={dashboard} /><KpiRow dashboard={dashboard} /><Primary dashboard={dashboard} onStart={onStartFocus} onContinue={onContinueFocus} /><Timeline dashboard={dashboard} /><Progress dashboard={dashboard} /><Tomorrow dashboard={dashboard} />{dashboard.locationContext ? <SectionCard><Text style={{ color: colors.text }}>{dashboard.locationContext.label}</Text></SectionCard> : null}</View> : <SectionCard><Text style={{ color: colors.text }}>Nothing planned yet</Text></SectionCard>}
  </ScreenLayout>;
}

function Status({ dashboard }: { dashboard: TodayDashboard }) { const { theme } = useTheme(); const c = theme.colors; const tone = dashboard.dailyStatus.statusTone === 'danger' ? c.error : dashboard.dailyStatus.statusTone === 'warning' ? c.warning : c.accent; return <SectionCard><View className="flex-row items-center gap-2"><Sparkles accessible={false} size={18} strokeWidth={1.75} color={c.accent} /><Text className="text-xl font-black" style={{ color: c.text }}>{dashboard.greeting}</Text></View><Text className="mt-2 text-sm font-bold" style={{ color: tone }}>{dashboard.dailyStatus.status}</Text>{dashboard.dailyStatus.summaryLines.map((line) => <Text key={line} className="mt-1 text-xs" style={{ color: c.secondaryText }}>{line}</Text>)}</SectionCard> }

function KpiRow({ dashboard }: { dashboard: TodayDashboard }) { const { theme } = useTheme(); const c = theme.colors; const priority = dashboard.whyNow.find((reason) => reason.code === 'high_priority'); const tomorrow = dashboard.tomorrowPreview; return <View accessibilityLabel="Today at a glance" className="gap-3"><FocusTodayKpi focusMinutes={dashboard.progress.focusMinutes} /><SectionCard><View className="flex-row items-center gap-2"><View accessible={false} className="h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: c.progressTrack }}><TriangleAlert size={20} strokeWidth={1.75} color={c.warning} /></View><Text className="text-xs font-bold uppercase" style={{ color: c.warning }}>Priority</Text></View><Text className="mt-2 text-lg font-black" style={{ color: c.text }}>{priority?.value ?? (priority ? 'Attention needed' : dashboard.dailyStatus.status)}</Text><Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{priority ? 'A high-priority item is ready' : 'Today’s attention signal'}</Text></SectionCard><SectionCard><View className="flex-row items-center gap-2"><View accessible={false} className="h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: c.progressTrack }}><CalendarDays size={20} strokeWidth={1.75} color="#60a5fa" /></View><Text className="text-xs font-bold uppercase" style={{ color: '#60a5fa' }}>Tomorrow</Text></View><Text className="mt-2 text-lg font-black" style={{ color: c.text }}>≈{formatMinutes(tomorrow.estimatedWorkMinutes)} planned</Text><Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{tomorrow.dueWorkUnits} due {tomorrow.dueWorkUnits === 1 ? 'item' : 'items'}</Text></SectionCard></View> }

function FocusTodayKpi({ focusMinutes }: { focusMinutes: number }) { const { theme } = useTheme(); const c = theme.colors; return <SectionCard><View className="flex-row items-center gap-2"><View accessible={false} className="h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: c.accentSoft }}><Target size={20} strokeWidth={1.75} color={c.accent} /></View><Text className="text-xs font-bold uppercase" style={{ color: c.accent }}>Focus Today</Text></View><Text accessibilityLabel={`${formatMinutes(focusMinutes)} focused today`} className="mt-2 text-3xl font-black" style={{ color: c.text }}>{formatMinutes(focusMinutes)}</Text><Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>Focused today</Text></SectionCard> }

function Primary({ dashboard, onStart, onContinue }: { dashboard: TodayDashboard; onStart: (item: TodayDashboardRecommendation) => Promise<void>; onContinue: () => void }) { const { theme } = useTheme(); const c = theme.colors; const active = dashboard.activeFocus; const item = active ?? dashboard.recommendation; if (!item) return <SectionCard style={{ backgroundColor: c.accentSoft }}><Target accessible={false} size={18} strokeWidth={1.75} color={c.accent} /><Text className="mt-2 text-base font-bold" style={{ color: c.text }}>Your day is clear</Text><Text className="text-xs" style={{ color: c.secondaryText }}>There is no Focus recommendation right now.</Text></SectionCard>; const title = focusPrimaryTitle(item); const parent = focusParentLabel(item); const minutes = 'plannedMinutes' in item ? item.plannedMinutes : item.estimatedMinutes; return <SectionCard style={{ borderColor: c.accent, backgroundColor: c.card }}><View className="flex-row items-center gap-2"><Target accessible={false} size={18} strokeWidth={1.75} color={c.accent} /><Text className="text-xs font-bold uppercase" style={{ color: c.accent }}>Do This Now</Text></View><Text className="mt-3 text-2xl font-black" style={{ color: c.text }}>{title}</Text>{parent ? <Text className="mt-2 text-sm" style={{ color: c.secondaryText }}>{parent}</Text> : null}<View className="mt-4 flex-row flex-wrap gap-2">{minutes ? <View className="rounded-full px-3 py-1.5" style={{ backgroundColor: c.accentSoft }}><Text className="text-xs font-semibold" style={{ color: c.text }}>{minutes} min focus</Text></View> : null}{'status' in item ? <View className="rounded-full px-3 py-1.5" style={{ backgroundColor: c.progressTrack }}><Text className="text-xs font-semibold capitalize" style={{ color: c.secondaryText }}>{item.status}</Text></View> : null}</View>{dashboard.whyNow.length ? <View className="mt-5"><Text className="text-xs font-bold uppercase" style={{ color: c.secondaryText }}>Why this</Text><View className="mt-2 flex-row flex-wrap gap-2">{dashboard.whyNow.map((reason) => <View key={reason.code} className="rounded-full px-3 py-1.5" style={{ backgroundColor: c.accentSoft }}><Text className="text-xs font-semibold" style={{ color: c.accent }}>{reason.label}{reason.value ? ` · ${reason.value}` : ''}</Text></View>)}</View></View> : null}<Pressable accessibilityRole="button" accessibilityLabel={active ? 'Continue Focus' : 'Start Focus'} onPress={() => { if (active) onContinue(); else void onStart(item as TodayDashboardRecommendation); }} className="mt-6 flex-row items-center justify-center gap-2 rounded-xl px-5 py-3.5" style={{ backgroundColor: c.accent }}><Target accessible={false} size={16} strokeWidth={1.75} color={c.accentText} /><Text className="text-center text-base font-black" style={{ color: c.accentText }}>{active ? 'Continue Focus' : 'Start Focus'}</Text></Pressable></SectionCard> }

function Timeline({ dashboard }: { dashboard: TodayDashboard }) { const { theme } = useTheme(); const c = theme.colors; if (!dashboard.timeline.length) return <SectionCard><View className="flex-row items-center gap-2"><Clock3 accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>Today timeline</Text></View><Text className="mt-2 text-sm" style={{ color: c.secondaryText }}>No accepted plan is scheduled for today.</Text></SectionCard>; const now = Date.now(); const nextIndex = dashboard.timeline.findIndex((item) => new Date(item.startTime).getTime() > now); return <SectionCard><View className="flex-row items-center gap-2"><Clock3 accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>Today timeline</Text></View><View className="mt-4">{dashboard.timeline.map((item, index) => { const start = new Date(item.startTime).getTime(); const end = item.endTime ? new Date(item.endTime).getTime() : Infinity; const marker = start <= now && now < end ? 'NOW' : index === nextIndex ? 'NEXT' : 'LATER'; const current = marker === 'NOW' || (dashboard.timeline.length === 1 && index === 0); return <View key={item.id} className={`flex-row gap-3 pb-5 ${index === dashboard.timeline.length - 1 ? 'pb-0' : ''}`}><View className="items-center"><View className="mt-1 h-3 w-3 rounded-full" style={{ backgroundColor: current ? c.accent : c.secondaryText }} />{index < dashboard.timeline.length - 1 ? <View className="mt-2 w-px flex-1" style={{ backgroundColor: c.border }} /> : null}</View><View className="flex-1"><View className="flex-row flex-wrap items-center gap-2"><Text className="text-[10px] font-black" style={{ color: c.accent }}>{marker}</Text><Text className="text-xs" style={{ color: c.secondaryText }}>{formatTime(item.startTime, item.endTime, dashboard.timezone)}</Text></View><Text className="mt-1 text-sm font-bold" style={{ color: c.text }}>{item.title}</Text><Text className="text-xs capitalize" style={{ color: c.secondaryText }}>{item.type} · {item.status}</Text></View></View> })}</View></SectionCard> }

function Progress({ dashboard }: { dashboard: TodayDashboard }) { const { theme } = useTheme(); const c = theme.colors; const p = dashboard.progress; if (!p.totalWorkUnits) return <SectionCard><View className="flex-row items-center gap-2"><Activity accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>Today’s Activity</Text></View><View className="mt-3 flex-row items-baseline gap-2"><Text className="text-2xl font-black" style={{ color: c.accent }}>{formatMinutes(p.focusMinutes)}</Text><Text className="text-sm" style={{ color: c.secondaryText }}>Focus</Text></View><Text className="mt-1 text-sm" style={{ color: c.secondaryText }}>No scheduled work today.</Text></SectionCard>; return <SectionCard><View className="flex-row items-start justify-between"><View><View className="flex-row items-center gap-2"><Activity accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>Today’s progress</Text></View><Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{p.completedWorkUnits}/{p.totalWorkUnits} units complete</Text></View><Text accessibilityLabel={`${p.percent} percent complete`} className="text-sm font-bold" style={{ color: c.accent }}>{p.percent}%</Text></View><View className="mt-4 h-2.5 rounded-full" style={{ backgroundColor: c.progressTrack }}><View className="h-2.5 rounded-full" style={{ width: `${p.percent}%`, backgroundColor: c.accent }} /></View><View className="mt-3 flex-row flex-wrap gap-x-5 gap-y-1"><Text className="text-xs" style={{ color: c.secondaryText }}>{formatMinutes(p.focusMinutes)} Focus</Text><Text className="text-xs" style={{ color: c.secondaryText }}>{formatMinutes(p.remainingEstimatedMinutes)} remaining</Text></View></SectionCard> }

function Tomorrow({ dashboard }: { dashboard: TodayDashboard }) { const { theme } = useTheme(); const c = theme.colors; const t = dashboard.tomorrowPreview; const overloaded = t.overloadStatus === 'overloaded'; return <SectionCard style={overloaded ? { borderColor: c.error } : undefined}><View className="flex-row items-center gap-2"><CalendarDays accessible={false} size={18} strokeWidth={1.75} color="#60a5fa" /><Text className="text-base font-black" style={{ color: c.text }}>Tomorrow</Text></View>{overloaded ? <View className="mt-2 flex-row items-center gap-2"><TriangleAlert accessible={false} size={16} strokeWidth={1.75} color={c.error} /><Text className="text-sm font-bold" style={{ color: c.error }}>Heavy workload tomorrow</Text></View> : null}<Text className="mt-2 text-sm" style={{ color: c.secondaryText }}>≈{formatMinutes(t.estimatedWorkMinutes)} planned · {t.dueWorkUnits} due items · {t.highPriorityItems} high priority</Text>{t.capacityMinutes !== null ? <Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{formatMinutes(t.capacityMinutes)} planned capacity</Text> : null}{overloaded ? <Text className="mt-2 text-xs" style={{ color: c.secondaryText }}>Review your plan tonight.</Text> : null}</SectionCard> }

function Skeleton() { const { theme } = useTheme(); return <View className="gap-3">{[1, 2, 3].map((key) => <View key={key} className="h-28 rounded-2xl" style={{ backgroundColor: theme.colors.surfaceElevated }} />)}</View> }
export function formatMinutes(minutes: number) { const hours = Math.floor(Math.max(0, minutes) / 60); const rest = Math.max(0, minutes) % 60; return hours ? `${hours}h${rest ? ` ${rest}m` : ''}` : `${rest}m`; }
function formatTime(start: string, end: string | null, timezone: string) { const options: Intl.DateTimeFormatOptions = { hour: 'numeric', minute: '2-digit', timeZone: timezone }; const format = (value: string) => new Intl.DateTimeFormat(undefined, options).format(new Date(value)); return end ? `${format(start)}–${format(end)}` : `${format(start)}–now`; }
