import { Activity, CalendarDays, Clock3, Sparkles, Target, TriangleAlert } from 'lucide-react-native';
import { Pressable, Text, View } from 'react-native';
import { BottomNavBar, ScreenLayout, SectionCard } from '../components/layout';
import type { TodayDashboard, TodayDashboardRecommendation } from '../lib/tasksApi';
import { focusParentLabel, focusPrimaryTitle } from '../lib/focusDisplay';
import { useTheme } from '../theme/useTheme';
import { RandomStartSheet } from '../components/RandomStartSheet';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '../hooks/useAuth';
import { challengesApi, type Challenge } from '../features/challenges/challengesApi';
import { useNavigation } from '@react-navigation/native';
import { useLanguage } from '../i18n/LanguageContext';

type Props = { dashboard: TodayDashboard | null; accessToken?: string; onOpenTask?: (id: string) => void; onOpenRandomStart?: () => void; summaryLoading?: boolean; summaryError?: string; onRetrySummary?: () => void; onRefresh?: () => void; onSignOut: () => void; onViewTasks: () => void; onViewFocus?: () => void; onViewReminders: () => void; onViewNotes?: () => void; onViewAnalytics?: () => void; onViewSettings?: () => void; onViewCalendar?: () => void; onViewAiDailyPlanner?: () => void; onViewNotifications?: () => void; unreadCount?: number; onStartFocus: (item: TodayDashboardRecommendation) => Promise<void>; onContinueFocus: () => void };

export default function TasksDashboardScreen({ dashboard, onOpenRandomStart, summaryLoading = false, summaryError = '', onRetrySummary, onRefresh, onSignOut, onViewTasks, onViewFocus, onViewReminders, onViewSettings, onViewNotifications, unreadCount, onStartFocus, onContinueFocus }: Props) {
  const { theme } = useTheme(); const { colors } = theme; const { t } = useLanguage();
  return <ScreenLayout headerSubtitle={dashboard?.greeting ?? t('dashboardUi.today')} onSignOut={onSignOut} onOpenNotifications={onViewNotifications} unreadCount={unreadCount} refreshing={summaryLoading && Boolean(dashboard)} onRefresh={onRefresh} footer={<BottomNavBar active="dashboard" onNavigateTasks={onViewTasks} onNavigateFocus={onViewFocus} onNavigateReminders={onViewReminders} />}>
    {summaryError ? <SectionCard className="mb-3"><Text style={{ color: colors.error }}>{t('dashboardUi.loadFailed')}</Text><Pressable onPress={onRetrySummary} accessibilityRole="button" accessibilityLabel={t('dashboardUi.retry')} className="mt-2"><Text style={{ color: colors.accentInk }}>{t('dashboardUi.retry')}</Text></Pressable></SectionCard> : null}
    {onViewSettings ? <Pressable onPress={onViewSettings} accessibilityRole="button" accessibilityLabel={t('dashboardUi.openSettings')} className="mb-3 self-end"><Text className="text-sm font-bold" style={{ color: colors.accentInk }}>{t('dashboardUi.settings')}</Text></Pressable> : null}
    {summaryLoading && !dashboard ? <Skeleton /> : dashboard ? <View className="gap-3"><Status dashboard={dashboard} />{onOpenRandomStart ? <RandomStartSheet onOpen={onOpenRandomStart} /> : null}<KpiRow dashboard={dashboard} /><Primary dashboard={dashboard} onStart={onStartFocus} onContinue={onContinueFocus} /><Timeline dashboard={dashboard} /><Progress dashboard={dashboard} /><Tomorrow dashboard={dashboard} />{dashboard.locationContext ? <SectionCard><Text style={{ color: colors.text }}>{dashboard.locationContext.label}</Text></SectionCard> : null}</View> : <SectionCard><Text style={{ color: colors.text }}>{t('dashboardUi.nothingPlanned')}</Text></SectionCard>}
  </ScreenLayout>;
}

function Status({ dashboard }: { dashboard: TodayDashboard }) { const { theme } = useTheme(); const { t } = useLanguage(); const c = theme.colors; const tone = dashboard.dailyStatus.statusTone === 'danger' ? c.error : dashboard.dailyStatus.statusTone === 'warning' ? c.warning : c.accent; const {accessToken}=useAuth(); const navigation=useNavigation<any>(); const q=useQuery({queryKey:['challenges'],queryFn:()=>challengesApi.list(accessToken!),enabled:Boolean(accessToken)}); const challenge=q.data?.filter((item:Challenge)=>item.status==='active').sort((a,b)=>(Number(a.completed)-Number(b.completed)) || new Date(a.endAt).getTime()-new Date(b.endAt).getTime())[0]; const value=challenge?Math.min(challenge.progressValue,challenge.targetValue):0; const percent=challenge?Math.min(100,Math.max(0,value/challenge.targetValue*100)):0; const unit=challenge?.type==='focus_minutes'?t('challenges.minutes'):challenge?.type==='focus_sessions'?t('challenges.sessions'):t('challenges.tasks'); return <><SectionCard><View className="flex-row items-center gap-2"><Sparkles accessible={false} size={18} strokeWidth={1.75} color={c.accent} /><Text className="text-xl font-black" style={{ color: c.text }}>{dashboard.greeting}</Text></View><Text className="mt-2 text-sm font-bold" style={{ color: tone }}>{dashboard.dailyStatus.status}</Text>{dashboard.dailyStatus.summaryLines.map((line) => <Text key={line} className="mt-1 text-xs" style={{ color: c.secondaryText }}>{line}</Text>)}</SectionCard>{challenge?<Pressable onPress={()=>navigation.navigate('ChallengeDetail',{challengeId:challenge.id})}><SectionCard><Text className="text-xs font-black uppercase" style={{color:c.accentInk}}>{t('challenges.community')}</Text><Text className="mt-1 text-base font-black" style={{color:c.text}}>{challenge.title}</Text><Text className="mt-3 font-bold" style={{color:c.text}}>{value} / {challenge.targetValue} {unit}</Text><View className="mt-2 h-2 overflow-hidden rounded-full" style={{backgroundColor:c.progressTrack}}><View className="h-full rounded-full" style={{width:`${percent}%`,backgroundColor:c.accent}}/></View><Text className="mt-3 text-sm font-bold" style={{color:c.accentInk}}>{t('challenges.view')}</Text></SectionCard></Pressable>:null}</> }

function KpiRow({ dashboard }: { dashboard: TodayDashboard }) {
  const { theme } = useTheme();
  const { t } = useLanguage();
  const c = theme.colors;
  const priority = dashboard.whyNow.find((reason) => reason.code === 'high_priority');
  const tomorrow = dashboard.tomorrowPreview;
  return <View accessibilityLabel={t('dashboardUi.atAGlance')} className="gap-3">
    <FocusTodayKpi focusMinutes={dashboard.progress.focusMinutes} />
    <SectionCard>
      <View className="flex-row items-center gap-2"><View accessible={false} className="h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: c.progressTrack }}><TriangleAlert size={20} strokeWidth={1.75} color={c.warning} /></View><Text className="text-xs font-bold uppercase" style={{ color: c.warning }}>{t('dashboardUi.priority')}</Text></View>
      <Text className="mt-2 text-lg font-black" style={{ color: c.text }}>{priority?.value ?? (priority ? t('dashboardUi.attentionNeeded') : dashboard.dailyStatus.status)}</Text>
      <Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{priority ? t('dashboardUi.highPriorityReady') : t('dashboardUi.attentionSignal')}</Text>
    </SectionCard>
    <SectionCard>
      <View className="flex-row items-center gap-2"><View accessible={false} className="h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: c.progressTrack }}><CalendarDays size={20} strokeWidth={1.75} color="#60a5fa" /></View><Text className="text-xs font-bold uppercase" style={{ color: '#60a5fa' }}>{t('dashboardUi.tomorrow')}</Text></View>
      <Text className="mt-2 text-lg font-black" style={{ color: c.text }}>{t('dashboardUi.planned', { value: formatMinutes(tomorrow.estimatedWorkMinutes, t) })}</Text>
      <Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{t('dashboardUi.dueItems', { count: tomorrow.dueWorkUnits })}</Text>
    </SectionCard>
  </View>;
}

function FocusTodayKpi({ focusMinutes }: { focusMinutes: number }) {
  const { theme } = useTheme();
  const { t } = useLanguage();
  const c = theme.colors;
  const duration = formatMinutes(focusMinutes, t);
  return <SectionCard><View className="flex-row items-center gap-2"><View accessible={false} className="h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: c.accentSoft }}><Target size={20} strokeWidth={1.75} color={c.accent} /></View><Text className="text-xs font-bold uppercase" style={{ color: c.accentInk }}>{t('dashboardUi.focusToday')}</Text></View><Text accessibilityLabel={t('dashboardUi.focusedDuration', { value: duration })} className="mt-2 text-3xl font-black" style={{ color: c.text }}>{duration}</Text><Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{t('dashboardUi.focusedToday')}</Text></SectionCard>;
}

function Primary({ dashboard, onStart, onContinue }: { dashboard: TodayDashboard; onStart: (item: TodayDashboardRecommendation) => Promise<void>; onContinue: () => void }) {
  const { theme } = useTheme();
  const { t } = useLanguage();
  const c = theme.colors;
  const active = dashboard.activeFocus;
  const item = active ?? dashboard.recommendation;
  if (!item) return <SectionCard style={{ backgroundColor: c.accentSoft }}><Target accessible={false} size={18} strokeWidth={1.75} color={c.accent} /><Text className="mt-2 text-base font-bold" style={{ color: c.text }}>{t('dashboardUi.dayClear')}</Text><Text className="text-xs" style={{ color: c.secondaryText }}>{t('dashboardUi.noFocusRecommendation')}</Text></SectionCard>;
  const title = focusPrimaryTitle(item);
  const parent = focusParentLabel(item);
  const minutes = 'plannedMinutes' in item ? item.plannedMinutes : item.estimatedMinutes;
  const actionLabel = active ? t('dashboardUi.continueFocus') : t('dashboardUi.startFocus');
  return <SectionCard style={{ borderColor: c.accent, backgroundColor: c.accentSoft, shadowColor: c.accent, shadowOpacity: 0.18, shadowRadius: 15, elevation: 3 }}><View className="flex-row items-center gap-2"><Target accessible={false} size={18} strokeWidth={1.75} color={c.accent} /><Text className="text-xs font-bold uppercase" style={{ color: c.accentInk }}>{t('dashboardUi.doThisNow')}</Text></View><Text className="mt-3 text-2xl font-black" style={{ color: c.text }}>{title}</Text>{parent ? <Text className="mt-2 text-sm" style={{ color: c.secondaryText }}>{parent}</Text> : null}<View className="mt-4 flex-row flex-wrap gap-2">{minutes ? <View className="rounded-full px-3 py-1.5" style={{ backgroundColor: c.accentSoft }}><Text className="text-xs font-semibold" style={{ color: c.text }}>{t('dashboardUi.minutesFocus', { count: minutes })}</Text></View> : null}{'status' in item ? <View className="rounded-full px-3 py-1.5" style={{ backgroundColor: c.progressTrack }}><Text className="text-xs font-semibold capitalize" style={{ color: c.secondaryText }}>{item.status}</Text></View> : null}</View>{dashboard.whyNow.length ? <View className="mt-5"><Text className="text-xs font-bold uppercase" style={{ color: c.secondaryText }}>{t('dashboardUi.whyThis')}</Text><View className="mt-2 flex-row flex-wrap gap-2">{dashboard.whyNow.map((reason) => <View key={reason.code} className="rounded-full px-3 py-1.5" style={{ backgroundColor: c.accentSoft }}><Text className="text-xs font-semibold" style={{ color: c.accentInk }}>{reason.label}{reason.value ? ` · ${reason.value}` : ''}</Text></View>)}</View></View> : null}<Pressable accessibilityRole="button" accessibilityLabel={actionLabel} onPress={() => { if (active) onContinue(); else void onStart(item as TodayDashboardRecommendation); }} className="mt-6 flex-row items-center justify-center gap-2 rounded-xl px-5 py-3.5" style={{ backgroundColor: c.accent }}><Target accessible={false} size={16} strokeWidth={1.75} color={c.accentText} /><Text className="text-center text-base font-black" style={{ color: c.accentText }}>{actionLabel}</Text></Pressable></SectionCard>;
}

function Timeline({ dashboard }: { dashboard: TodayDashboard }) {
  const { theme } = useTheme();
  const { t, language } = useLanguage();
  const c = theme.colors;
  if (!dashboard.timeline.length) return <SectionCard><View className="flex-row items-center gap-2"><Clock3 accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>{t('dashboardUi.todayTimeline')}</Text></View><Text className="mt-2 text-sm" style={{ color: c.secondaryText }}>{t('dashboardUi.noPlanToday')}</Text></SectionCard>;
  const now = Date.now();
  const nextIndex = dashboard.timeline.findIndex((item) => new Date(item.startTime).getTime() > now);
  return <SectionCard><View className="flex-row items-center gap-2"><Clock3 accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>{t('dashboardUi.todayTimeline')}</Text></View><View className="mt-4">{dashboard.timeline.map((item, index) => { const start = new Date(item.startTime).getTime(); const end = item.endTime ? new Date(item.endTime).getTime() : Infinity; const markerKey = start <= now && now < end ? 'now' : index === nextIndex ? 'next' : 'later'; const current = markerKey === 'now' || (dashboard.timeline.length === 1 && index === 0); return <View key={item.id} className={`flex-row gap-3 pb-5 ${index === dashboard.timeline.length - 1 ? 'pb-0' : ''}`}><View className="items-center"><View className="mt-1 h-3 w-3 rounded-full" style={{ backgroundColor: current ? c.accent : c.secondaryText }} />{index < dashboard.timeline.length - 1 ? <View className="mt-2 w-px flex-1" style={{ backgroundColor: c.border }} /> : null}</View><View className="flex-1"><View className="flex-row flex-wrap items-center gap-2"><Text className="text-[10px] font-black" style={{ color: c.accentInk }}>{t(`dashboardUi.${markerKey}`)}</Text><Text className="text-xs" style={{ color: c.secondaryText }}>{formatTime(item.startTime, item.endTime, dashboard.timezone, language)}</Text></View><Text className="mt-1 text-sm font-bold" style={{ color: c.text }}>{item.title}</Text><Text className="text-xs capitalize" style={{ color: c.secondaryText }}>{item.type} · {item.status}</Text></View></View> })}</View></SectionCard>;
}

function Progress({ dashboard }: { dashboard: TodayDashboard }) {
  const { theme } = useTheme(); const { t, formatPercent } = useLanguage(); const c = theme.colors; const p = dashboard.progress;
  if (!p.totalWorkUnits) return <SectionCard><View className="flex-row items-center gap-2"><Activity accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>{t('dashboardUi.todayActivity')}</Text></View><View className="mt-3 flex-row items-baseline gap-2"><Text className="text-2xl font-black" style={{ color: c.accentInk }}>{formatMinutes(p.focusMinutes, t)}</Text><Text className="text-sm" style={{ color: c.secondaryText }}>{t('dashboardUi.focus')}</Text></View><Text className="mt-1 text-sm" style={{ color: c.secondaryText }}>{t('dashboardUi.noScheduledWork')}</Text></SectionCard>;
  return <SectionCard><View className="flex-row items-start justify-between"><View><View className="flex-row items-center gap-2"><Activity accessible={false} size={18} strokeWidth={1.75} color={c.secondaryText} /><Text className="text-base font-black" style={{ color: c.text }}>{t('dashboardUi.todayProgress')}</Text></View><Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{t('dashboardUi.unitsComplete', { completed: p.completedWorkUnits, total: p.totalWorkUnits })}</Text></View><Text accessibilityLabel={t('dashboardUi.percentComplete', { value: p.percent })} className="text-sm font-bold" style={{ color: c.accentInk }}>{formatPercent(p.percent)}</Text></View><View className="mt-4 h-2.5 rounded-full" style={{ backgroundColor: c.progressTrack }}><View className="h-2.5 rounded-full" style={{ width: `${p.percent}%`, backgroundColor: c.accent }} /></View><View className="mt-3 flex-row flex-wrap gap-x-5 gap-y-1"><Text className="text-xs" style={{ color: c.secondaryText }}>{t('dashboardUi.focusValue', { value: formatMinutes(p.focusMinutes, t) })}</Text><Text className="text-xs" style={{ color: c.secondaryText }}>{t('dashboardUi.remaining', { value: formatMinutes(p.remainingEstimatedMinutes, t) })}</Text></View></SectionCard>;
}

function Tomorrow({ dashboard }: { dashboard: TodayDashboard }) {
  const { theme } = useTheme(); const { t: translate } = useLanguage(); const c = theme.colors; const preview = dashboard.tomorrowPreview; const overloaded = preview.overloadStatus === 'overloaded';
  return <SectionCard style={overloaded ? { borderColor: c.error } : undefined}><View className="flex-row items-center gap-2"><CalendarDays accessible={false} size={18} strokeWidth={1.75} color="#60a5fa" /><Text className="text-base font-black" style={{ color: c.text }}>{translate('dashboardUi.tomorrow')}</Text></View>{overloaded ? <View className="mt-2 flex-row items-center gap-2"><TriangleAlert accessible={false} size={16} strokeWidth={1.75} color={c.error} /><Text className="text-sm font-bold" style={{ color: c.error }}>{translate('dashboardUi.heavyWorkload')}</Text></View> : null}<Text className="mt-2 text-sm" style={{ color: c.secondaryText }}>{translate('dashboardUi.tomorrowSummary', { estimate: formatMinutes(preview.estimatedWorkMinutes, translate), due: preview.dueWorkUnits, priority: preview.highPriorityItems })}</Text>{preview.capacityMinutes !== null ? <Text className="mt-1 text-xs" style={{ color: c.secondaryText }}>{translate('dashboardUi.plannedCapacity', { value: formatMinutes(preview.capacityMinutes, translate) })}</Text> : null}{overloaded ? <Text className="mt-2 text-xs" style={{ color: c.secondaryText }}>{translate('dashboardUi.reviewPlan')}</Text> : null}</SectionCard>;
}

function Skeleton() { const { theme } = useTheme(); return <View className="gap-3">{[1, 2, 3].map((key) => <View key={key} className="h-28 rounded-2xl" style={{ backgroundColor: theme.colors.surfaceElevated }} />)}</View> }
export function formatMinutes(minutes: number, t?: ReturnType<typeof useLanguage>['t']) { const hours = Math.floor(Math.max(0, minutes) / 60); const rest = Math.max(0, minutes) % 60; if (!t) return hours ? `${hours}h${rest ? ` ${rest}m` : ''}` : `${rest}m`; if (!hours) return t('dashboardUi.minutes', { count: rest }); if (!rest) return t('dashboardUi.hours', { count: hours }); return t('dashboardUi.hoursMinutes', { hours, minutes: rest }); }
function formatTime(start: string, end: string | null, timezone: string, language: 'en' | 'ar') { const options: Intl.DateTimeFormatOptions = { hour: 'numeric', minute: '2-digit', timeZone: timezone }; const format = (value: string) => new Intl.DateTimeFormat(language === 'ar' ? 'ar' : 'en-US', options).format(new Date(value)); return end ? `${format(start)}–${format(end)}` : format(start); }
