import { API_BASE_URL, apiFetch, readJsonOrThrow } from './apiClient'

export type DailyPlanItem = { id: string; type: 'task' | 'reminder' | 'break' | 'calendar'; taskId?: string; reminderId?: string; title: string; startTime: string; endTime: string; durationMinutes: number; priority: 'low' | 'medium' | 'high' | 'urgent'; category?: string; isFocusTask?: boolean; locked?: boolean; rationale?: string }
export type UnscheduledItem = { taskId?: string; reminderId?: string; title: string; reason: string; status: string; reasonCode: string; estimatedMinutes?: number; priority?: 'low' | 'medium' | 'high' | 'urgent'; deadline?: string; suggestedDate?: string }
export type ScheduleConflict = { id: string; task: { itemId: string; taskId?: string; subtaskId?: string; title: string; startTime: string; endTime: string; durationMinutes: number; isFocusTask: boolean }; commitment: { id: string; title: string; startTime: string; endTime: string }; conflictMinutes: number }
export type DailyPlan = { date: string; generatedAt: string; source: 'ai' | 'fallback'; workingHours: { start: string; end: string }; summary: string; sections: Record<'morning' | 'afternoon' | 'evening' | 'night', DailyPlanItem[]>; unscheduled: UnscheduledItem[]; capacity: { availableMinutes: number; requestedMinutes: number; scheduledMinutes: number; postponedMinutes: number; scheduledTaskCount: number; postponedTaskCount: number; freeMinutes: number; maxDailyWorkMinutes: number; emergencyBufferMinutes: number }; conflicts: ScheduleConflict[]; taskConflicts?: import('./tasksApi').TaskTimeConflict[]; travelFeasibilityConflicts?: { type: 'travel_feasibility_conflict'; affectedItem: { id: string; title: string }; conflictingItem: { id: string; title: string } | null; requiredTravelDurationMinutes: number; requiredDeparture: string; availableGapMinutes: number; suggestedValidAlternative: string; fallbackUsed: boolean }[] }
export type PlanAcceptance = { date: string; plan: DailyPlan; acceptedAt: string }
export type EnergyLevel = 'high' | 'medium' | 'low'
export type TimeWindow = { start: string; end: string }
export type PlannerPreferences = { focusStartTime: string; focusEndTime: string; workBlockMinutes: number; breakMinutes: number; energy: { morning: EnergyLevel; afternoon: EnergyLevel; evening: EnergyLevel; night: EnergyLevel }; scheduleHardTasksInFocus: boolean; finishStartedFirst: boolean; groupSimilarTasks: boolean; bufferBeforeMeetings: boolean; bufferMinutes: number; maxDailyWorkMinutes: number; emergencyBufferMinutes: number; sleep: TimeWindow; lunch: TimeWindow; unavailableHours: TimeWindow[]; note: string }

async function request<T>(accessToken: string, path: string, init?: RequestInit) {
  const response = await apiFetch(path, { ...init, headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json', ...init?.headers } })
  return readJsonOrThrow<T>(response, `${API_BASE_URL}${path}`)
}

export function generateDailyPlan(accessToken: string, date: string, lockedItems?: { taskId?: string; reminderId?: string; startTime: string; endTime: string }[]) { return request<DailyPlan>(accessToken, '/ai/planner/daily', { method: 'POST', body: JSON.stringify({ date, currentTime: new Date().toTimeString().slice(0, 5), lockedItems }) }) }
export function acceptDailyPlan(accessToken: string, plan: DailyPlan) { return request<PlanAcceptance>(accessToken, '/ai/planner/daily/accept', { method: 'POST', body: JSON.stringify({ plan }) }) }
export function getDailyPlanAcceptance(accessToken: string, date: string) { return request<PlanAcceptance | null>(accessToken, `/ai/planner/daily/accept?date=${encodeURIComponent(date)}`) }
export function getPlannerPreferences(accessToken: string) { return request<PlannerPreferences>(accessToken, '/ai/planner/preferences') }
export function updatePlannerPreferences(accessToken: string, preferences: PlannerPreferences) { return request<PlannerPreferences>(accessToken, '/ai/planner/preferences', { method: 'PUT', body: JSON.stringify(preferences) }) }
export function skipCommitmentOccurrence(accessToken: string, commitmentId: string, date: string) { return request<{ commitmentId: string; date: string; skipped: true }>(accessToken, `/context/commitments/${commitmentId}/skip`, { method: 'POST', body: JSON.stringify({ date }) }) }
export function resolveScheduleConflict(accessToken: string, payload: { conflictKey: string; date: string; taskId?: string; commitmentId: string; resolution: 'keep_commitment' | 'keep_task' | 'postpone_task' | 'cancel_task' }) { return request<{ conflictKey: string; lifecycle: 'resolved'; resolution: string }>(accessToken, '/ai/planner/conflicts/resolve', { method: 'POST', body: JSON.stringify(payload) }) }
