import { API_BASE_URL, apiFetch, readJsonOrThrow } from './apiClient'

export type DailyPlanItem = { id: string; type: 'task' | 'reminder' | 'break' | 'calendar'; taskId?: string; subtaskId?: string; reminderId?: string; title: string; startTime: string; endTime: string; durationMinutes: number; priority: 'low' | 'medium' | 'high' | 'urgent'; category?: string; isFocusTask?: boolean; locked?: boolean; rationale?: string; selectionSource?: 'user' | 'autoFill' | 'scheduled' }
export type UnscheduledItem = { taskId?: string; reminderId?: string; title: string; reason: string; status: string; reasonCode: string; estimatedMinutes?: number; priority?: 'low' | 'medium' | 'high' | 'urgent'; deadline?: string; suggestedDate?: string }
export type ScheduleConflict = { id: string; task: { itemId: string; taskId?: string; subtaskId?: string; title: string; startTime: string; endTime: string; durationMinutes: number; isFocusTask: boolean }; commitment: { id: string; title: string; startTime: string; endTime: string }; conflictMinutes: number }
export type DailyPlan = { date: string; generatedAt: string; source: 'ai' | 'fallback'; workingHours: { start: string; end: string }; summary: string; sections: Record<'morning' | 'afternoon' | 'evening' | 'night', DailyPlanItem[]>; unscheduled: UnscheduledItem[]; capacity: { availableMinutes: number; requestedMinutes: number; scheduledMinutes: number; postponedMinutes: number; scheduledTaskCount: number; postponedTaskCount: number; freeMinutes: number; maxDailyWorkMinutes: number; emergencyBufferMinutes: number }; conflicts: ScheduleConflict[]; taskConflicts?: import('./tasksApi').TaskTimeConflict[]; travelFeasibilityConflicts?: { type: 'travel_feasibility_conflict'; affectedItem: { id: string; title: string }; conflictingItem: { id: string; title: string } | null; requiredTravelDurationMinutes: number; requiredDeparture: string; availableGapMinutes: number; suggestedValidAlternative: string; fallbackUsed: boolean }[] }
export type PlannerCandidate = { taskId: string; subtaskId: string | null; id: string; title: string; priority: 'low' | 'medium' | 'high' | 'urgent'; dueDate?: string; estimatedMinutes: number; scheduleReason?: string; scheduleCategory?: 'scheduledToday' | 'overdue' | 'upcoming' | 'unscheduled'; scheduledStartAt?: string; isAutoEligibleToday?: boolean; isManuallySelectable?: boolean; blockedReason?: string | null }
export type PlannerCandidates = { date: string; timezone?: string; availableMinutes: number; selectedItems: { taskId: string; subtaskId?: string | null }[]; items: PlannerCandidate[]; blockedItems: (PlannerCandidate & { reason: string; status: string })[] }
export type PlanAcceptance = { date: string; plan: DailyPlan; acceptedAt: string }
export type EnergyLevel = 'high' | 'medium' | 'low'
export type TimeWindow = { start: string; end: string }
export type PlannerPreferences = { focusStartTime: string; focusEndTime: string; workBlockMinutes: number; breakMinutes: number; energy: { morning: EnergyLevel; afternoon: EnergyLevel; evening: EnergyLevel; night: EnergyLevel }; scheduleHardTasksInFocus: boolean; finishStartedFirst: boolean; groupSimilarTasks: boolean; bufferBeforeMeetings: boolean; bufferMinutes: number; maxDailyWorkMinutes: number; emergencyBufferMinutes: number; sleep: TimeWindow; lunch: TimeWindow; unavailableHours: TimeWindow[]; note: string }

export function getDailyPlannerCandidates(accessToken: string, date: string) { return request<PlannerCandidates>(accessToken, `/ai/planner/daily/candidates?date=${encodeURIComponent(date)}&timezone=${encodeURIComponent(Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC')}`) }
export function saveDailyPlannerSelection(accessToken: string, payload: { date: string; selectedItems: { taskId: string; subtaskId?: string | null }[] }) { return request<{ selectedItems: { taskId: string; subtaskId?: string | null }[] }>(accessToken, '/ai/planner/daily/selection', { method: 'PUT', body: JSON.stringify({ ...payload, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' }) }) }

async function request<T>(accessToken: string, path: string, init?: RequestInit) {
  const response = await apiFetch(path, { ...init, headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json', ...init?.headers } })
  return readJsonOrThrow<T>(response, `${API_BASE_URL}${path}`)
}

export function generateDailyPlan(accessToken: string, date: string, lockedItems?: { taskId?: string; reminderId?: string; startTime: string; endTime: string }[], options?: { mode?: 'selectedOnly' | 'selectedPlusAutoFill'; selectedItems?: { taskId: string; subtaskId?: string | null }[] }) { const requestId = `mobile-planner-${Date.now()}-${Math.random().toString(36).slice(2)}`; console.debug('[planner] generate request', { requestId, date }); return request<DailyPlan>(accessToken, '/ai/planner/daily', { method: 'POST', headers: { 'X-Planner-Request-Id': requestId, 'Cache-Control': 'no-cache' }, body: JSON.stringify({ date, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC', lockedItems, ...options }) }).then((plan) => { console.debug('[planner] generated response', { requestId, generationRequestId: (plan as any).generationRequestId, generatedAt: (plan as any).generatedAt }); return plan }) }
export function acceptDailyPlan(accessToken: string, plan: DailyPlan) { return request<PlanAcceptance>(accessToken, '/ai/planner/daily/accept', { method: 'POST', body: JSON.stringify({ plan }) }) }
export function getDailyPlanAcceptance(accessToken: string, date: string) { return request<PlanAcceptance | null>(accessToken, `/ai/planner/daily/accept?date=${encodeURIComponent(date)}`) }
export function getPlannerPreferences(accessToken: string) { return request<PlannerPreferences>(accessToken, '/ai/planner/preferences') }
export function updatePlannerPreferences(accessToken: string, preferences: PlannerPreferences) { return request<PlannerPreferences>(accessToken, '/ai/planner/preferences', { method: 'PUT', body: JSON.stringify(preferences) }) }
export function skipCommitmentOccurrence(accessToken: string, commitmentId: string, date: string) { return request<{ commitmentId: string; date: string; skipped: true }>(accessToken, `/context/commitments/${commitmentId}/skip`, { method: 'POST', body: JSON.stringify({ date }) }) }
export function resolveScheduleConflict(accessToken: string, payload: { conflictKey: string; date: string; taskId?: string; commitmentId: string; resolution: 'keep_commitment' | 'keep_task' | 'postpone_task' | 'cancel_task' }) { return request<{ conflictKey: string; lifecycle: 'resolved'; resolution: string }>(accessToken, '/ai/planner/conflicts/resolve', { method: 'POST', body: JSON.stringify(payload) }) }
