import { useEffect, useState } from 'react';
import { Alert, Pressable, Switch, Text, TextInput, View } from 'react-native';
import { getTaskAssistant, refreshTaskAssistant, updateTaskAssistantNotification, updateTaskAssistantSuggestion, type ApiTask, type TaskAssistantState } from '../lib/tasksApi';
import { useTheme } from '../theme/useTheme';

const labelContext = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export function TravelWeatherCard({ token, task }: { token: string; task: ApiTask }) {
  const { theme: { colors } } = useTheme();
  const [state, setState] = useState<TaskAssistantState | null>(null);
  const [expandedSuggestion, setExpandedSuggestion] = useState<string | null>(null);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  useEffect(() => { void getTaskAssistant(token, task.id).then(setState); }, [task.id, task.updatedAt, token]);
  const update = (id: string, payload: { status?: string; quantity?: string }) => updateTaskAssistantSuggestion(token, task.id, id, payload).then(setState);
  const weatherEvidence = state?.travelWeather?.recommendations?.weatherEvidence;
  const recommendationTypes: string[] = state?.travelWeather?.recommendations?.recommendationTypes ?? [];
  const weatherAdvice = recommendationTypes.filter((type) => ['hydration', 'uv_protection', 'umbrella', 'strong_wind'].includes(type)).map((type) => ({ hydration: 'Take water', uv_protection: 'Use sun protection', umbrella: 'Take an umbrella', strong_wind: 'Prepare for strong wind' } as Record<string, string>)[type]).filter(Boolean);

  return <View accessibilityLabel="Task Assistant" className="mx-4 mb-3 rounded-2xl border p-4" style={{ borderColor: colors.border, backgroundColor: colors.card }}>
    <View className="flex-row items-center justify-between"><View className="flex-1"><Text className="font-black" style={{ color: colors.text }}>Task Assistant</Text><Text className="mt-1 text-xs" style={{ color: colors.secondaryText }}>{state ? labelContext(state.context.primaryContext) : 'Detecting context…'}</Text></View><Pressable accessibilityRole="button" onPress={() => void refreshTaskAssistant(token, task.id).then(setState)}><Text className="font-bold" style={{ color: colors.accent }}>Refresh</Text></Pressable></View>
    {state ? <>
      {state.suggestions.length ? <View className="mt-4"><Text className="mb-2 font-black" style={{ color: colors.text }}>Prepare</Text>{state.suggestions.map((item) => { const open = expandedSuggestion === item.id; return <View key={item.id} className="border-b py-2" style={{ borderColor: colors.border }}><View className="flex-row items-center gap-2"><Switch accessibilityLabel={`Complete ${item.title}`} value={item.status === 'completed'} onValueChange={(done) => void update(item.id, { status: done ? 'completed' : 'pending' })} /><Pressable accessibilityRole="button" onPress={() => setExpandedSuggestion(open ? null : item.id)} className="flex-1 flex-row items-center justify-between"><Text className="text-sm font-bold" style={{ color: colors.text }}>{item.title}</Text><Text style={{ color: colors.secondaryText }}>{open ? '⌃' : '›'}</Text></Pressable></View>{open ? <View className="ml-12 mt-2"><Text className="text-xs" style={{ color: colors.secondaryText }}>{item.description}</Text><Text className="mt-1 text-xs" style={{ color: colors.secondaryText }}>Why: {item.reason}</Text>{item.category ? <TextInput accessibilityLabel={`Quantity for ${item.title}`} defaultValue={item.quantity ?? ''} placeholder="Quantity or note" placeholderTextColor={colors.secondaryText} onEndEditing={(event) => void update(item.id, { quantity: event.nativeEvent.text })} className="mt-2 rounded-lg border px-2 py-1" style={{ borderColor: colors.border, color: colors.text }} /> : null}<Pressable accessibilityRole="button" accessibilityLabel={`Dismiss ${item.title}`} onPress={() => void update(item.id, { status: 'dismissed' })} className="mt-2 self-start"><Text className="text-xs font-bold" style={{ color: colors.secondaryText }}>Dismiss</Text></Pressable></View> : null}</View> })}</View> : null}
      {weatherEvidence ? <View className="mt-4"><Text className="font-black" style={{ color: colors.text }}>Weather</Text><Text className="mt-1 text-sm font-bold" style={{ color: colors.text }}>{Math.round(weatherEvidence.feelsLikeC ?? 0)}°C{weatherAdvice.length ? ` · ${weatherAdvice.join(' · ')}` : ''}</Text></View> : null}
      {state.travelWeather?.eligibility?.eligible ? <View className="mt-4"><Text className="font-black" style={{ color: colors.text }}>Travel</Text>{state.travelWeather.route?.durationMinutes ? <Text className="mt-1 text-sm font-bold" style={{ color: colors.text }}>🚗 {state.travelWeather.route.durationMinutes} min{state.travelWeather.recommendedDepartureTime ? ` · leave by ${new Date(state.travelWeather.recommendedDepartureTime).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}` : ''}</Text> : <><Text className="mt-1 text-sm font-bold" style={{ color: colors.text }}>Travel time unavailable</Text>{state.travelWeather.routeUnavailableReason === 'origin_unavailable' ? <><Text className="mt-1 text-xs" style={{ color: colors.secondaryText }}>Set Home to calculate departure.</Text><Pressable accessibilityRole="button" onPress={() => Alert.alert('Set travel origin', 'Open Settings → Saved Places and add a Home place, or enable location access.')} className="mt-2 self-start rounded-lg px-3 py-2" style={{ backgroundColor: colors.accentSoft }}><Text className="text-xs font-bold" style={{ color: colors.accentInk }}>Set Home</Text></Pressable></> : null}</>}</View> : null}
      {state.timeline.length ? <View className="mt-4"><Text className="font-black" style={{ color: colors.text }}>Timeline</Text>{state.timeline.map((stage) => <View key={stage.id} className="mt-2"><Text className="text-sm font-bold" style={{ color: colors.text }}>{stage.scheduledAt ? new Date(stage.scheduledAt).toLocaleString([], { weekday: 'short', hour: 'numeric', minute: '2-digit' }) : 'Upcoming'} · {stage.title}</Text></View>)}</View> : null}
      {state.contextualNotifications.length ? <View className="mt-4"><Pressable accessibilityRole="button" onPress={() => setNotificationsOpen((value) => !value)} className="flex-row items-center justify-between"><Text className="font-black" style={{ color: colors.text }}>Notifications</Text><Text className="text-xs font-bold" style={{ color: colors.secondaryText }}>{state.contextualNotifications.length} scheduled {notificationsOpen ? '⌃' : '›'}</Text></Pressable>{notificationsOpen ? state.contextualNotifications.map((notification) => <View key={notification.id} className="mt-2 flex-row items-center justify-between"><Text className="flex-1 text-xs" style={{ color: colors.secondaryText }}>{new Date(notification.scheduledAt).toLocaleString([], { weekday: 'short', hour: 'numeric', minute: '2-digit' })} · {notification.body}</Text><Pressable accessibilityRole="button" onPress={() => void updateTaskAssistantNotification(token, task.id, notification.id, { status: 'dismissed' }).then(setState)}><Text className="text-xs font-bold" style={{ color: colors.accent }}>Disable</Text></Pressable></View>) : null}</View> : null}
    </> : null}
  </View>;
}
