import React from 'react'
import { AppLayout, DangerButton, PageHeader, SectionCard, TopActionBar, type SidebarNavHandlers } from '../components/layout'
import { SavedPlacesSection } from '../features/context/components/SavedPlacesSection'
import { WeeklyCommitmentsSection } from '../features/context/components/WeeklyCommitmentsSection'
import { useAuth } from '../hooks/useAuth'
import { useLanguage } from '../i18n/LanguageContext'
import { useTheme } from '../theme/ThemeContext'
import { AccountSettings, AiSettings, GeneralSettings } from '../features/settings/SettingsHubSections'
import { WeatherTravelSettings } from '../features/settings/WeatherTravelSettings'
import { loadSharedSoundPreferences, saveSharedSoundPreferences, type SharedSoundPreferences } from '../lib/sharedFocusSounds'

type SettingsScreenProps = SidebarNavHandlers & { accessToken?: string; onSignOut?: () => void }
function Group({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-6 space-y-3"><div className="px-1"><h2 className="text-base font-black tracking-tight">{title}</h2><p className="mt-1 text-sm text-[var(--bp-muted)]">{description}</p></div>{children}</section> }
function SideNav({ t }: { t: ReturnType<typeof useLanguage>['t'] }) { const items = [{ id: 'account', key: 'account' }, { id: 'preferences', key: 'preferences' }, { id: 'notifications', key: 'notifications' }, { id: 'ai-planner', key: 'planner' }, { id: 'integrations', key: 'integrations' }, { id: 'privacy', key: 'privacy' }] as const; return <nav aria-label={t('settings.title')} className="hidden w-40 shrink-0 lg:block"><div className="sticky top-6 space-y-1 text-sm">{items.map((item) => <a key={item.id} href={`#${item.id}`} className="block rounded-lg px-3 py-2 font-bold text-[var(--bp-muted)] hover:bg-[var(--bp-accent-soft)] hover:text-[var(--bp-text)]">{t(`settings.${item.key}`)}</a>)}</div></nav> }

export default function SettingsScreen({ accessToken, onSignOut, ...nav }: SettingsScreenProps) {
  const { user, updateUser } = useAuth(); const { toggleLanguage, language, t } = useLanguage(); const { mode, toggleTheme } = useTheme(); const timezone = user?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone
  const [sharedSounds, setSharedSounds] = React.useState<SharedSoundPreferences>(() => loadSharedSoundPreferences())
  const updateSounds = (next: SharedSoundPreferences) => { setSharedSounds(next); saveSharedSoundPreferences(next) }
  return <AppLayout active="settings" {...nav}><PageHeader title={t('settings.title')} subtitle={t('settings.subtitle')} toolbar={<TopActionBar pageOnly onOpenNotifications={nav.onNavigateNotifications} onSignOut={onSignOut} />} /><div className="mx-auto flex max-w-5xl gap-8 pb-12"><SideNav t={t} /><main className="min-w-0 flex-1 space-y-8">
    <Group id="account" title={t('settings.account')} description={t('settings.accountDesc')}><AccountSettings user={user} token={accessToken} onUpdated={updateUser} /><SectionCard><div className="flex items-center justify-between gap-4"><div><h3 className="text-sm font-black">{t('settings.signOut')}</h3><p className="mt-1 text-xs text-[var(--bp-muted)]">{t('settings.signOutDesc')}</p></div><DangerButton onClick={onSignOut}>{t('settings.signOut')}</DangerButton></div></SectionCard></Group>
    <Group id="preferences" title={t('settings.preferences')} description={t('settings.preferencesDesc')}><GeneralSettings variant="preferences" mode={mode} language={language} timezone={timezone} onTheme={toggleTheme} onLanguage={toggleLanguage} /></Group>
    <Group id="shared-focus-sounds" title={t('settingsUi.sharedSounds')} description={t('settingsUi.sharedSounds')}><div className="space-y-4 rounded-2xl border border-[var(--bp-border)] bg-[var(--bp-surface)] p-4 shadow-xl"><label className="flex items-center justify-between gap-3 font-bold"><span>{t('settingsUi.enableSounds')}</span><input type="checkbox" checked={sharedSounds.enabled} onChange={e => updateSounds({ ...sharedSounds, enabled: e.target.checked })} /></label><label className="block text-sm font-bold">{t('settingsUi.masterVolume')}<input aria-label={t('settingsUi.masterVolume')} className="mt-2 w-full" type="range" min="0" max="1" step=".05" value={sharedSounds.volume} onChange={e => updateSounds({ ...sharedSounds, volume: Number(e.target.value) })} /></label><div className="grid gap-2 sm:grid-cols-2">{Object.entries(sharedSounds.events).map(([event, checked]) => <label key={event} className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={checked} onChange={e => updateSounds({ ...sharedSounds, events: { ...sharedSounds.events, [event]: e.target.checked } })} />{event}</label>)}</div><button className="rounded-xl border px-4 py-2 font-bold" onClick={() => { updateSounds(sharedSounds); const audio = new Audio('/focus-complete.mp3'); audio.volume = sharedSounds.volume; void audio.play().catch(() => undefined) }}>{t('settingsUi.testSound')}</button></div></Group>
    <Group id="notifications" title={t('settings.notifications')} description={t('settings.notificationsDesc')}><GeneralSettings variant="notifications" token={accessToken} onNotifications={nav.onNavigateNotifications} /></Group>
    <Group id="ai-planner" title={t('settings.planner')} description={t('settings.plannerDesc')}><AiSettings token={accessToken} onOpen={nav.onNavigatePlanner} /><details className="group rounded-2xl border border-[var(--bp-border)] bg-[var(--bp-surface)] shadow-xl"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-4 font-black"><span>{t('settingsUi.advanced')}</span><span className="text-xs font-bold text-[var(--bp-muted)] group-open:hidden">{t('settingsUi.showTechnical')}</span><span className="hidden text-xs font-bold text-[var(--bp-muted)] group-open:inline">{t('settingsUi.hideTechnical')}</span></summary><div className="space-y-4 border-t border-[var(--bp-border)] p-4"><p className="text-sm text-[var(--bp-muted)]">{t('settingsUi.advancedDesc')}</p><SavedPlacesSection accessToken={accessToken} /><WeeklyCommitmentsSection accessToken={accessToken} /></div></details></Group>
    <Group id="integrations" title={t('settings.integrations')} description={t('settings.integrationsDesc')}><WeatherTravelSettings token={accessToken} /></Group>
    <Group id="privacy" title={t('settings.privacy')} description={t('settings.privacyDesc')}><GeneralSettings variant="privacy" token={accessToken} onDeleted={() => void onSignOut?.()} /></Group>
  </main></div></AppLayout>
}
