import { AppLayout, DangerButton, PageHeader, SectionCard, TopActionBar, type SidebarNavHandlers } from '../components/layout'
import { SavedPlacesSection } from '../features/context/components/SavedPlacesSection'
import { WeeklyCommitmentsSection } from '../features/context/components/WeeklyCommitmentsSection'
import { useAuth } from '../hooks/useAuth'
import { useLanguage } from '../i18n/LanguageContext'
import { useTheme } from '../theme/ThemeContext'
import { AccountSettings, AiSettings, GeneralSettings } from '../features/settings/SettingsHubSections'
import { WeatherTravelSettings } from '../features/settings/WeatherTravelSettings'
import { GoogleCalendarSettings } from '../features/settings/GoogleCalendarSettings'

type SettingsScreenProps = SidebarNavHandlers & { accessToken?: string; onSignOut?: () => void }
function Group({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-6 space-y-3"><div className="px-1"><h2 className="text-base font-black tracking-tight">{title}</h2><p className="mt-1 text-sm text-[var(--bp-muted)]">{description}</p></div>{children}</section> }
function SideNav() { return <nav aria-label="Settings sections" className="hidden w-40 shrink-0 lg:block"><div className="sticky top-6 space-y-1 text-sm">{['Account','Preferences','Notifications','AI Planner','Integrations','Privacy'].map((name) => <a key={name} href={`#${name.toLowerCase().replace(' ', '-')}`} className="block rounded-lg px-3 py-2 font-bold text-[var(--bp-muted)] hover:bg-[var(--bp-accent-soft)] hover:text-[var(--bp-text)]">{name}</a>)}</div></nav> }

export default function SettingsScreen({ accessToken, onSignOut, ...nav }: SettingsScreenProps) {
  const { user, updateUser } = useAuth(); const { toggleLanguage, language } = useLanguage(); const { mode, toggleTheme } = useTheme(); const timezone = user?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone
  return <AppLayout active="settings" {...nav}><PageHeader title="Settings" subtitle="A calmer way to shape BeePlan around you" toolbar={<TopActionBar pageOnly onOpenNotifications={nav.onNavigateNotifications} onSignOut={onSignOut} />} /><div className="mx-auto flex max-w-5xl gap-8 pb-12"><SideNav /><main className="min-w-0 flex-1 space-y-8">
    <Group id="account" title="Account" description="Your identity and sign-in details."><AccountSettings user={user} token={accessToken} onUpdated={updateUser} /><SectionCard><div className="flex items-center justify-between gap-4"><div><h3 className="text-sm font-black">Sign out</h3><p className="mt-1 text-xs text-[var(--bp-muted)]">End your session on this device.</p></div><DangerButton onClick={onSignOut}>Sign out</DangerButton></div></SectionCard></Group>
    <Group id="preferences" title="Preferences" description="Choose how BeePlan looks and fits into your day."><GeneralSettings variant="preferences" mode={mode} language={language} timezone={timezone} onTheme={toggleTheme} onLanguage={toggleLanguage} /></Group>
    <Group id="notifications" title="Notifications" description="Control the updates you want to hear about."><GeneralSettings variant="notifications" token={accessToken} onNotifications={nav.onNavigateNotifications} /></Group>
    <Group id="ai-planner" title="AI Planner" description="The few choices that make planning feel like your own."><AiSettings token={accessToken} onOpen={nav.onNavigatePlanner} /><details className="group rounded-2xl border border-[var(--bp-border)] bg-[var(--bp-surface)] shadow-xl"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-4 font-black"><span>Advanced Planner Settings</span><span className="text-xs font-bold text-[var(--bp-muted)] group-open:hidden">Show technical options</span><span className="hidden text-xs font-bold text-[var(--bp-muted)] group-open:inline">Hide technical options</span></summary><div className="space-y-4 border-t border-[var(--bp-border)] p-4"><p className="text-sm text-[var(--bp-muted)]">Less frequently changed planner controls and permanent planning knowledge.</p><SavedPlacesSection accessToken={accessToken} /><WeeklyCommitmentsSection accessToken={accessToken} /></div></details></Group>
    <Group id="integrations" title="Integrations" description="Connect the services BeePlan uses to plan with better context."><GoogleCalendarSettings token={accessToken} /><WeatherTravelSettings token={accessToken} /><div className="rounded-2xl border border-[var(--bp-border)] bg-[var(--bp-surface)] p-4 shadow-xl"><div className="flex items-center justify-between gap-4"><div><h3 className="text-sm font-black">Future integrations</h3><p className="mt-1 text-xs text-[var(--bp-muted)]">More useful connections are on the way.</p></div><span className="text-xs font-bold text-[var(--bp-muted)]">Coming soon</span></div></div></Group>
    <Group id="privacy" title="Privacy" description="Review permissions and connected access at a glance."><GeneralSettings variant="privacy" token={accessToken} onDeleted={() => void onSignOut?.()} /></Group>
  </main></div></AppLayout>
}
