import { Activity, CalendarDays, Clock3, Sparkles, Target, TriangleAlert } from 'lucide-react'
import { AppLayout, DirectionalChevron, PageHeader, SectionCard, TopActionBar, type SidebarNavHandlers } from '../components/layout'
import { useLanguage } from '../i18n/LanguageContext'
import { useTheme } from '../theme/ThemeContext'
import type { DashboardRecommendation, TodayDashboard } from '../lib/tasksApi'
import { focusParentLabel, focusPrimaryTitle } from '../lib/focusDisplay'

type Props = SidebarNavHandlers & { dashboard: TodayDashboard | null; summaryLoading: boolean; summaryError: string; onRetrySummary?: () => void; onViewReminders: () => void; onViewTasks: () => void; onCreateTask?: () => void; onCreateTaskAi?: () => void; onCreateReminder?: () => void; onViewTaskDetails?: (taskId: string) => void; onSignOut?: () => void; onStartFocus: (recommendation: DashboardRecommendation) => Promise<void>; onContinueFocus: () => void }

export default function TasksDashboardScreen({ dashboard, summaryLoading, summaryError, onRetrySummary, onViewTasks, onSignOut, onStartFocus, onContinueFocus, ...nav }: Props) {
  const { t, toggleLanguage } = useLanguage(); const { mode, toggleTheme } = useTheme(); const loading = summaryLoading && !dashboard
  return <AppLayout active="dashboard" {...nav} onNavigateTasks={onViewTasks} panelTitle="Today" panelCaption="Your next best action." panelPercent={dashboard?.progress.percent ?? 0}>
    <PageHeader title={t('taskUi.dashboard.title')} subtitle="" toolbar={<TopActionBar themeMode={mode} onToggleTheme={toggleTheme} languageLabel={t('common.languageToggle')} onToggleLanguage={toggleLanguage} onOpenNotifications={nav.onNavigateNotifications} onSignOut={onSignOut} />} />
    {summaryError ? <SectionCard className="mb-4 border-red-500/40 shadow-lg shadow-red-950/10"><p className="text-sm text-red-300">{summaryError}</p><button className="mt-2 text-sm font-bold text-[var(--bp-accent)] hover:underline" onClick={onRetrySummary}>Retry dashboard</button></SectionCard> : null}
    {loading ? <Skeleton /> : dashboard ? <main className="mx-auto max-w-5xl space-y-5"><Greeting dashboard={dashboard} /><KpiRow dashboard={dashboard} /><Hero dashboard={dashboard} onStart={onStartFocus} onContinue={onContinueFocus} /><Timeline dashboard={dashboard} onOpenPlanner={nav.onNavigatePlanner} />{dashboard.suggestions.length ? <Suggestions dashboard={dashboard} /> : null}<div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Progress dashboard={dashboard} /><Tomorrow dashboard={dashboard} /></div>{dashboard.locationContext ? <SectionCard><h2 className="text-sm font-bold">{dashboard.locationContext.label}</h2></SectionCard> : null}</main> : <Empty onViewTasks={onViewTasks} />}
  </AppLayout>
}

function Greeting({ dashboard }: { dashboard: TodayDashboard }) { const tone: Record<string, string> = { success: 'text-emerald-400', positive: 'text-emerald-400', warning: 'text-amber-400', danger: 'text-orange-400' }; return <section className="px-1 py-1"><div className="flex items-center gap-2"><Sparkles aria-hidden="true" size={18} strokeWidth={1.75} className="text-[var(--bp-accent)]" /><h1 className="text-xl font-black tracking-tight sm:text-2xl">{dashboard.greeting}</h1></div><p className={`mt-1 text-sm font-bold ${tone[dashboard.dailyStatus.statusTone]}`}>{dashboard.dailyStatus.status}</p><div className="mt-2 space-y-0.5 text-sm leading-relaxed text-slate-400">{dashboard.dailyStatus.summaryLines.map((line) => <p key={line}>{line}</p>)}</div></section> }

function KpiRow({ dashboard }: { dashboard: TodayDashboard }) { const p = dashboard.progress; const priority = dashboard.whyNow.find((reason) => reason.code === 'high_priority'); const tomorrow = dashboard.tomorrowPreview; return <section aria-label="Today at a glance" className="grid gap-3 sm:grid-cols-3"><SectionCard className="group overflow-hidden bg-gradient-to-br from-[var(--bp-surface)] to-[var(--bp-accent)]/10 p-4 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center gap-3"><div aria-hidden="true" className="grid h-14 w-14 place-items-center rounded-full border-2 border-[var(--bp-accent)]/40 bg-[var(--bp-accent)]/10 text-[var(--bp-accent)]"><Target size={20} strokeWidth={1.75} /></div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.13em] text-[var(--bp-accent)]">Focus Today</p><p aria-label={`${formatMinutes(p.focusMinutes)} focused today`} className="mt-0.5 text-3xl font-black leading-none tracking-tight text-[var(--bp-text)]">{formatMinutes(p.focusMinutes)}</p><p className="mt-1 text-xs text-slate-400">Focused today</p></div></div></SectionCard><SectionCard className="bg-gradient-to-br from-[var(--bp-surface)] to-amber-400/10 p-4 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center gap-2"><span aria-hidden="true" className="grid h-10 w-10 place-items-center rounded-full bg-amber-400/10 text-amber-300"><TriangleAlert size={20} strokeWidth={1.75} /></span><p className="text-xs font-bold uppercase tracking-[.13em] text-amber-300">Priority</p></div><p className="mt-2 text-lg font-black">{priority ? 'Attention needed' : dashboard.dailyStatus.status}</p><p className="mt-1 text-xs text-slate-400">{priority ? 'A high-priority item is ready' : 'Today’s attention signal'}</p></SectionCard><SectionCard className="bg-gradient-to-br from-[var(--bp-surface)] to-sky-400/10 p-4 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between gap-2"><div><div className="flex items-center gap-2"><span aria-hidden="true" className="grid h-10 w-10 place-items-center rounded-full bg-sky-400/10 text-sky-300"><CalendarDays size={20} strokeWidth={1.75} /></span><p className="text-xs font-bold uppercase tracking-[.13em] text-sky-300">Tomorrow</p></div><p className="mt-2 text-lg font-black">≈{formatMinutes(tomorrow.estimatedWorkMinutes)} planned</p><p className="mt-1 text-xs text-slate-400">{tomorrow.dueWorkUnits} due {tomorrow.dueWorkUnits === 1 ? 'item' : 'items'}</p></div>{tomorrow.overloadStatus === 'overloaded' ? <span className="rounded-full bg-amber-400/15 px-2 py-1 text-[10px] font-black uppercase tracking-wide text-amber-300">Busy</span> : null}</div></SectionCard></section> }

function Hero({ dashboard, onStart, onContinue }: { dashboard: TodayDashboard; onStart: (item: DashboardRecommendation) => Promise<void>; onContinue: () => void }) { const active = dashboard.activeFocus; const item = active ?? dashboard.recommendation; if (!item) return <SectionCard className="bg-gradient-to-br from-[var(--bp-surface)] to-[var(--bp-accent)]/5 py-7"><Target aria-hidden="true" size={18} strokeWidth={1.75} className="text-[var(--bp-accent)]" /><h2 className="mt-2 text-xl font-black">Your day is clear</h2><p className="text-sm text-slate-400">There is no Focus recommendation right now.</p></SectionCard>; const title = focusPrimaryTitle(item); const parent = focusParentLabel(item); const minutes = 'plannedMinutes' in item ? item.plannedMinutes : item.estimatedMinutes; return <SectionCard className="overflow-hidden border-[var(--bp-accent)]/30 bg-gradient-to-br from-[var(--bp-surface)] via-[var(--bp-surface)] to-[var(--bp-accent)]/10 p-5 shadow-xl shadow-black/10"><div className="flex items-center gap-2 text-[var(--bp-accent)]"><Target aria-hidden="true" size={18} strokeWidth={1.75} /><p className="text-xs font-bold uppercase tracking-[.2em]">Do this now</p></div><h2 className="mt-3 text-2xl font-black leading-tight tracking-tight sm:text-3xl">{title}</h2>{parent ? <p className="mt-2 text-sm text-slate-400">{parent}</p> : null}<div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold text-slate-300">{minutes ? <span className="rounded-full bg-white/5 px-3 py-1.5">{minutes} min focus</span> : null}{'status' in item ? <span className="rounded-full bg-white/5 px-3 py-1.5 capitalize">{item.status}</span> : null}</div>{dashboard.whyNow.length ? <div className="mt-5"><p className="text-xs font-bold uppercase tracking-[.15em] text-slate-400">Why this</p><div className="mt-2 flex flex-wrap gap-2">{dashboard.whyNow.map((reason) => <span key={reason.code} className="rounded-full bg-[var(--bp-accent)]/15 px-3 py-1.5 text-xs font-semibold text-[var(--bp-accent)]">{reason.label}{reason.value ? ` · ${reason.value}` : ''}</span>)}</div></div> : null}<button type="button" onClick={() => { if (active) onContinue(); else void onStart(item as DashboardRecommendation) }} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--bp-accent)] px-5 py-3.5 text-base font-black text-slate-950 shadow-lg shadow-[var(--bp-accent)]/15 transition duration-200 hover:-translate-y-0.5 hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--bp-accent)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--bp-surface)] active:translate-y-0"><Target aria-hidden="true" size={16} strokeWidth={1.75} />{active ? 'Continue Focus' : 'Start Focus'}</button></SectionCard> }

function Timeline({ dashboard, onOpenPlanner }: { dashboard: TodayDashboard; onOpenPlanner?: () => void }) { if (!dashboard.timeline.length) return <SectionCard><div className="flex items-center gap-2"><Clock3 aria-hidden="true" size={18} strokeWidth={1.75} className="text-slate-400" /><h2 className="text-base font-black">Today timeline</h2></div><p className="mt-2 text-sm text-slate-400">No accepted plan is scheduled for today.</p>{onOpenPlanner ? <button className="mt-3 text-sm font-bold text-[var(--bp-accent)] hover:underline" onClick={onOpenPlanner}>Open planner</button> : null}</SectionCard>; const now = Date.now(); const nextIndex = dashboard.timeline.findIndex((block) => new Date(block.startTime).getTime() > now); return <SectionCard className="shadow-sm"><div className="flex items-center gap-2"><Clock3 aria-hidden="true" size={18} strokeWidth={1.75} className="text-slate-400" /><h2 className="text-base font-black">Today timeline</h2></div><div className="mt-4">{dashboard.timeline.map((block, index) => { const start = new Date(block.startTime).getTime(); const end = block.endTime ? new Date(block.endTime).getTime() : Infinity; const marker = start <= now && now < end ? 'NOW' : index === nextIndex ? 'NEXT' : 'LATER'; const current = marker === 'NOW' || (dashboard.timeline.length === 1 && index === 0); return <div key={block.id} className={`group relative flex gap-4 pb-5 last:pb-0 ${current ? 'rounded-xl bg-[var(--bp-accent)]/7 p-3' : 'px-1'} transition hover:bg-white/[.025]`}><div className="flex w-4 flex-col items-center"><span className={`mt-1 h-3 w-3 rounded-full ring-4 ${current ? 'bg-[var(--bp-accent)] ring-[var(--bp-accent)]/15' : 'bg-slate-500 ring-slate-500/10'}`} />{index < dashboard.timeline.length - 1 ? <span className="mt-2 w-px flex-1 bg-[var(--bp-border)]" /> : null}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-black tracking-[.18em] text-[var(--bp-accent)]">{current && dashboard.timeline.length === 1 ? 'CURRENT' : marker}</span><span className="text-xs text-slate-400">{formatRange(block.startTime, block.endTime, dashboard.timezone)}</span></div><p className="mt-1 text-sm font-bold">{block.title}</p><p className="text-xs capitalize text-slate-400">{block.type} · {block.status}</p>{current && dashboard.timeline.length === 1 ? <p className="mt-2 text-xs text-slate-400">Waiting for the next scheduled block…</p> : null}</div></div> })}</div></SectionCard> }

function Progress({ dashboard }: { dashboard: TodayDashboard }) { const p = dashboard.progress; if (!p.totalWorkUnits) return <SectionCard><div className="flex items-center gap-2"><Activity aria-hidden="true" size={18} strokeWidth={1.75} className="text-slate-400" /><h2 className="text-base font-black">Today’s Activity</h2></div><div className="mt-3 flex items-baseline gap-2"><strong className="text-2xl text-[var(--bp-accent)]">{formatMinutes(p.focusMinutes)}</strong><span className="text-sm text-slate-400">Focus</span></div><p className="mt-1 text-sm text-slate-400">No scheduled work today.</p></SectionCard>; return <SectionCard><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Activity aria-hidden="true" size={18} strokeWidth={1.75} className="text-slate-400" /><h2 className="text-base font-black">Today’s progress</h2></div><p className="mt-1 text-xs text-slate-400"><span>{p.completedWorkUnits}/{p.totalWorkUnits} units</span> complete</p></div><strong className="text-2xl text-[var(--bp-accent)]">{p.percent}%</strong></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-[var(--bp-bg)]"><div className="h-full rounded-full bg-[var(--bp-accent)] transition-all duration-700" style={{ width: `${p.percent}%` }} /></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-slate-400"><span>{formatMinutes(p.focusMinutes)} Focus</span><span>{formatMinutes(p.remainingEstimatedMinutes)} remaining</span></div></SectionCard> }

function Tomorrow({ dashboard }: { dashboard: TodayDashboard }) { const t = dashboard.tomorrowPreview; const overloaded = t.overloadStatus === 'overloaded'; return <SectionCard className={overloaded ? 'border-red-500/30 bg-gradient-to-r from-red-500/10 to-orange-500/5' : ''}><div className="flex items-center gap-2"><CalendarDays aria-hidden="true" size={18} strokeWidth={1.75} className="text-sky-300" /><h2 className="text-base font-black">Tomorrow</h2></div>{overloaded ? <><p className="mt-2 text-sm font-bold text-orange-300">Heavy workload tomorrow</p><span className="sr-only">Tomorrow is overloaded.</span></> : null}<p className="mt-2 text-sm text-slate-300">≈{formatMinutes(t.estimatedWorkMinutes)} planned · {t.dueWorkUnits} due items · {t.highPriorityItems} high priority</p>{t.capacityMinutes !== null ? <p className="mt-1 text-xs text-slate-400">{formatMinutes(t.capacityMinutes)} planned capacity</p> : null}{overloaded ? <p className="mt-2 text-xs text-slate-400">Review your plan tonight.</p> : null}</SectionCard> }

function Suggestions({ dashboard }: { dashboard: TodayDashboard }) { return <SectionCard><h2 className="text-base font-black">Suggestions</h2>{dashboard.suggestions.map((suggestion) => <div key={suggestion.id} className="mt-3"><p className="font-semibold">{suggestion.title}</p><p className="text-sm text-slate-400">{suggestion.explanation}</p></div>)}</SectionCard> }
function Empty({ onViewTasks }: { onViewTasks: () => void }) { return <SectionCard className="py-8 text-center"><h2 className="text-lg font-black">Nothing planned yet</h2><p className="mt-2 text-sm text-slate-400">Add a task or accept a daily plan to see your guided day here.</p><button className="mt-4 text-sm font-bold text-[var(--bp-accent)] hover:underline" onClick={onViewTasks}>View tasks <DirectionalChevron direction="forward" className="inline h-4 w-4" /></button></SectionCard> }
function Skeleton() { return <div className="mx-auto max-w-5xl space-y-5 animate-pulse"><div className="grid gap-4 xl:grid-cols-2"><div className="h-36 rounded-2xl bg-[var(--bp-surface)]" /><div className="h-72 rounded-2xl bg-[var(--bp-surface)]" /></div><div className="h-52 rounded-2xl bg-[var(--bp-surface)]" /><div className="h-32 rounded-2xl bg-[var(--bp-surface)]" /></div> }
function formatMinutes(minutes: number) { const hours = Math.floor(Math.max(0, minutes) / 60); const rest = Math.max(0, minutes) % 60; return hours ? `${hours}h${rest ? ` ${rest}m` : ''}` : `${rest}m` }
function formatRange(start: string, end: string | null, timezone: string) { const options: Intl.DateTimeFormatOptions = { hour: 'numeric', minute: '2-digit', timeZone: timezone }; const format = (value: string) => new Intl.DateTimeFormat(undefined, options).format(new Date(value)); return end ? `${format(start)}–${format(end)}` : `${format(start)}–now` }
