import { useEffect, useState } from 'react'
import { ActivityIndicator, Image, Modal, Pressable, Text, View } from 'react-native'
import * as FileSystem from 'expo-file-system/legacy'
import * as Sharing from 'expo-sharing'
import { useAudioPlayer, useAudioPlayerStatus } from 'expo-audio'
import { VideoView, useVideoPlayer } from 'expo-video'
import { getAuthToken } from '../../lib/authToken'
import { API_BASE_URL, type Capsule } from './api'
import { useTheme } from '../../theme/useTheme'
type Attachment = NonNullable<Capsule['attachments']>[number]
const format = (seconds: number) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`

export function UnlockedAttachment({ capsuleId, attachment }: { capsuleId: string; attachment: Attachment }) {
  const { theme } = useTheme(); const [uri, setUri] = useState<string>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [full, setFull] = useState(false)
  const audio = useAudioPlayer(attachment.type === 'audio' ? uri ?? null : null); const audioStatus = useAudioPlayerStatus(audio); const video = useVideoPlayer(attachment.type === 'video' ? uri ?? null : null, p => { p.loop = false })
  useEffect(() => () => { audio.pause(); audio.release(); video.release() }, [audio, video])
  async function load() { if (uri) return uri; setLoading(true); setError(''); try { const target = `${FileSystem.cacheDirectory}capsule-${attachment.id}-${attachment.fileName}`; const result = await FileSystem.downloadAsync(`${API_BASE_URL}/time-capsules/${capsuleId}/attachments/${attachment.id}/content`, target, { headers: { Authorization: `Bearer ${getAuthToken()}` } }); if (result.status !== 200) throw new Error('Could not load this attachment.'); setUri(result.uri); return result.uri } catch (e) { setError(e instanceof Error ? e.message : 'Could not load this attachment.'); return undefined } finally { setLoading(false) } }
  if (attachment.type === 'image') return <View style={{ marginTop: 12 }}><Pressable accessibilityLabel={`View ${attachment.fileName}`} onPress={() => void load().then(v => v && setFull(true))} style={{ minHeight: 110, borderRadius: 14, backgroundColor: theme.colors.surface, alignItems: 'center', justifyContent: 'center' }}>{loading ? <ActivityIndicator /> : uri ? <Image source={{ uri }} style={{ width: '100%', height: 180, borderRadius: 14, resizeMode: 'contain' }} /> : <Text style={{ color: theme.colors.text }}>Image · {attachment.fileName}</Text>}</Pressable>{error ? <Text style={{ color: theme.colors.error }}>{error}</Text> : null}<Modal visible={full} animationType="fade"><View style={{ flex: 1, backgroundColor: '#000', paddingTop: 48 }}><Pressable onPress={() => setFull(false)} style={{ padding: 18 }}><Text style={{ color: '#fff', fontWeight: '800' }}>Close</Text></Pressable>{uri ? <Image source={{ uri }} style={{ flex: 1, width: '100%', resizeMode: 'contain' }} /> : null}</View></Modal></View>
  if (attachment.type === 'video') return <View style={{ marginTop: 12, padding: 14, borderRadius: 14, backgroundColor: theme.colors.surface }}><Text style={{ color: theme.colors.text, fontWeight: '800' }}>Video · {attachment.fileName}</Text><Text style={{ color: theme.colors.secondaryText, marginTop: 4 }}>{(attachment.sizeBytes / 1024 / 1024).toFixed(2)} MB{attachment.durationSeconds ? ` · ${format(attachment.durationSeconds)}` : ''}</Text>{uri ? <VideoView player={video} style={{ width: '100%', height: 220, marginTop: 10 }} nativeControls allowsFullscreen /> : <Pressable onPress={() => void load()} style={{ marginTop: 10 }}><Text style={{ color: theme.colors.primary, fontWeight: '800' }}>{loading ? 'Loading…' : 'Preview / Play'}</Text></Pressable>}{error ? <Text style={{ color: theme.colors.error }}>{error}</Text> : null}</View>
  if (attachment.type === 'audio') return <View style={{ marginTop: 12, padding: 14, borderRadius: 14, backgroundColor: theme.colors.surface }}><Pressable onPress={() => void load().then(v => { if (v) audioStatus.playing ? audio.pause() : audio.play() })}><Text style={{ color: theme.colors.text, fontWeight: '800' }}>{audioStatus.playing ? 'Pause' : 'Play'} voice memory</Text></Pressable><Text style={{ color: theme.colors.secondaryText }}>{format(audioStatus.currentTime ?? 0)} / {format(audioStatus.duration ?? attachment.durationSeconds ?? 0)}</Text>{error ? <Text style={{ color: theme.colors.error }}>{error}</Text> : null}</View>
  return <View style={{ marginTop: 12, padding: 14, borderRadius: 14, backgroundColor: theme.colors.surface }}><Text style={{ color: theme.colors.text }}>File · {attachment.fileName} · {(attachment.sizeBytes / 1024).toFixed(0)} KB</Text><Pressable onPress={() => void load().then(async v => { if (v && await Sharing.isAvailableAsync()) await Sharing.shareAsync(v) })} style={{ marginTop: 8 }}><Text style={{ color: theme.colors.primary, fontWeight: '800' }}>{loading ? 'Loading…' : 'Open'}</Text></Pressable>{error ? <Text style={{ color: theme.colors.error }}>{error}</Text> : null}</View>
}
