import { BadGatewayException, Injectable, Logger, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHash } from 'crypto';
import OpenAI from 'openai';
import { desc, eq, sql } from 'drizzle-orm';
import { DatabaseService } from '../db/database.service';
import { errorAnalyses, errorGroups, errorGroupUsers, errorOccurrences } from '../db/schema';
import { ErrorSanitizerService } from '../observability/sanitization/error-sanitizer.service';
import { AdminAuditLogService } from '../admin/audit/admin-audit.service';
import { parseAnalysisResponse, responseShape, type AnalysisOutput } from './admin-error-analysis.schemas';

@Injectable()
export class AdminErrorAnalysisService {
  private readonly client: OpenAI | null; private readonly model: string | null;
  private readonly logger = new Logger(AdminErrorAnalysisService.name);
  constructor(private readonly database: DatabaseService, private readonly config: ConfigService, private readonly sanitizer: ErrorSanitizerService, private readonly audit: AdminAuditLogService) { const apiKey = config.get<string>('QWEN_API_KEY'); const baseURL = config.get<string>('QWEN_BASE_URL'); this.model = config.get<string>('ADMIN_ERROR_ANALYSIS_MODEL') ?? config.get<string>('QWEN_MODEL') ?? null; this.client = apiKey && baseURL ? new OpenAI({ apiKey, baseURL }) : null; }
  async list(errorGroupId: string) { const rows = await this.database.db.select().from(errorAnalyses).where(eq(errorAnalyses.errorGroupId, errorGroupId)).orderBy(desc(errorAnalyses.createdAt)); return rows.map((row) => ({ ...row, createdAt: row.createdAt.toISOString() })); }
  async analyze(actorId: string, errorGroupId: string, reanalyze = false) {
    const context = await this.context(errorGroupId); const contextHash = createHash('sha256').update(JSON.stringify(context)).digest('hex');
    const [existing] = await this.database.db.select().from(errorAnalyses).where(eq(errorAnalyses.contextHash, contextHash)).orderBy(desc(errorAnalyses.createdAt)).limit(1);
    if (existing && !reanalyze) { await this.audit.write({ actorUserId: actorId, action: 'error.ai_analysis_reused', targetType: 'error_group', targetId: errorGroupId, metadata: { analysisId: existing.id, model: existing.model, contextHash } }); return { ...existing, createdAt: existing.createdAt.toISOString(), reused: true }; }
    if (!this.client || !this.model) throw new ServiceUnavailableException('AI analysis is not configured.');
    let response: string | null = null;
    try { const completion = await this.client.chat.completions.create({ model: this.model, response_format: { type: 'json_object' }, max_tokens: 1200, messages: [{ role: 'system', content: 'You are a BeePlan developer diagnostic assistant. Analyze only the supplied sanitized error evidence. Do not invent facts, request secrets, output code patches, or imply any system change. Return one JSON object only (no Markdown) with exact fields likelyCause(string), evidence(string[]), investigationSteps(string[]), suggestedFix(string), likelyModules(string[]), confidence(low|medium|high), limitations(string[]).' }, { role: 'user', content: JSON.stringify(context) }] }); response = completion.choices[0]?.message?.content ?? null; if (process.env.NODE_ENV !== 'production') this.logger.debug(`Admin AI response diagnostics ${JSON.stringify({ model: this.model, finishReason: completion.choices[0]?.finish_reason, shape: responseShape(response) })}`); } catch { throw new ServiceUnavailableException('AI analysis is temporarily unavailable.'); }
    const output: AnalysisOutput | null = response ? parseAnalysisResponse(response) : null; if (!output) { if (process.env.NODE_ENV !== 'production') this.logger.warn(`Admin AI response validation failed ${JSON.stringify({ model: this.model, shape: responseShape(response) })}`); throw new BadGatewayException('The AI response could not be validated.'); }
    const [saved] = await this.database.db.insert(errorAnalyses).values({ errorGroupId, requestedByAdminId: actorId, model: this.model, provider: 'qwen-compatible', promptVersion: 'admin-error-analysis-v1', contextVersion: 'error-context-v1', contextHash, inputSummary: context, likelyCause: output.likelyCause.slice(0, 4000), evidence: output.evidence.slice(0, 12), investigationSteps: output.investigationSteps.slice(0, 12), suggestedFix: output.suggestedFix.slice(0, 4000), likelyModules: output.likelyModules.slice(0, 12), confidence: output.confidence, limitations: output.limitations.slice(0, 12) }).returning();
    await this.audit.write({ actorUserId: actorId, action: 'error.ai_analysis_requested', targetType: 'error_group', targetId: errorGroupId, metadata: { analysisId: saved.id, model: this.model, contextHash } }); return { ...saved, createdAt: saved.createdAt.toISOString(), reused: false };
  }
  private async context(id: string) { const [group] = await this.database.db.select().from(errorGroups).where(eq(errorGroups.id, id)).limit(1); if (!group) throw new NotFoundException('Error group not found.'); const [occurrences, [{ affectedUsers }]] = await Promise.all([this.database.db.select({ occurredAt: errorOccurrences.occurredAt, requestId: errorOccurrences.requestId, statusCode: errorOccurrences.statusCode, clientPlatform: errorOccurrences.clientPlatform, clientVersion: errorOccurrences.clientVersion, sanitizedContext: errorOccurrences.sanitizedContext, sanitizedStack: errorOccurrences.sanitizedStack }).from(errorOccurrences).where(eq(errorOccurrences.errorGroupId, id)).orderBy(desc(errorOccurrences.occurredAt)).limit(5), this.database.db.select({ affectedUsers: sql<number>`count(*)` }).from(errorGroupUsers).where(eq(errorGroupUsers.errorGroupId, id))]);
    const safeOccurrences = occurrences.map((item) => ({ occurredAt: item.occurredAt.toISOString(), requestId: item.requestId, statusCode: item.statusCode, clientPlatform: item.clientPlatform, clientVersion: item.clientVersion, sanitizedContext: this.sanitizer.sanitize(item.sanitizedContext), sanitizedStack: this.sanitizer.stack(item.sanitizedStack) }));
    return { errorGroupId: group.id, title: group.title, severity: group.severity, status: group.status, service: group.service, operation: group.operation, route: group.route, httpMethod: group.httpMethod, httpStatus: group.httpStatus, environment: group.environment, errorClass: group.errorClass, normalizedMessage: this.sanitizer.message(group.normalizedMessage), sanitizedStack: safeOccurrences[0]?.sanitizedStack ?? null, occurrenceCount: group.occurrenceCount, affectedUsersCount: Number(affectedUsers), firstSeenAt: group.firstSeenAt.toISOString(), lastSeenAt: group.lastSeenAt.toISOString(), recurringAfterResolution: group.status === 'resolved' && group.lastSeenAt > group.updatedAt, representativeOccurrences: safeOccurrences };
  }
}
