import { feedbackClusterValidationShape, parseFeedbackClusterResponse, validateFeedbackClusterMembership } from './feedback-clustering.schemas';
const valid = { clusters: [{ title: 'Collaborative Focus', summary: 'Shared focus sessions.', feedbackIds: ['a', 'b'], confidence: 'high' }], unclusteredFeedbackIds: ['c'] };
describe('feedback clustering response validation', () => {
  it('accepts plain and fenced JSON', () => { expect(parseFeedbackClusterResponse(JSON.stringify(valid))).toEqual(valid); expect(parseFeedbackClusterResponse(`\`\`\`json\n${JSON.stringify(valid)}\n\`\`\``)).toEqual(valid); });
  it('rejects malformed, singleton, duplicate, and invalid-confidence clusters', () => { expect(parseFeedbackClusterResponse('{bad')).toBeNull(); expect(parseFeedbackClusterResponse(JSON.stringify({ ...valid, clusters: [{ ...valid.clusters[0], feedbackIds: ['a'] }] }))).toBeNull(); expect(parseFeedbackClusterResponse(JSON.stringify({ ...valid, clusters: [valid.clusters[0], { ...valid.clusters[0], title: 'Duplicate' }] }))).toBeNull(); expect(parseFeedbackClusterResponse(JSON.stringify({ ...valid, clusters: [{ ...valid.clusters[0], confidence: 'certain' }] }))).toBeNull(); });
  it('continues to reject numeric confidence scores', () => { expect(parseFeedbackClusterResponse(JSON.stringify({ ...valid, clusters: [{ ...valid.clusters[0], confidence: 0.9 }] }))).toBeNull(); });
  it('rejects invented membership IDs after parsing', () => { const parsed = parseFeedbackClusterResponse(JSON.stringify(valid))!; expect(validateFeedbackClusterMembership(parsed, ['a','b','c'])).toBe(true); expect(validateFeedbackClusterMembership(parsed, ['a','b'])).toBe(false); });
  it('reports only structural validation metadata', () => { const raw = JSON.stringify({ clusters: [{ title: 'Sensitive title', summary: 'Sensitive summary', feedbackIds: ['private-id'], confidence: 'High' }], unclusteredFeedbackIds: [] }); const shape = feedbackClusterValidationShape(raw, ['allowed']); expect(shape).toMatchObject({ category: 'field', path: 'clusters[0].feedbackIds', fewerThanTwoMembers: true }); expect(JSON.stringify(shape)).not.toContain('Sensitive'); expect(JSON.stringify(shape)).not.toContain('private-id'); });
});
