import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { ActivityIndicator, Alert, AppState, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { getInstallationId } from '../../lib/pushDevicesApi'
import { useTheme } from '../../theme/useTheme'
import { mobileSupervisionApi as api, type Relationship, type SafeIdentity } from './api'
import { mobileIdentityLabel } from './identity'
import { ManagedAppsCard } from './ManagedAppsCard'
import { getDeviceCapability } from './deviceCapability'
import { reconcileGuardianRestrictions } from './restrictionEnforcement'

const permissionRows = [['can_view_task_progress','Task Progress'],['can_view_focus_progress','Focus Progress'],['can_view_achievement_summary','Achievement Summary'],['can_view_weekly_summary','Weekly Summary']] as const
export const splitRelationships = (relationships: Relationship[]) => ({ guardian: relationships.filter(row => row.status === 'active' && row.currentRole === 'guardian'), supervised: relationships.filter(row => row.status === 'active' && row.currentRole === 'supervised') })

export function SupervisionScreen({ navigation }: { navigation: any }) {
  const { theme } = useTheme(); const c = theme.colors
  const [relationships, setRelationships] = useState<Relationship[]>([]); const [requests, setRequests] = useState<Relationship[]>([]); const [devices, setDevices] = useState<any[]>([])
  const [guardianDashboard, setGuardianDashboard] = useState<Relationship | null>(null); const [managedRelationship, setManagedRelationship] = useState<Relationship | null>(null)
  const [editingPermissions, setEditingPermissions] = useState(false); const [permissionDraft, setPermissionDraft] = useState<Record<string, boolean | string>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [query, setQuery] = useState(''); const [people, setPeople] = useState<SafeIdentity[]>([]); const [target, setTarget] = useState<SafeIdentity | null>(null); const [level, setLevel] = useState('accountability'); const [requested, setRequested] = useState<Record<string, boolean>>({})
  const load = () => Promise.all([api.relationships(), api.requests(), api.devices()]).then(([r, q, d]) => { setRelationships(r); setRequests(q); setDevices(d); setManagedRelationship(current => current ? r.find(row => row.id === current.id) ?? null : null) }).catch(e => setError(e.message)).finally(() => setLoading(false))
  useEffect(() => { void load() }, [])
  useEffect(() => { const sync = () => void reconcileGuardianRestrictions().then(load).catch(() => undefined); sync(); const listener = AppState.addEventListener('change', state => { if (state === 'active') sync() }); return () => listener.remove() }, [])
  const Card = ({ children }: { children: ReactNode }) => <View style={{ backgroundColor: c.surface, borderRadius: 16, padding: 16, marginTop: 10 }}>{children}</View>
  const openManage = (relationship: Relationship) => { setManagedRelationship(relationship); setEditingPermissions(false); setPermissionDraft(relationship.permissions) }
  const savePermissions = async (nextLevel = managedRelationship?.permissions.level) => { if (!managedRelationship) return; try { const updated = await api.updatePermissions(managedRelationship.id, { ...permissionDraft, level: nextLevel }); setManagedRelationship(updated); setRelationships(rows => rows.map(row => row.id === updated.id ? updated : row)); setEditingPermissions(false) } catch (e) { setError(e instanceof Error ? e.message : 'Could not save supervision permissions.') } }
  const registerDevice = async () => { try { const deviceId = await getInstallationId(); const capability = await getDeviceCapability(); await api.registerDevice({ platform: capability.platform, deviceId, deviceName: 'This device', capabilityLevel: capability.capabilityLevel, permissionState: capability.permissionState }); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Could not register this device.') } }
  const revoke = () => { if (!managedRelationship) return; Alert.alert('Revoke Supervision?', 'This stops Guardian access, cancels active restrictions, and cannot be undone from this screen.', [{ text: 'Keep Supervision' }, { text: 'Revoke', style: 'destructive', onPress: () => void api.revoke(managedRelationship.id).then(() => { setManagedRelationship(null); void load() }).catch(e => setError(e.message)) }]) }
  if (loading) return <SafeAreaView style={{ flex: 1, backgroundColor: c.background, alignItems: 'center', justifyContent: 'center' }}><ActivityIndicator /></SafeAreaView>
  const roleGroups = splitRelationships(relationships)
  if (managedRelationship) {
    const registered = devices[0]; const deviceLevel = managedRelationship.permissions.level === 'device_restrictions'
    return <SafeAreaView style={{ flex: 1, backgroundColor: c.background }}><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 80 }}>
      <Pressable onPress={() => setManagedRelationship(null)}><Text style={{ color: c.primary }}>Back to Supervision</Text></Pressable>
      <Text style={{ color: c.text, fontSize: 28, fontWeight: '900', marginTop: 12 }}>Manage Supervision</Text>
      {error ? <Text style={{ color: c.error }}>{error}</Text> : null}
      <Card><Text style={{ color: c.text, fontSize: 20, fontWeight: '800' }}>Guardian</Text><Text style={{ color: c.text, fontWeight: '800', marginTop: 8 }}>{mobileIdentityLabel(managedRelationship.guardian)}</Text>{managedRelationship.guardian.username ? <Text style={{ color: c.secondaryText }}>@{managedRelationship.guardian.username}</Text> : null}<Text style={{ color: c.secondaryText, marginTop: 8 }}>Status: Active</Text><Text style={{ color: c.secondaryText }}>Supervision Level: {managedRelationship.permissions.level.replaceAll('_', ' ')}</Text></Card>
      <Card><Text style={{ color: c.text, fontSize: 20, fontWeight: '800' }}>Progress Sharing</Text>{permissionRows.map(([key, label]) => <Pressable key={key} disabled={!editingPermissions} onPress={() => setPermissionDraft(current => ({ ...current, [key]: !current[key] }))}><Text style={{ color: editingPermissions ? c.text : c.secondaryText, paddingVertical: 6 }}>{editingPermissions && permissionDraft[key] ? '☑' : editingPermissions ? '☐' : managedRelationship.permissions[key] ? 'ON' : 'OFF'} {label}</Text></Pressable>)}<Text style={{ color: c.secondaryText, marginTop: 6 }}>These permissions only share progress summaries. Notes, comments, attachments, files, messages, and passwords are never shared.</Text>{editingPermissions ? <View style={{ flexDirection: 'row', gap: 18, marginTop: 10 }}><Pressable onPress={() => void savePermissions()}><Text style={{ color: c.primary, fontWeight: '800' }}>Save Changes</Text></Pressable><Pressable onPress={() => setEditingPermissions(false)}><Text style={{ color: c.secondaryText }}>Cancel</Text></Pressable></View> : <Pressable onPress={() => setEditingPermissions(true)}><Text style={{ color: c.primary, fontWeight: '800', marginTop: 10 }}>Manage Permissions</Text></Pressable>}</Card>
      <Card><Text style={{ color: c.text, fontSize: 20, fontWeight: '800' }}>Device Restrictions</Text>{deviceLevel ? <Text style={{ color: c.primary }}>Enabled with your consent</Text> : <><Text style={{ color: c.secondaryText }}>Allow this Guardian to create study restrictions using apps you explicitly approve.</Text><Pressable onPress={() => Alert.alert('Enable Device Restrictions?', 'This allows the Guardian to create study restrictions only for apps you later choose to approve.', [{ text: 'Cancel' }, { text: 'Enable', onPress: () => void savePermissions('device_restrictions') }])}><Text style={{ color: c.primary, fontWeight: '800', marginTop: 10 }}>Enable Device Restrictions</Text></Pressable></>}
      </Card>
      {deviceLevel ? <Card><Text style={{ color: c.text, fontSize: 20, fontWeight: '800' }}>Device Status</Text>{registered ? <><Text style={{ color: c.primary }}>Registered</Text><Text style={{ color: c.secondaryText }}>{registered.deviceName ?? 'This device'} · {registered.capabilityLevel?.replaceAll('_',' ')}</Text><ManagedAppsCard device={registered} colors={c} onSaved={() => void load()} onError={setError} /></> : <><Text style={{ color: c.secondaryText }}>Not registered</Text><Pressable onPress={() => void registerDevice()}><Text style={{ color: c.primary, fontWeight: '800', marginTop: 10 }}>Register This Device</Text></Pressable></>}</Card> : null}
      <Pressable onPress={revoke}><Text style={{ color: c.error, fontWeight: '800', marginTop: 22 }}>Revoke Supervision</Text></Pressable>
    </ScrollView></SafeAreaView>
  }
  return <SafeAreaView style={{ flex: 1, backgroundColor: c.background }}><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 80 }}>
    <Pressable onPress={() => guardianDashboard ? setGuardianDashboard(null) : navigation.goBack()}><Text style={{ color: c.primary }}>Back</Text></Pressable>
    <Text style={{ color: c.text, fontSize: 28, fontWeight: '900', marginTop: 12 }}>{guardianDashboard ? 'Guardian Dashboard' : 'Supervision'}</Text>{error ? <Text style={{ color: c.error }}>{error}</Text> : null}
    {guardianDashboard ? <><Text style={{ color: c.text, fontSize: 22, fontWeight: '800' }}>{mobileIdentityLabel(guardianDashboard.supervisedUser)}</Text><Text style={{ color: c.secondaryText }}>{guardianDashboard.permissions.level}</Text><Card><Text style={{color:c.secondaryText}}>Use the safe Guardian progress sections on this dashboard. Supervised-side relationships are managed separately under My Supervision.</Text></Card></> : <>
      <Text style={{ color: c.text, fontSize: 20, fontWeight: '800', marginTop: 18 }}>People I Supervise</Text>{roleGroups.guardian.map(row => <Pressable key={row.id} onPress={() => setGuardianDashboard(row)}><Card><Text style={{ color: c.text, fontWeight: '800' }}>{mobileIdentityLabel(row.supervisedUser)}</Text><Text style={{ color: c.secondaryText }}>{row.permissions.level} · Open Dashboard</Text></Card></Pressable>)}
      <Text style={{ color: c.text, fontSize: 20, fontWeight: '800', marginTop: 18 }}>My Supervision</Text>{roleGroups.supervised.map(row => <Pressable key={row.id} onPress={() => openManage(row)}><Card><Text style={{ color: c.text, fontWeight: '800' }}>{mobileIdentityLabel(row.guardian)}</Text>{row.guardian.username ? <Text style={{color:c.secondaryText}}>@{row.guardian.username}</Text> : null}<Text style={{ color: c.secondaryText }}>{row.permissions.level} · Managed by this Guardian</Text><Text style={{ color: c.primary, marginTop: 8 }}>Manage Supervision</Text></Card></Pressable>)}
      <Text style={{ color: c.text, fontSize: 20, fontWeight: '800', marginTop: 18 }}>Requests</Text>{requests.map(row => <Card key={row.id}><Text style={{ color: c.text }}>{mobileIdentityLabel(row.guardian)} wants to supervise you.</Text><View style={{ flexDirection: 'row', gap: 18, marginTop: 8 }}><Pressable onPress={() => void api.respond(row.id, 'accept').then(load)}><Text style={{ color: c.primary }}>Accept</Text></Pressable><Pressable onPress={() => void api.respond(row.id, 'reject').then(load)}><Text style={{ color: c.error }}>Decline</Text></Pressable></View></Card>)}
      <Text style={{ color: c.text, fontSize: 20, fontWeight: '800', marginTop: 18 }}>Add Person</Text><TextInput accessibilityLabel="Search BeePlan users" value={query} onChangeText={value => { setQuery(value); if (value.length > 1) void api.people(value).then(setPeople).catch(e => setError(e.message)); else setPeople([]) }} placeholder="Name or username" placeholderTextColor={c.secondaryText} style={{ color: c.text, backgroundColor: c.surface, borderRadius: 12, padding: 14, marginTop: 8 }} />{people.map(person => <Pressable key={person.id} onPress={() => !person.relationshipState && setTarget(person)}><Card><Text style={{ color: c.text, fontWeight: '800' }}>{person.displayName}</Text><Text style={{ color: c.secondaryText }}>@{person.username}</Text>{person.relationshipState ? <Text style={{ color: c.primary }}>{person.relationshipState.status === 'pending' ? 'Supervision request already pending.' : 'An active supervision relationship already exists.'}</Text> : null}</Card></Pressable>)}
      {target ? <Card><Text style={{color:c.text,fontWeight:'800'}}>Request supervision for {target.displayName}</Text>{[['plan_only','Plan Only'],['accountability','Accountability'],['device_restrictions','Device Restrictions']].map(([value,label])=><Pressable key={value} onPress={()=>setLevel(value)}><Text style={{color:level===value?c.primary:c.text,paddingVertical:4}}>{level===value?'●':'○'} {label}</Text></Pressable>)}{permissionRows.map(([key,label])=><Pressable key={key} onPress={()=>setRequested(old=>({...old,[key]:!old[key]}))}><Text style={{color:c.text,paddingVertical:4}}>{requested[key]?'☑':'☐'} {label}</Text></Pressable>)}<Pressable onPress={()=>void api.send({supervisedUserId:target.id,level,progressPermissions:requested}).then(()=>{setTarget(null);void load()}).catch(e=>setError(e.message))}><Text style={{color:c.primary,fontWeight:'800',marginTop:10}}>Send Supervision Request</Text></Pressable></Card> : null}
    </>}
  </ScrollView></SafeAreaView>
}
