import { useEffect, useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native'
import { useAuth } from '../../../hooks/useAuth'
import { useTheme } from '../../../theme/useTheme'
import { findInviteCandidates, inviteFriend, listMembers, type WhiteboardRole } from '../api/whiteboardApi'

export default function WhiteboardShareScreen({ route, navigation }: { route: { params: { boardId: string } }; navigation: any }) {
  const { accessToken } = useAuth(); const { theme } = useTheme(); const { colors } = theme; const boardId = route.params.boardId
  const [query, setQuery] = useState(''); const [role, setRole] = useState<Exclude<WhiteboardRole, 'owner'>>('viewer'); const [members, setMembers] = useState<Array<{ id: string; role: WhiteboardRole; username?: string; fullName?: string }>>([]); const [candidates, setCandidates] = useState<Array<{ id: string; username: string; fullName: string }>>([]); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false)
  useEffect(() => { if (!accessToken) return; void listMembers(accessToken, boardId).then(setMembers).catch(() => undefined).finally(() => setLoading(false)) }, [accessToken, boardId])
  useEffect(() => { if (!accessToken || query.trim().length < 2) { setCandidates([]); return }; const timer = setTimeout(() => { void findInviteCandidates(accessToken, boardId, query.trim()).then(setCandidates).catch(() => setCandidates([])) }, 250); return () => clearTimeout(timer) }, [accessToken, boardId, query])
  return <View className="flex-1" style={{ backgroundColor: colors.background }}><View className="flex-row items-center border-b px-4 py-3" style={{ borderColor: colors.border, backgroundColor: colors.surface }}><Pressable accessibilityLabel="Back" onPress={() => navigation.goBack()}><Text className="font-bold" style={{ color: colors.accent }}>‹ Back</Text></Pressable><Text className="ms-4 text-lg font-black" style={{ color: colors.text }}>Share Whiteboard</Text></View><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 50 }}><Text className="mb-2 text-xs font-black uppercase tracking-widest" style={{ color: colors.secondaryText }}>Invite a friend</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search by username" placeholderTextColor={colors.placeholder} autoCapitalize="none" className="rounded-xl border px-4 py-3" style={{ borderColor: colors.border, backgroundColor: colors.input, color: colors.text }} /><View className="my-3 flex-row gap-2">{(['viewer', 'editor'] as const).map((item) => <Pressable key={item} onPress={() => setRole(item)} className="rounded-xl border px-4 py-2" style={{ borderColor: role === item ? colors.accent : colors.border, backgroundColor: role === item ? colors.accentSoft : colors.surface }}><Text className="font-bold capitalize" style={{ color: role === item ? colors.accent : colors.text }}>{item}</Text></Pressable>)}</View>{candidates.map((candidate) => <Pressable key={candidate.id} disabled={sending} onPress={async () => { if (!accessToken) return; setSending(true); try { await inviteFriend(accessToken, boardId, candidate.id, role); setQuery(''); setCandidates([]); Alert.alert('Invitation sent', `@${candidate.username}`) } catch (e) { Alert.alert('Unable to invite', e instanceof Error ? e.message : 'Please try again.') } finally { setSending(false) } }} className="mb-2 rounded-xl border p-3" style={{ borderColor: colors.border, backgroundColor: colors.surface }}><Text className="font-bold" style={{ color: colors.text }}>{candidate.fullName}</Text><Text className="text-xs" style={{ color: colors.secondaryText }}>@{candidate.username}</Text></Pressable>)}<Text className="mb-3 mt-5 text-xs font-black uppercase tracking-widest" style={{ color: colors.secondaryText }}>Members</Text>{loading ? <ActivityIndicator color={colors.accent} /> : members.map((member) => <View key={member.id} className="mb-2 flex-row items-center justify-between rounded-xl border p-3" style={{ borderColor: colors.border, backgroundColor: colors.surface }}><View><Text className="font-bold" style={{ color: colors.text }}>{member.fullName ?? member.username ?? 'Member'}</Text><Text className="text-xs" style={{ color: colors.secondaryText }}>@{member.username ?? 'user'}</Text></View><Text className="text-xs font-black uppercase" style={{ color: colors.accent }}>{member.role}</Text></View>)}</ScrollView></View>
}
