import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'
import { and, desc, eq, gte, lt, lte, ne } from 'drizzle-orm'
import { DatabaseService } from '../db/database.service'
import { achievements, focusSessions, supervisionOverrides, supervisionRelationships, supervisionRules, tasks } from '../db/schema'

export type GuardianTaskProgressDto = { id: string; title: string; status: string; dueAt: Date | null; completedAt: Date | null; progress: number; estimatedMinutes: number; focusedMinutes: number; overdue: boolean; dueToday: boolean; upcoming: boolean }
type Permission = 'can_view_task_progress' | 'can_view_focus_progress' | 'can_view_achievement_summary' | 'can_view_weekly_summary'
@Injectable()
export class SupervisionProgressProjectionService {
  constructor(private readonly database: DatabaseService) {}
  private get db() { return this.database.db }
  async tasks(guardianId: string, relationshipId: string, filter = 'today') { const userId = await this.authorize(guardianId, relationshipId, 'can_view_task_progress'); const { start, tomorrow, weekEnd } = this.ranges(); const conditions = [eq(tasks.userId, userId)]; if (filter === 'today') conditions.push(gte(tasks.dueDate, start), lt(tasks.dueDate, tomorrow)); else if (filter === 'upcoming') conditions.push(gte(tasks.dueDate, tomorrow), lt(tasks.dueDate, weekEnd)); else if (filter === 'completed') conditions.push(eq(tasks.status, 'done')); else if (filter === 'overdue') conditions.push(lt(tasks.dueDate, start)); else if (filter === 'active') conditions.push(ne(tasks.status, 'done')); else throw new ForbiddenException('Unsupported task filter.'); const rows = await this.db.select({ id: tasks.id, title: tasks.title, status: tasks.status, dueAt: tasks.dueDate, progress: tasks.progress, estimatedMinutes: tasks.estimatedTimeMinutes, focusedMinutes: tasks.spentTimeMinutes, updatedAt: tasks.updatedAt }).from(tasks).where(and(...conditions)).orderBy(tasks.dueDate); return rows.filter(r => filter !== 'overdue' || r.status !== 'done').map(r => this.taskDto(r, start, tomorrow)) }
  async progress(guardianId: string, relationshipId: string) { const userId = await this.authorize(guardianId, relationshipId, 'can_view_task_progress'); const { start, tomorrow } = this.ranges(); const rows = await this.db.select({ status: tasks.status, dueAt: tasks.dueDate }).from(tasks).where(and(eq(tasks.userId, userId), lt(tasks.dueDate, tomorrow))); const today = rows.filter(r => r.dueAt && r.dueAt >= start); const focus = await this.focusMetrics(userId); const [currentRule] = await this.db.select({ id: supervisionRules.id, name: supervisionRules.name, status: supervisionRules.status }).from(supervisionRules).where(and(eq(supervisionRules.relationshipId, relationshipId), lte(supervisionRules.startsAt, new Date()), gte(supervisionRules.endsAt, new Date()))).limit(1); return { today: { tasksCompleted: today.filter(r => r.status === 'done').length, tasksTotal: today.length, tasksRemaining: today.filter(r => r.status !== 'done').length, overdueTasks: rows.filter(r => r.dueAt && r.dueAt < start && r.status !== 'done').length, focusMinutes: focus.todayMinutes, focusSessionsCompleted: focus.todaySessions }, currentRule: currentRule ?? null } }
  async focusSummary(guardianId: string, relationshipId: string) { const userId = await this.authorize(guardianId, relationshipId, 'can_view_focus_progress'); const m = await this.focusMetrics(userId); return { totalFocusMinutesToday: m.todayMinutes, totalFocusMinutesWeek: m.weekMinutes, sessionsCompletedToday: m.todaySessions, sessionsCompletedWeek: m.weekSessions, averageSessionMinutes: m.weekSessions ? Math.round(m.weekMinutes / m.weekSessions) : 0, supervisedSessionsCompleted: m.weekSessions, supervisedSessionsMissed: 0 } }
  async achievementSummary(guardianId: string, relationshipId: string) { const userId = await this.authorize(guardianId, relationshipId, 'can_view_achievement_summary'); const safe = ['Education', 'Career', 'Skills', 'Learning', 'Milestone']; return this.db.select({ id: achievements.id, title: achievements.title, unlockedAt: achievements.achievementDate, category: achievements.category }).from(achievements).where(eq(achievements.userId, userId)).orderBy(desc(achievements.achievementDate)).limit(20).then(rows => rows.filter(r => safe.includes(r.category))) }
  async weeklySummary(guardianId: string, relationshipId: string) { const userId = await this.authorize(guardianId, relationshipId, 'can_view_weekly_summary'); const { weekStart, weekEnd } = this.ranges(); const taskRows = await this.db.select({ status: tasks.status, dueAt: tasks.dueDate, updatedAt: tasks.updatedAt }).from(tasks).where(and(eq(tasks.userId, userId), gte(tasks.updatedAt, weekStart), lt(tasks.updatedAt, weekEnd))); const ruleRows = await this.db.select({ status: supervisionRules.status }).from(supervisionRules).where(and(eq(supervisionRules.relationshipId, relationshipId), gte(supervisionRules.startsAt, weekStart), lt(supervisionRules.startsAt, weekEnd))); const overrides = await this.db.select({ id: supervisionOverrides.id }).from(supervisionOverrides).innerJoin(supervisionRules, eq(supervisionOverrides.ruleId, supervisionRules.id)).where(and(eq(supervisionRules.relationshipId, relationshipId), gte(supervisionOverrides.effectiveAt, weekStart), lt(supervisionOverrides.effectiveAt, weekEnd))); const focus = await this.focusMetrics(userId); const completed = taskRows.filter(r => r.status === 'done').length, due = taskRows.filter(r => r.dueAt).length; return { tasksCompleted: completed, tasksMissed: taskRows.filter(r => r.dueAt && r.dueAt < new Date() && r.status !== 'done').length, focusMinutes: focus.weekMinutes, rulesCompleted: ruleRows.filter(r => r.status === 'completed').length, rulesTotal: ruleRows.length, overrides: overrides.length, completionRate: due ? Math.round(completed / due * 100) : null } }
  private async authorize(guardianId: string, relationshipId: string, permission: Permission) { const [row] = await this.db.select().from(supervisionRelationships).where(eq(supervisionRelationships.id, relationshipId)); if (!row) throw new NotFoundException('Supervision relationship not found.'); if (row.guardianUserId !== guardianId || row.status !== 'active') throw new ForbiddenException('Active guardian permission is required.'); if ((row.permissions as Record<string, unknown>)[permission] !== true) throw new ForbiddenException('Progress visibility permission was not granted.'); return row.supervisedUserId }
  private taskDto(r: { id: string; title: string; status: string; dueAt: Date | null; progress: number; estimatedMinutes: number; focusedMinutes: number; updatedAt: Date }, start: Date, tomorrow: Date): GuardianTaskProgressDto { return { id: r.id, title: r.title, status: r.status, dueAt: r.dueAt, completedAt: r.status === 'done' ? r.updatedAt : null, progress: r.progress, estimatedMinutes: r.estimatedMinutes, focusedMinutes: r.focusedMinutes, overdue: Boolean(r.dueAt && r.dueAt < start && r.status !== 'done'), dueToday: Boolean(r.dueAt && r.dueAt >= start && r.dueAt < tomorrow), upcoming: Boolean(r.dueAt && r.dueAt >= tomorrow) } }
  private async focusMetrics(userId: string) { const { start, weekStart, weekEnd } = this.ranges(); const rows = await this.db.select({ startedAt: focusSessions.startedAt, actualMinutes: focusSessions.actualMinutes }).from(focusSessions).where(and(eq(focusSessions.userId, userId), eq(focusSessions.status, 'completed'), gte(focusSessions.startedAt, weekStart), lt(focusSessions.startedAt, weekEnd))); const weekMinutes = rows.reduce((n, r) => n + (r.actualMinutes ?? 0), 0), today = rows.filter(r => r.startedAt >= start); return { weekMinutes, weekSessions: rows.length, todayMinutes: today.reduce((n, r) => n + (r.actualMinutes ?? 0), 0), todaySessions: today.length } }
  private ranges() { const now = new Date(), start = new Date(now); start.setHours(0, 0, 0, 0); const tomorrow = new Date(start); tomorrow.setDate(tomorrow.getDate() + 1); const weekStart = new Date(start); weekStart.setDate(weekStart.getDate() - ((weekStart.getDay() + 6) % 7)); const weekEnd = new Date(weekStart); weekEnd.setDate(weekEnd.getDate() + 7); return { start, tomorrow, weekStart, weekEnd } }
}
