import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'
import { Cron, CronExpression } from '@nestjs/schedule'
import { and, desc, eq, gte, ilike, inArray, or } from 'drizzle-orm'
import { DatabaseService } from '../db/database.service'
import { supervisionAccessRequests, supervisionAuditLogs, supervisionDevices, supervisionManagedApps, supervisionOverrides, supervisionRelationships, supervisionRules, tasks, users } from '../db/schema'
import { SupervisionAccessEvaluator } from './supervision-access-evaluator.service'
import { SupervisionGrantService } from './supervision-grant.service'

type Level = 'plan_only' | 'accountability' | 'device_restrictions'
const levels = new Set<Level>(['plan_only', 'accountability', 'device_restrictions'])
export function restrictionCompletionReason(rule: { restrictionMode: string; endsAt: Date }, taskStatus: string | null, now: Date) { const taskDone = ['task', 'task_or_time'].includes(rule.restrictionMode) && taskStatus === 'done'; const timeExpired = ['time', 'task_or_time'].includes(rule.restrictionMode) && rule.endsAt <= now; return taskDone ? 'task_completed' : timeExpired ? 'time_expired' : null }
@Injectable()
export class SupervisionService {
  constructor(private readonly database: DatabaseService, private readonly evaluator: SupervisionAccessEvaluator, private readonly grants: SupervisionGrantService) {}
  private get db() { return this.database.db }
  async people(userId: string, q: string) { const term = q.trim(); if (term.length < 2) return []; const people = await this.db.select({ id: users.id, displayName: users.fullName, fullName: users.fullName, username: users.username, avatarUrl: users.avatarUrl }).from(users).where(ilike(users.fullName, `%${term}%`)).limit(12); const candidates = people.filter(row => row.id !== userId); if (!candidates.length) return []; const rows = await this.db.select().from(supervisionRelationships).where(and(or(eq(supervisionRelationships.guardianUserId, userId), eq(supervisionRelationships.supervisedUserId, userId)), inArray(supervisionRelationships.status, ['pending', 'active']))); return candidates.map(person => { const relationship = rows.find(row => row.guardianUserId === person.id || row.supervisedUserId === person.id); return { ...person, relationshipState: relationship ? { id: relationship.id, status: relationship.status, direction: relationship.guardianUserId === userId ? 'guardian' : 'supervised' } : null } }) }
  async request(guardianUserId: string, body: Record<string, unknown>) { const supervisedUserId = String(body.supervisedUserId ?? ''); if (!supervisedUserId || supervisedUserId === guardianUserId) throw new BadRequestException('You cannot supervise yourself.'); const level = String(body.level ?? 'plan_only') as Level; if (!levels.has(level)) throw new BadRequestException('Invalid supervision permission level.'); const requested = (body.progressPermissions ?? {}) as Record<string, unknown>; const permissions = { level, can_view_task_progress: requested.can_view_task_progress === true, can_view_focus_progress: requested.can_view_focus_progress === true, can_view_achievement_summary: requested.can_view_achievement_summary === true, can_view_weekly_summary: requested.can_view_weekly_summary === true }; const [person] = await this.db.select({ id: users.id }).from(users).where(eq(users.id, supervisedUserId)); if (!person) throw new NotFoundException('BeePlan user not found.'); const [existing] = await this.db.select().from(supervisionRelationships).where(and(or(and(eq(supervisionRelationships.guardianUserId, guardianUserId), eq(supervisionRelationships.supervisedUserId, supervisedUserId)), and(eq(supervisionRelationships.guardianUserId, supervisedUserId), eq(supervisionRelationships.supervisedUserId, guardianUserId))), inArray(supervisionRelationships.status, ['pending', 'active']))); if (existing) { if (existing.status === 'pending') throw new ConflictException('Supervision request already pending.'); throw new ConflictException(existing.guardianUserId === guardianUserId ? 'You already supervise this person.' : 'This person already supervises you.'); } const [row] = await this.db.insert(supervisionRelationships).values({ guardianUserId, supervisedUserId, permissions }).returning(); await this.log(row.id, guardianUserId, 'requested'); return row }
  async requests(userId: string) { const rows = await this.db.select().from(supervisionRelationships).where(and(eq(supervisionRelationships.supervisedUserId, userId), eq(supervisionRelationships.status, 'pending'))).orderBy(desc(supervisionRelationships.createdAt)); return this.withIdentities(rows, userId) }
  async respond(userId: string, id: string, accept: boolean) { await this.supervised(userId, id, 'pending'); const now = new Date(); const [updated] = await this.db.update(supervisionRelationships).set({ status: accept ? 'active' : 'rejected', acceptedAt: accept ? now : null, updatedAt: now }).where(and(eq(supervisionRelationships.id, id), eq(supervisionRelationships.status, 'pending'), eq(supervisionRelationships.supervisedUserId, userId))).returning(); if (!updated) throw new ConflictException('This request has already been handled.'); await this.log(id, userId, accept ? 'accepted' : 'rejected'); return updated }
  async relationships(userId: string) { const rows = await this.db.select().from(supervisionRelationships).where(or(eq(supervisionRelationships.guardianUserId, userId), eq(supervisionRelationships.supervisedUserId, userId))).orderBy(desc(supervisionRelationships.createdAt)); return this.withIdentities(rows, userId) }
  async updatePermissions(userId: string, id: string, body: Record<string, unknown>) { const relationship = await this.supervised(userId, id, 'active'); const requested = (body.permissions ?? body) as Record<string, unknown>; const current = relationship.permissions as Record<string, unknown>; const level = String(requested.level ?? current.level ?? 'plan_only') as Level; if (!levels.has(level)) throw new BadRequestException('Invalid supervision permission level.'); const aiPolicy = String(requested.ai_access_policy ?? current.ai_access_policy ?? 'ai_may_approve'); if (!['ai_may_approve', 'supervisor_must_approve', 'always_require_supervisor'].includes(aiPolicy)) throw new BadRequestException('Invalid AI access policy.'); const next = { level, can_view_task_progress: requested.can_view_task_progress === undefined ? Boolean(current.can_view_task_progress) : requested.can_view_task_progress === true, can_view_focus_progress: requested.can_view_focus_progress === undefined ? Boolean(current.can_view_focus_progress) : requested.can_view_focus_progress === true, can_view_achievement_summary: requested.can_view_achievement_summary === undefined ? Boolean(current.can_view_achievement_summary) : requested.can_view_achievement_summary === true, can_view_weekly_summary: requested.can_view_weekly_summary === undefined ? Boolean(current.can_view_weekly_summary) : requested.can_view_weekly_summary === true, ai_access_policy: aiPolicy }; const [updated] = await this.db.update(supervisionRelationships).set({ permissions: next, updatedAt: new Date() }).where(and(eq(supervisionRelationships.id, id), eq(supervisionRelationships.supervisedUserId, userId), eq(supervisionRelationships.status, 'active'))).returning(); if (!updated) throw new NotFoundException('Active supervision relationship not found.'); await this.log(id, userId, 'permissions_updated'); return (await this.withIdentities([updated], userId))[0] }
  async revoke(userId: string, id: string) { const row = await this.participant(userId, id); if (row.status === 'revoked') return row; const now = new Date(); const [updated] = await this.db.update(supervisionRelationships).set({ status: 'revoked', revokedAt: now, updatedAt: now }).where(eq(supervisionRelationships.id, id)).returning(); await this.db.update(supervisionRules).set({ status: 'cancelled', completedAt: now, updatedAt: now }).where(and(eq(supervisionRules.relationshipId, id), inArray(supervisionRules.status, ['scheduled', 'active', 'paused']))); await this.log(id, userId, 'revoked'); return updated }
  async rules(userId: string, relationshipId: string) { await this.participant(userId, relationshipId); return this.db.select().from(supervisionRules).where(eq(supervisionRules.relationshipId, relationshipId)).orderBy(desc(supervisionRules.startsAt)) }
  async createRule(userId: string, relationshipId: string, body: Record<string, unknown>) { const relationship = await this.guardian(userId, relationshipId); const level = (relationship.permissions as { level?: Level }).level ?? 'plan_only'; if (level !== 'device_restrictions') throw new ForbiddenException('Device restriction permission is required.'); const restrictionMode = String(body.restrictionMode ?? 'time'); if (!['time', 'task', 'task_or_time'].includes(restrictionMode)) throw new BadRequestException('Invalid restriction mode.'); const name = String(body.name ?? '').trim(), startsAt = new Date(String(body.startsAt ?? new Date().toISOString())); const endsAt = body.endsAt ? new Date(String(body.endsAt)) : null; const taskId = body.taskId ? String(body.taskId) : null; if (!name || !Number.isFinite(startsAt.getTime()) || ((restrictionMode === 'time' || restrictionMode === 'task_or_time') && (!endsAt || !Number.isFinite(endsAt.getTime()) || endsAt <= startsAt)) || (restrictionMode !== 'time' && !taskId)) throw new BadRequestException('A supervised task is required for task-linked restrictions, along with valid timing.'); if (taskId) { const [task] = await this.db.select({ id: tasks.id, status: tasks.status }).from(tasks).where(and(eq(tasks.id, taskId), eq(tasks.userId, relationship.supervisedUserId))); if (!task || task.status === 'done') throw new BadRequestException('Selected task is not an eligible supervised task.'); } const approvedApps = await this.approvedAppsForRelationship(relationship); const requestedIds = Array.isArray(body.managedAppIds) ? body.managedAppIds.map(String) : []; if (!requestedIds.length) throw new BadRequestException('Select at least one approved app or configured iOS selection.'); if (requestedIds.some(id => !approvedApps.some(app => app.id === id || (app.platform === 'ios' && id === `ios:${app.deviceId}`)))) throw new ForbiddenException('A selected app was not approved by the supervised user.'); const completionTrigger = restrictionMode === 'time' ? 'time_expired' : restrictionMode === 'task' ? 'task_completed' : 'either'; const [rule] = await this.db.insert(supervisionRules).values({ relationshipId, createdBy: userId, name, startsAt, endsAt: endsAt ?? new Date('9999-12-31T23:59:59Z'), mode: 'device_restrictions', restrictionMode, completionTrigger, appSelection: { managedAppIds: requestedIds }, repeat: { type: 'once' }, taskId, status: startsAt <= new Date() ? 'active' : 'scheduled' }).returning(); await this.log(relationshipId, userId, 'rule_created', rule.id); return rule }
  async updateRule(userId: string, id: string, body: Record<string, unknown>) { const rule = await this.ruleForGuardian(userId, id); const [updated] = await this.db.update(supervisionRules).set({ name: body.name === undefined ? rule.name : String(body.name).trim(), startsAt: body.startsAt ? new Date(String(body.startsAt)) : rule.startsAt, endsAt: body.endsAt ? new Date(String(body.endsAt)) : rule.endsAt, repeat: body.repeat ?? rule.repeat, updatedAt: new Date() }).where(eq(supervisionRules.id, id)).returning(); await this.log(rule.relationshipId, userId, 'rule_updated', id); return updated }
  async action(userId: string, id: string, action: string) { const rule = await this.rule(id); if (action === 'override') { const relationship = await this.supervised(userId, rule.relationshipId, 'active'); const now = new Date(); const [override] = await this.db.insert(supervisionOverrides).values({ ruleId: id, userId, reason: 'emergency' }).returning(); await this.db.update(supervisionRules).set({ status: 'overridden', completedAt: now, updatedAt: now }).where(eq(supervisionRules.id, id)); await this.log(relationship.id, userId, 'override_used', id); return override } if (!['pause', 'resume', 'end'].includes(action)) throw new BadRequestException('Unknown rule action.'); await this.guardian(userId, rule.relationshipId); const status = action === 'pause' ? 'paused' : action === 'resume' ? 'active' : 'completed'; const now = new Date(); const [updated] = await this.db.update(supervisionRules).set({ status, completedAt: action === 'end' ? now : rule.completedAt, updatedAt: now }).where(eq(supervisionRules.id, id)).returning(); await this.log(rule.relationshipId, userId, `rule_${action}`, id); return updated }
  async audit(userId: string, relationshipId: string) { await this.participant(userId, relationshipId); return this.db.select().from(supervisionAuditLogs).where(eq(supervisionAuditLogs.relationshipId, relationshipId)).orderBy(desc(supervisionAuditLogs.createdAt)) }
  async report(userId: string, relationshipId: string) { await this.participant(userId, relationshipId); const rules = await this.rules(userId, relationshipId); return { rules: rules.length, completed: rules.filter(r => r.status === 'completed').length, overridden: rules.filter(r => r.status === 'overridden').length, active: rules.filter(r => r.status === 'active').length } }
  async devices(userId: string) { return this.db.select().from(supervisionDevices).where(eq(supervisionDevices.userId, userId)) }
  async registerDevice(userId: string, body: Record<string, unknown>) { const platform = String(body.platform ?? ''); const deviceId = String(body.deviceId ?? ''); if (!['ios', 'android'].includes(platform) || !deviceId) throw new BadRequestException('A platform and device identifier are required.'); const capabilityLevel = this.capability(body.capabilityLevel); const permissionState = this.permission(body.permissionState); const existing = await this.db.select().from(supervisionDevices).where(and(eq(supervisionDevices.userId, userId), eq(supervisionDevices.deviceId, deviceId))); if (existing[0]) { const [updated] = await this.db.update(supervisionDevices).set({ platform, deviceName: body.deviceName ? String(body.deviceName) : null, capabilityLevel, permissionState, lastSeenAt: new Date(), updatedAt: new Date() }).where(eq(supervisionDevices.id, existing[0].id)).returning(); return updated } const [created] = await this.db.insert(supervisionDevices).values({ userId, platform, deviceId, deviceName: body.deviceName ? String(body.deviceName) : null, capabilityLevel, permissionState }).returning(); return created }
  async updateDevice(userId: string, id: string, body: Record<string, unknown>) { const [device] = await this.db.select().from(supervisionDevices).where(and(eq(supervisionDevices.id, id), eq(supervisionDevices.userId, userId))); if (!device) throw new NotFoundException('Supervision device not found.'); const [updated] = await this.db.update(supervisionDevices).set({ capabilityLevel: body.capabilityLevel === undefined ? device.capabilityLevel : this.capability(body.capabilityLevel), permissionState: body.permissionState === undefined ? device.permissionState : this.permission(body.permissionState), lastSeenAt: new Date(), updatedAt: new Date() }).where(eq(supervisionDevices.id, id)).returning(); return updated }
  async managedApps(userId: string, deviceId: string) { const [device] = await this.db.select().from(supervisionDevices).where(and(eq(supervisionDevices.id, deviceId), eq(supervisionDevices.userId, userId))); if (!device) throw new NotFoundException('Supervision device not found.'); if (device.platform === 'ios') return []; return this.db.select({ id: supervisionManagedApps.id, platformAppIdentifier: supervisionManagedApps.platformAppIdentifier, displayName: supervisionManagedApps.displayName, iconReference: supervisionManagedApps.iconReference, enabledForGuardianManagement: supervisionManagedApps.enabledForGuardianManagement, lastSeenAt: supervisionManagedApps.lastSeenAt }).from(supervisionManagedApps).where(and(eq(supervisionManagedApps.deviceId, deviceId), eq(supervisionManagedApps.enabledForGuardianManagement, true))) }
  async configureManagedApps(userId: string, deviceId: string, body: Record<string, unknown>) { const [device] = await this.db.select().from(supervisionDevices).where(and(eq(supervisionDevices.id, deviceId), eq(supervisionDevices.userId, userId))); if (!device) throw new NotFoundException('Supervision device not found.'); const enabled = body.enabled === true; if (device.platform === 'ios') { const count = Math.max(0, Number(body.selectedAppCount ?? 0)); const [updated] = await this.db.update(supervisionDevices).set({ appManagementEnabled: enabled, selectionConfigured: enabled && body.selectionConfigured === true, selectedAppCount: count, categoriesConfigured: body.categoriesConfigured === true, lastSeenAt: new Date(), updatedAt: new Date() }).where(eq(supervisionDevices.id, deviceId)).returning(); await this.auditConsentChange(userId, enabled); return updated; } if (!Array.isArray(body.apps)) { const [updated] = await this.db.update(supervisionDevices).set({ appManagementEnabled: enabled, lastSeenAt: new Date(), updatedAt: new Date() }).where(eq(supervisionDevices.id, deviceId)).returning(); if (!enabled) await this.db.delete(supervisionManagedApps).where(eq(supervisionManagedApps.deviceId, deviceId)); await this.auditConsentChange(userId, enabled); return updated; } const deduped = [...new Map((body.apps as Array<Record<string, unknown>>).map(app => [String(app.platformAppIdentifier ?? '').trim(), app])).values()]; if (deduped.some(app => !String(app.platformAppIdentifier ?? '').trim() || !String(app.displayName ?? '').trim())) throw new BadRequestException('Approved apps require an identifier and display name.'); const updated = await this.db.transaction(async tx => { await tx.delete(supervisionManagedApps).where(eq(supervisionManagedApps.deviceId, deviceId)); if (enabled && deduped.length) await tx.insert(supervisionManagedApps).values(deduped.map(app => ({ deviceId, platformAppIdentifier: String(app.platformAppIdentifier).trim(), displayName: String(app.displayName).trim(), iconReference: app.iconReference ? String(app.iconReference) : null, enabledForGuardianManagement: true }))); const [row] = await tx.update(supervisionDevices).set({ appManagementEnabled: enabled, selectionConfigured: enabled && deduped.length > 0, selectedAppCount: enabled ? deduped.length : 0, lastSeenAt: new Date(), updatedAt: new Date() }).where(eq(supervisionDevices.id, deviceId)).returning(); return row }); await this.auditConsentChange(userId, enabled); return updated }
  async approvedApps(userId: string, relationshipId: string) { const relationship = await this.guardian(userId, relationshipId); if ((relationship.permissions as { level?: Level }).level !== 'device_restrictions') throw new ForbiddenException('Device restriction permission is required.'); return this.approvedAppsForRelationship(relationship) }
  async deviceRestrictions(userId: string) { const relationships = await this.db.select().from(supervisionRelationships).where(and(eq(supervisionRelationships.supervisedUserId, userId), eq(supervisionRelationships.status, 'active'))); if (!relationships.length) return []; const rules = await this.db.select().from(supervisionRules).where(and(inArray(supervisionRules.relationshipId, relationships.map(r => r.id)), inArray(supervisionRules.status, ['scheduled', 'active']))).orderBy(desc(supervisionRules.startsAt)); const devices = await this.db.select({ id: supervisionDevices.id }).from(supervisionDevices).where(eq(supervisionDevices.userId, userId)); const apps = devices.length ? await this.db.select().from(supervisionManagedApps).where(and(inArray(supervisionManagedApps.deviceId, devices.map(d => d.id)), eq(supervisionManagedApps.enabledForGuardianManagement, true))) : []; return rules.map(rule => { const selected = new Set(((rule.appSelection as { managedAppIds?: string[] })?.managedAppIds ?? [])); return { ...rule, blockedPackages: apps.filter(app => selected.has(app.id)).map(app => app.platformAppIdentifier) } }) }
  async requestTemporaryAccess(userId: string, body: Record<string, unknown>) {
    const packageName = String(body.packageName ?? '').trim(), justification = String(body.justification ?? '').trim()
    if (!packageName || justification.length < 8 || justification.length > 2000) throw new BadRequestException('Please provide a short explanation for this access request.')
    if (/(disable\s+supervision|uninstall|device admin|administrative permission|permanent|unrestricted|إلغاء.*الإشراف|حذف.*بي\s*بلان)/iu.test(justification)) throw new ForbiddenException('Sensitive or permanent exceptions cannot be requested through Bee.')
    const [rule] = await this.db.select().from(supervisionRules).innerJoin(supervisionRelationships, eq(supervisionRules.relationshipId, supervisionRelationships.id)).where(and(eq(supervisionRelationships.supervisedUserId, userId), eq(supervisionRelationships.status, 'active'), inArray(supervisionRules.status, ['scheduled', 'active']))).orderBy(desc(supervisionRules.startsAt)).limit(1)
    if (!rule || !(((rule.supervision_rules.appSelection as { managedAppIds?: string[] })?.managedAppIds) ?? []).length) throw new ForbiddenException('No active restricted app rule was found.')
    const relationship = rule.supervision_relationships
    const devices = await this.db.select({ id: supervisionDevices.id }).from(supervisionDevices).where(eq(supervisionDevices.userId, userId)); const apps = devices.length ? await this.db.select().from(supervisionManagedApps).where(and(inArray(supervisionManagedApps.deviceId, devices.map(d => d.id)), eq(supervisionManagedApps.enabledForGuardianManagement, true), eq(supervisionManagedApps.platformAppIdentifier, packageName))) : []
    if (!apps.some(app => (((rule.supervision_rules.appSelection as { managedAppIds?: string[] }).managedAppIds ?? []).includes(app.id)))) throw new ForbiddenException('This app is not restricted by the active supervision rule.')
    const recent = await this.db.select({ id: supervisionAccessRequests.id }).from(supervisionAccessRequests).where(and(eq(supervisionAccessRequests.supervisedUserId, userId), gte(supervisionAccessRequests.createdAt, new Date(Date.now() - 60 * 60 * 1000))))
    if (recent.length >= 6) throw new ConflictException('Too many temporary-access requests. Please try again later.')
    const policy = String((relationship.permissions as Record<string, unknown>).ai_access_policy ?? 'ai_may_approve')
    let ai; try { ai = await this.evaluator.evaluate({ justification, packageName, appName: apps[0]?.displayName, recentRequestCount: recent.length }) } catch (error) { if (policy === 'ai_may_approve') throw error; ai = { decision: 'needs_supervisor' as const, confidence: 0, category: 'unclear' as const, reason: 'Your supervisor needs to review this request.', suggestedDurationMinutes: null } }
    const prohibited = new Set(['entertainment', 'social']); const autoAllowed = policy === 'ai_may_approve' && ai.decision === 'allow' && ai.confidence >= .7 && !prohibited.has(ai.category)
    const decision = autoAllowed ? 'allow' : policy === 'ai_may_approve' && ai.decision === 'deny' ? 'deny' : 'needs_supervisor'
    const minutes = autoAllowed ? ([5, 10, 15].includes(ai.suggestedDurationMinutes ?? 0) ? ai.suggestedDurationMinutes! : 10) : null; const expiresAt = minutes ? new Date(Date.now() + minutes * 60_000) : null
    const [request] = await this.db.insert(supervisionAccessRequests).values({ relationshipId: relationship.id, supervisedUserId: userId, ruleId: rule.supervision_rules.id, packageName, decision, category: ai.category, confidence: ai.confidence, reason: ai.reason.slice(0, 500), durationMinutes: minutes, decisionSource: autoAllowed ? 'ai' : 'policy', expiresAt }).returning()
    await this.log(relationship.id, userId, `access_${decision}`, rule.supervision_rules.id)
    return this.accessResponse(request, true)
  }
  async accessRequests(userId: string, relationshipId?: string) { const rows = await this.db.select().from(supervisionAccessRequests).where(relationshipId ? eq(supervisionAccessRequests.relationshipId, relationshipId) : eq(supervisionAccessRequests.supervisedUserId, userId)).orderBy(desc(supervisionAccessRequests.createdAt)); if (relationshipId) await this.guardian(userId, relationshipId); return rows.map(row => this.accessResponse(row, false)) }
  async supervisorDecision(userId: string, id: string, approve: boolean) { const [request] = await this.db.select().from(supervisionAccessRequests).where(eq(supervisionAccessRequests.id, id)); if (!request) throw new NotFoundException('Access request not found.'); await this.guardian(userId, request.relationshipId); if (request.decision !== 'needs_supervisor') throw new ConflictException('This request has already been decided.')
    const minutes = approve ? 10 : null, expiresAt = minutes ? new Date(Date.now() + minutes * 60_000) : null; const [updated] = await this.db.update(supervisionAccessRequests).set({ decision: approve ? 'allow' : 'deny', decisionSource: 'supervisor', durationMinutes: minutes, expiresAt, updatedAt: new Date() }).where(eq(supervisionAccessRequests.id, id)).returning(); await this.log(request.relationshipId, userId, approve ? 'access_supervisor_approved' : 'access_supervisor_denied', request.ruleId); return this.accessResponse(updated, true) }
  private accessResponse(row: typeof supervisionAccessRequests.$inferSelect, includeGrant: boolean) { const grant = includeGrant && row.decision === 'allow' && row.expiresAt ? this.grants.issue({ requestId: row.id, supervisedUserId: row.supervisedUserId, relationshipId: row.relationshipId, packageName: row.packageName, expiresAt: row.expiresAt.getTime(), decisionSource: row.decisionSource }) : null; return { id: row.id, relationshipId: row.relationshipId, packageName: row.packageName, decision: row.decision, category: row.category, confidence: row.confidence, reason: row.reason, durationMinutes: row.durationMinutes, decisionSource: row.decisionSource, expiresAt: row.expiresAt, signedGrant: grant?.token ?? null, createdAt: row.createdAt } }
  @Cron(CronExpression.EVERY_MINUTE)
  async reconcileRestrictions(now = new Date()) { const rules = await this.db.select().from(supervisionRules).where(inArray(supervisionRules.status, ['scheduled', 'active'])); for (const rule of rules) { if (rule.status === 'scheduled' && rule.startsAt <= now) { await this.db.update(supervisionRules).set({ status: 'active', updatedAt: now }).where(eq(supervisionRules.id, rule.id)); await this.log(rule.relationshipId, rule.createdBy, 'rule_started', rule.id); } let taskStatus: string | null = null; if (rule.taskId && ['task', 'task_or_time'].includes(rule.restrictionMode)) { const [task] = await this.db.select({ status: tasks.status }).from(tasks).where(eq(tasks.id, rule.taskId)); taskStatus = task?.status ?? null; } const reason = restrictionCompletionReason(rule, taskStatus, now); if (reason) { await this.db.update(supervisionRules).set({ status: 'completed', completedAt: now, updatedAt: now }).where(and(eq(supervisionRules.id, rule.id), inArray(supervisionRules.status, ['scheduled', 'active']))); await this.log(rule.relationshipId, rule.createdBy, reason === 'task_completed' ? 'rule_task_completed' : 'rule_time_expired', rule.id); } } }
  private async participant(userId: string, id: string) { const [row] = await this.db.select().from(supervisionRelationships).where(and(eq(supervisionRelationships.id, id), or(eq(supervisionRelationships.guardianUserId, userId), eq(supervisionRelationships.supervisedUserId, userId)))); if (!row) throw new NotFoundException('Supervision relationship not found.'); return row }
  private async guardian(userId: string, id: string) { const row = await this.participant(userId, id); if (row.guardianUserId !== userId || row.status !== 'active') throw new ForbiddenException('Guardian permission is required.'); return row }
  private async supervised(userId: string, id: string, status: string) { const row = await this.participant(userId, id); if (row.supervisedUserId !== userId || row.status !== status) throw new ForbiddenException('This request is not available.'); return row }
  private async rule(id: string) { const [row] = await this.db.select().from(supervisionRules).where(eq(supervisionRules.id, id)); if (!row) throw new NotFoundException('Study rule not found.'); return row }
  private async ruleForGuardian(userId: string, id: string) { const rule = await this.rule(id); await this.guardian(userId, rule.relationshipId); return rule }
  private async approvedAppsForRelationship(relationship: typeof supervisionRelationships.$inferSelect) { const devices = await this.db.select().from(supervisionDevices).where(and(eq(supervisionDevices.userId, relationship.supervisedUserId), eq(supervisionDevices.appManagementEnabled, true))); const result: Array<Record<string, unknown>> = []; for (const device of devices) { if (device.platform === 'ios') { if (device.selectionConfigured) result.push({ id: `ios:${device.id}`, deviceId: device.id, platform: 'ios', displayName: `${device.selectedAppCount} supervised apps configured`, selectionConfigured: true, selectedAppCount: device.selectedAppCount, categoriesConfigured: device.categoriesConfigured, capability: device.capabilityLevel === 'managed_device' ? 'managed_device_blocking' : 'accountability_only', enforceable: device.capabilityLevel === 'managed_device' }); continue; } const apps = await this.db.select().from(supervisionManagedApps).where(and(eq(supervisionManagedApps.deviceId, device.id), eq(supervisionManagedApps.enabledForGuardianManagement, true))); result.push(...apps.map(app => ({ id: app.id, deviceId: device.id, platform: 'android', displayName: app.displayName, iconReference: app.iconReference, capability: device.capabilityLevel === 'managed_device' ? 'managed_device_blocking' : device.permissionState === 'granted' ? 'intervention_only' : 'accountability_only', enforceable: device.capabilityLevel === 'managed_device' }))); } return result }
  private async auditConsentChange(userId: string, enabled: boolean) { const relationships = await this.db.select({ id: supervisionRelationships.id }).from(supervisionRelationships).where(and(eq(supervisionRelationships.supervisedUserId, userId), eq(supervisionRelationships.status, 'active'))); for (const relationship of relationships) await this.log(relationship.id, userId, enabled ? 'app_management_consent_updated' : 'app_management_consent_revoked') }
  private async log(relationshipId: string, actorUserId: string, event: string, ruleId?: string) { await this.db.insert(supervisionAuditLogs).values({ relationshipId, actorUserId, event, ruleId: ruleId ?? null }) }
  private capability(value: unknown) { const v = String(value ?? 'none'); if (!['none', 'accountability_only', 'device_restrictions', 'managed_device'].includes(v)) throw new BadRequestException('Invalid device capability.'); return v }
  private permission(value: unknown) { const v = String(value ?? 'not_requested'); if (!['not_requested', 'granted', 'denied', 'revoked', 'unavailable'].includes(v)) throw new BadRequestException('Invalid device permission state.'); return v }
  private async withIdentities<T extends { guardianUserId: string; supervisedUserId: string }>(rows: T[], currentUserId?: string) { const ids = [...new Set(rows.flatMap(r => [r.guardianUserId, r.supervisedUserId]))]; const people = ids.length ? await this.db.select({ id: users.id, displayName: users.fullName, username: users.username, avatarUrl: users.avatarUrl }).from(users).where(inArray(users.id, ids)) : []; const byId = new Map(people.map(p => [p.id, p])); return rows.map(row => ({ ...row, currentRole: currentUserId ? row.guardianUserId === currentUserId ? 'guardian' : 'supervised' : undefined, guardian: byId.get(row.guardianUserId) ?? { id: row.guardianUserId, displayName: 'BeePlan user', username: null, avatarUrl: null }, supervisedUser: byId.get(row.supervisedUserId) ?? { id: row.supervisedUserId, displayName: 'BeePlan user', username: null, avatarUrl: null } })) }
}
