import { useEffect, useRef, useState } from 'react'

export function VoiceRecorder({ onRecorded }: { onRecorded: (file: File) => void }) {
  const recorder = useRef<MediaRecorder | null>(null), stream = useRef<MediaStream | null>(null), chunks = useRef<Blob[]>([])
  const [recording, setRecording] = useState(false), [seconds, setSeconds] = useState(0), [error, setError] = useState(''), [preview, setPreview] = useState<string>()
  useEffect(() => () => { recorder.current?.stop(); stream.current?.getTracks().forEach(track => track.stop()); if (preview) URL.revokeObjectURL(preview) }, [preview])
  async function start() { setError(''); if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) { setError('Voice recording is not supported by this browser.'); return } try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current=[]; const r=new MediaRecorder(stream.current); recorder.current=r; r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)}; r.onstop=()=>{ const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'}), url=URL.createObjectURL(blob); setPreview(previous=>{if(previous)URL.revokeObjectURL(previous);return url}); onRecorded(new File([blob],`voice-${Date.now()}.webm`,{type:blob.type})); stream.current?.getTracks().forEach(t=>t.stop()); setRecording(false) }; r.start(); setSeconds(0); setRecording(true) } catch { setError('Microphone permission was denied or is unavailable.') } }
  useEffect(()=>{if(!recording)return;const id=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[recording])
  return <div className="mt-3 rounded-xl border border-white/10 bg-slate-800 p-3"><div className="flex items-center gap-3"><button type="button" onClick={()=>recording?recorder.current?.stop():void start()} className="rounded-lg bg-[#FDEF4B] px-3 py-2 font-bold text-slate-950">{recording?'Stop':'Record voice'}</button><span className="text-sm text-slate-300">{recording?`Recording ${seconds}s`:'Voice note (optional)'}</span></div>{preview&&<audio className="mt-3 w-full" controls src={preview}/>} {error&&<p role="alert" className="mt-2 text-sm text-red-300">{error}</p>}</div>
}
