import { apiRequest, API_BASE_URL } from './api'
export type Achievement = { id: string; title: string; description: string; reflection: string; achievementDate: string; category: string; relatedTaskId?: string | null; images: { id: string; url: string; isCover: boolean; fileName: string }[]; stats: { completedTasks: number; focusSessions: number; focusedMinutes: number; collaborators: number } | null }
export type YearReview = { year: number; achievements: Achievement[]; availableYears: number[]; stats: { achievements: number; memories: number; completedLinkedTasks: number; focusSessions: number; focusedMinutes: number } }
export const achievementCategories = ['All', 'Education', 'Career', 'Skills', 'Personal', 'Learning', 'Health', 'Financial', 'Milestone', 'Other']
export async function getAchievements(token: string, filters: { search?: string; category?: string; year?: string } = {}) { const query = new URLSearchParams(Object.entries(filters).filter(([, v]) => v && v !== 'All') as [string, string][]).toString(); return apiRequest(`/achievements${query ? `?${query}` : ''}`, { headers: { Authorization: `Bearer ${token}` } }) as Promise<Achievement[]> }
export async function getYearReview(token: string, year: number) { return apiRequest(`/achievements/year/${year}/review`, { headers: { Authorization: `Bearer ${token}` } }) as Promise<YearReview> }
export async function createAchievement(token: string, payload: object) { return apiRequest('/achievements', { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: JSON.stringify(payload) }) as Promise<Achievement> }
export async function deleteAchievement(token: string, id: string) { await apiRequest(`/achievements/${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }) }
export async function updateAchievement(token: string, id: string, payload: object) { return apiRequest(`/achievements/${id}`, { method: 'PATCH', headers: { Authorization: `Bearer ${token}` }, body: JSON.stringify(payload) }) as Promise<Achievement> }
export async function uploadAchievementImage(token: string, id: string, file: File) { const body = new FormData(); body.append('file', file); return apiRequest(`/achievements/${id}/images`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body }) }
export async function deleteAchievementImage(token: string, id: string, imageId: string) { await apiRequest(`/achievements/${id}/images/${imageId}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }) }
export async function setAchievementCover(token: string, id: string, imageId: string) { return apiRequest(`/achievements/${id}/images/${imageId}/cover`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }) as Promise<Achievement> }
export function achievementImageUrl(id: string, imageId: string) { return `${API_BASE_URL}/achievements/${id}/images/${imageId}` }
